import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';
import{initializeNativeTikTokCreators,validateTikTokRuntime,validateTikTokCheck,validateTikTokDraft}from'../native-tiktok-creators.mjs';
const fixture=JSON.parse(readFileSync(new URL('./fixtures/native-tiktok-creator-v1.json',import.meta.url)));assert.equal(fixture.fixture_kind,'explicit_protocol_mock_not_owner_or_real_provider_acceptance');
const page=(kind,items)=>({schema_version:'native-tiktok-creator-page-v1',kind,workspace_id:fixture.pending.workspace_id,project_id:fixture.project.id,items,next_cursor:null,truncated:false,token_returned:false,publishing_enabled:false});
function harness(){const nodes=new Map();class Node{constructor(){this.children=[];this.value='';this.checked=false;this.dataset={};this.listeners={};this.textContent='';}set id(v){this._id=v;nodes.set(v,this);}get id(){return this._id;}append(...v){this.children.push(...v);}replaceChildren(...v){this.children=[...v];}addEventListener(k,v){this.listeners[k]=v;}removeAttribute(k){delete this[k];}}
  const root={createElement:()=>new Node(),getElementById(v){if(!nodes.has(v))nodes.set(v,new Node());return nodes.get(v);}},get=v=>root.getElementById('native-tiktok-'+v),state={workspace_id:fixture.pending.workspace_id,project:structuredClone(fixture.project),canManage:true,busy:false,dirty:false,active:false},calls=[],messages=[];let time=Date.parse(fixture.pending.snapshot.consented_at),keys=0,handler;
  const defaultHandler=async(path,body)=>{if(path==='/api/connections/tiktok-creators')return structuredClone(fixture.runtime);if(path.endsWith('/fetch'))return structuredClone(fixture.succeeded);
    if(path.endsWith('/cancel'))return{...structuredClone(fixture.succeeded),status:'cancelled'};if(body)return structuredClone(path.endsWith('/drafts')?fixture.draft:fixture.pending);
    return page(path.includes('/drafts')?'draft':'check',[structuredClone(path.includes('/drafts')?fixture.draft:fixture.succeeded)]);};handler=defaultHandler;
  const controller=initializeNativeTikTokCreators({root,getState:()=>({...state}),api:async(...args)=>{calls.push(args);return handler(...args);},onMessage:(...v)=>messages.push(v),uuid:()=> 'explicit-tiktok-ui-key-'+(++keys),now:()=>time});
  return{root,get,state,calls,messages,controller,defaultHandler,handler:v=>{handler=v;},time:v=>{time=v;}};}
async function ready(h){await h.controller.readConfig();h.get('read-ack').checked=h.get('mock-ack').checked=true;h.controller.controls();}
async function creator(h){await ready(h);await h.controller.createCheck();await h.controller.fetchCheck();}
function choices(h){h.get('final').value=fixture.job.id;h.get('title').value=fixture.draft.snapshot.request.metadata.title;h.get('hashtags').value='#tiktok #fixture #tiktok';h.get('privacy').value='SELF_ONLY';h.get('aigc').checked=h.get('video-ack').checked=h.get('ai-ack').checked=h.get('music-ack').checked=true;h.controller.controls();}
test('actual retained public DTOs validate without secret or publish authority',()=>{const h=harness();validateTikTokRuntime(fixture.runtime,h.state.workspace_id);});
test('initialization has no provider request, privacy default or interaction opt-in',()=>{const h=harness();assert.deepEqual(h.calls,[]);assert.equal(h.get('privacy').value,'');for(const k of['comment','duet','stitch','disclosure','aigc','music-ack','video-ack'])assert.equal(h.get(k).checked,false);assert.equal(h.get('prepare').disabled,true);});
test('prepare requires separate read and mock consent then two-step account creator fetch',async()=>{const h=harness();await h.controller.readConfig();h.get('read-ack').checked=true;await h.controller.createCheck();assert.equal(h.calls.length,1);h.get('mock-ack').checked=true;await h.controller.createCheck();assert.equal(h.controller.current().status,'pending');assert.equal(h.calls.at(-1)[1].acknowledged_creator_read,true);await h.controller.fetchCheck();assert.equal(h.controller.current().status,'succeeded');assert.ok(h.get('detail').textContent.includes(fixture.succeeded.result.creator.nickname));assert.equal(h.get('privacy').value,'');assert.equal(h.get('duet').disabled,true);assert.equal(h.calls.filter(([,b])=>b).length,2);});
test('unsent draft binds original creator, exact approved final, explicit AI music and normalized hashtags',async()=>{const h=harness();await creator(h);choices(h);await h.controller.createDraft();assert.equal(h.controller.currentDraft()?.draft_id,fixture.draft.draft_id);assert.equal(h.calls.at(-1)[0],'/api/projects/'+fixture.project.id+'/tiktok-creators/drafts');const b=h.calls.at(-1)[1];assert.deepEqual(b.metadata.hashtags,['tiktok','fixture']);assert.equal(b.expected_final_sha256,fixture.job.result.qc.final_sha256);assert.equal(b.choices.disable_duet,true);assert.equal(b.acknowledged_ai_disclosure,true);assert.equal(h.controller.currentDraft().publishing_enabled,false);assert.equal(h.get('music-ack').checked,false);assert.ok(!h.calls.some(([p])=>p.includes('/publish')||p.includes('/official-publications')));});
test('privacy stays empty and brand disclosure starts off; required choices gate drafts',async()=>{const h=harness();await creator(h);choices(h);h.get('privacy').value='';const n=h.calls.length;await h.controller.createDraft();assert.equal(h.calls.length,n);h.get('privacy').value='PUBLIC_TO_EVERYONE';await h.controller.createDraft();assert.equal(h.calls.length,n);h.get('privacy').value='SELF_ONLY';h.get('disclosure').checked=true;await h.controller.createDraft();assert.equal(h.calls.length,n);h.get('branded').checked=h.get('brand-ack').checked=true;await h.controller.createDraft();assert.equal(h.calls.length,n);});
test('video review AI review and music consent are independently mandatory',async()=>{for(const key of['video-ack','ai-ack','music-ack']){const h=harness();await creator(h);choices(h);h.get(key).checked=false;const n=h.calls.length;await h.controller.createDraft();assert.equal(h.calls.length,n);}});
test('viewer dirty busy active archived and expired creator cannot create drafts',async()=>{for(const change of[{canManage:false},{dirty:true},{busy:true},{active:true},{project:{...fixture.project,archived:true}}]){const h=harness();await creator(h);choices(h);Object.assign(h.state,change);const n=h.calls.length;await h.controller.createDraft();assert.equal(h.calls.length,n);}const h=harness();await creator(h);choices(h);h.time(Date.parse(fixture.pending.snapshot.deadline));const n=h.calls.length;await h.controller.createDraft();assert.equal(h.calls.length,n);});
test('failed or revoked creator proof never becomes draft authority',async()=>{const h=harness();await ready(h);h.handler(async()=>page('check',[{...structuredClone(fixture.succeeded),status:'cancelled'}]));await h.controller.readHistory();choices(h);const n=h.calls.length;await h.controller.createDraft();assert.equal(h.calls.length,n);assert.equal(h.controller.currentDraft(),null);});
test('history is scoped and bounded; wrong cursor, target, mock or private fields fail closed',()=>{const h=harness();for(const change of[v=>{v.project_id='f'.repeat(32);},v=>{v.snapshot.factory.target.platform='youtube';},v=>{v.result.mock=false;},v=>{v.snapshot.token_file='C:/private';},v=>{v.result.creator.duet_disabled=1;}]){const v=structuredClone(fixture.succeeded);change(v);assert.throws(()=>validateTikTokCheck(v,h.state));}validateTikTokCheck(fixture.succeeded,h.state);validateTikTokDraft(fixture.draft,h.state);});
test('unknown create result reuses original key only on another explicit click',async()=>{const h=harness();await ready(h);h.handler(async()=>{throw Error('unknown');});await h.controller.createCheck();const key=h.calls.at(-1)[1].request_key;assert.equal(h.controller.current(),null);await h.controller.createCheck();assert.equal(h.calls.at(-1)[1].request_key,key);assert.equal(h.calls.filter(([,b])=>b).length,2);});
test('late reply cannot change creator or draft in a different project context',async()=>{const h=harness();await ready(h);let reply;h.handler(()=>new Promise(r=>{reply=r;}));const pending=h.controller.createCheck();h.state.project={id:'f'.repeat(32),revision:1};h.controller.sync();reply(structuredClone(fixture.pending));await pending;assert.equal(h.controller.current(),null);assert.ok(h.messages.length);});
test('changed original fetch snapshot is rejected without attaching response',async()=>{const h=harness();await ready(h);await h.controller.createCheck();h.handler(async()=>{const v=structuredClone(fixture.succeeded);v.snapshot.document_sha256='f'.repeat(64);return v;});await h.controller.fetchCheck();assert.equal(h.controller.current().status,'pending');});
test('current final changes clear choices and never reuse another final review',async()=>{const h=harness();await creator(h);choices(h);h.state.project.jobs[0].final_review.artifact_sha256='f'.repeat(64);h.controller.sync();assert.equal(h.controller.current(),null);assert.equal(h.get('privacy').value,'');assert.equal(h.get('video-ack').checked,false);assert.equal(h.get('save').disabled,true);});
test('long UTF16 caption or unavailable creator interaction blocks unsent draft',async()=>{const h=harness();await creator(h);choices(h);const n=h.calls.length;h.get('caption').value='😀'.repeat(1100);await h.controller.createDraft();assert.equal(h.calls.length,n);h.get('caption').value='';h.get('duet').checked=true;h.controller.controls();assert.equal(h.get('duet').checked,false);assert.equal(h.get('duet').disabled,true);});
test('Native Studio connects card controls sync and same signed local routes',()=>{const html=readFileSync(new URL('../native.html',import.meta.url),'utf8'),js=readFileSync(new URL('../native.mjs',import.meta.url),'utf8');assert.ok(html.includes('id="native-tiktok-creators-card"'));assert.ok(js.includes('tiktokCreatorsUI?.controls()'));assert.ok(js.includes('tiktokCreatorsUI?.sync()'));assert.ok(js.includes('initializeNativeTikTokCreators'));});
