import test from 'node:test';import assert from 'node:assert/strict';
import {validateOfficialThumbnailStage} from '../native-official-publications.mjs';
const sha='a'.repeat(64),id='ast_rthumb_'+'b'.repeat(32);
const row=()=>({publication_id:'nopu_'+'c'.repeat(32),workspace_id:'wsp_fixture',project_id:'d'.repeat(32),snapshot_sha256:sha,mock:true,receipt:null,
 snapshot:{metadata:{thumbnail_asset_id:id},final_job_id:'e'.repeat(32),final_sha256:sha,document_sha256:sha,final_job_snapshot_sha256:sha,
 thumbnail:{schema_version:'native-publication-thumbnail-review-v1',workspace_id:'wsp_fixture',project_id:'d'.repeat(32),thumbnail_asset_id:id,render_job_id:'e'.repeat(32),final_sha256:sha,document_sha256:sha,
 render_snapshot_sha256:sha,thumbnail_snapshot_sha256:sha,image:{sha256:sha,content_type:'image/png',rights_status:'unknown',license:null},status:'passed',scope:'dry_run_metadata_review',
 original_source_rights_review_still_required:true,publishing_authorized:false,rights_independently_verified:false}}});
const stage=(r,status='not_started')=>({schema_version:'native-official-thumbnail-stage-v1',publication_id:r.publication_id,workspace_id:r.workspace_id,project_id:r.project_id,snapshot_sha256:r.snapshot_sha256,
 mock:r.mock,status,image_sha256:sha,intent_sha256:status==='not_started'?null:sha,response_sha256:status==='response_received'?sha:null,result_sha256:status==='response_received'?sha:null,
 remote_post_id:status==='not_started'?null:'FIXTURE0001',provider_response_acknowledged:status==='response_received',remote_image_bytes_verified:false,rights_independently_verified:false,
 publishing_authorized:false,automatic_retry:false,token_returned:false});
test('legacy metadata preserves omitted stage and rejects an unrelated extra stage',()=>{const r={snapshot:{metadata:{}},receipt:null};assert.equal(validateOfficialThumbnailStage(undefined,r),null);assert.throws(()=>validateOfficialThumbnailStage({},r));});
test('requested original PNG can remain not started and missing stage cannot certify a receipt',()=>{const r=row(),s=stage(r);assert.equal(validateOfficialThumbnailStage(s,r),s);assert.equal(validateOfficialThumbnailStage(undefined,r),null);r.receipt={remote_post_id:'FIXTURE0001'};assert.throws(()=>validateOfficialThumbnailStage(undefined,r));assert.throws(()=>validateOfficialThumbnailStage(s,r));});
test('response acknowledgement supports only the exact synthetic video receipt without rights or pixel authority',()=>{const r=row(),s=stage(r,'response_received');r.receipt={remote_post_id:'FIXTURE0001'};assert.equal(validateOfficialThumbnailStage(s,r),s);r.receipt.remote_post_id='OTHERID0001';assert.throws(()=>validateOfficialThumbnailStage(s,r));});
test('unknown and pending evidence can be reviewed but never used as completion',()=>{for(const status of ['dispatch_intent','outcome_unknown']){const r=row(),s=stage(r,status);assert.equal(validateOfficialThumbnailStage(s,r),s);r.receipt={remote_post_id:'FIXTURE0001'};assert.throws(()=>validateOfficialThumbnailStage(s,r));}});
test('foreign workspace image snapshot mock and authority relabels fail',()=>{const r=row(),s=stage(r,'response_received');for(const change of [{workspace_id:'wsp_foreign'},{image_sha256:'f'.repeat(64)},{snapshot_sha256:'f'.repeat(64)},{mock:false},{provider_response_acknowledged:1},{publishing_authorized:true},{automatic_retry:true},{remote_image_bytes_verified:true}])assert.throws(()=>validateOfficialThumbnailStage({...s,...change},r));});
test('changed original render document source rights or omitted response hashes fail',()=>{const r=row(),s=stage(r,'response_received');for(const change of [{render_job_id:'f'.repeat(32)},{document_sha256:'f'.repeat(64)},{publishing_authorized:true},{rights_independently_verified:true}]){const changed=structuredClone(r);Object.assign(changed.snapshot.thumbnail,change);assert.throws(()=>validateOfficialThumbnailStage(s,changed));}for(const change of [{response_sha256:null},{result_sha256:null},{status:'completed'},{result_sha256:true}])assert.throws(()=>validateOfficialThumbnailStage({...s,...change},r));});
test('not-started state cannot hide an already issued intent or a remote video',()=>{const r=row(),s=stage(r);for(const change of [{intent_sha256:sha},{response_sha256:sha},{result_sha256:sha},{remote_post_id:'FIXTURE0001'}])assert.throws(()=>validateOfficialThumbnailStage({...s,...change},r));});
