import test from 'node:test';import assert from 'node:assert/strict';
import {initializeNativeQualifiedLearning}from'../native-qualified-learning.mjs';
const workspace='wsp_qualified_learning_fixture',project='a'.repeat(32),sha='b'.repeat(64),keys=['trend_family','hook','duration','visual_strategy','subtitle_style','voice_profile','publishing_window'];
const consumerKeys={trend_radar:['trend_family'],idea_engine:['hook','duration'],media_planner:['visual_strategy','duration','voice_profile'],template_recommendations:['subtitle_style']};
function learning(positive=false){const dimensions=keys.map(dimension=>({dimension,state:positive&&dimension==='subtitle_style'?'recommendations_available':'insufficient_data',missing_feature_posts:0,groups_truncated:false,
  groups:positive&&dimension==='subtitle_style'?[{value:'karaoke@1',state:'recommendation_candidate',sample_count:3,control_count:3,median_assessment_score:90,control_median_score:50,score_difference:40,snapshot_ids:['noam_1','noam_2','noam_3'],control_snapshot_ids:['noam_4','noam_5','noam_6']}]:[]}));
  return{workspace_id:workspace,project_id:project,learning_id:'nols_'+'c'.repeat(32),snapshot_sha256:sha,publication_id:'nopu_'+'d'.repeat(32),anchor_assessment_id:'nowa_'+'e'.repeat(32),anchor_result_snapshot_id:'noam_'+'f'.repeat(32),
    mock:true,real_audience_observation:false,recommendation_only:true,automatic_action:false,status:positive?'recommendations_available':'insufficient_data',observation_count:positive?6:0,dimensions,
    snapshot:{scope:{workspace_id:workspace,mock:true,channel_profile_ref:'ai-education-reference@1',channel_profile_sha256:'1'.repeat(64),platform:'youtube'},request:{expected_assessment_sha256:'2'.repeat(64)},
      anchor_candidate_sha256:'3'.repeat(64),winner_policy_sha256:'4'.repeat(64),winner_factor_basis_sha256:'5'.repeat(64)}};}
function sourceBinding(l){return{project_id:l.project_id,learning_id:l.learning_id,learning_sha256:l.snapshot_sha256,publication_id:l.publication_id,anchor_assessment_id:l.anchor_assessment_id,
  anchor_assessment_sha256:l.snapshot.request.expected_assessment_sha256,anchor_candidate_sha256:l.snapshot.anchor_candidate_sha256,anchor_result_snapshot_id:l.anchor_result_snapshot_id,winner_policy_sha256:l.snapshot.winner_policy_sha256,winner_factor_basis_sha256:l.snapshot.winner_factor_basis_sha256};}
function result(l,body){const{request_key,...request}=body;return{schema_version:'native-qualified-learning-feedback-result-v1',workspace_id:workspace,idempotent_replay:false,record_sha256:'6'.repeat(64),
  recommendation_only:true,automatic_application:false,provider_calls:0,publishing_enabled:false,token_returned:false,record:{schema_version:'native-trend-radar-record-v1',id:'7'.repeat(32),version:1,record_type:'learning',workspace_id:workspace,
    payload:{schema_version:'native-qualified-learning-feedback-v1',request,request_sha256:'8'.repeat(64),scope:structuredClone(l.snapshot.scope),source_binding:sourceBinding(l),recommendations:structuredClone(l.dimensions),
      consumers:Object.fromEntries(Object.entries(consumerKeys).map(([key,d])=>[key,structuredClone(l.dimensions.filter(v=>d.includes(v.dimension)))])),status:l.status,observation_count:l.observation_count,mock:l.mock,real_audience_observation:!l.mock,
      recommendation_only:true,automatic_production:false,autonomous_execution:false,automatic_application:false,publishing_enabled:false,provider_calls:0,external_call:false,token_returned:false,
      channel_selection:{profile_sha256:l.snapshot.scope.channel_profile_sha256,profile:{profile_ref:l.snapshot.scope.channel_profile_ref}}}}};}
function templateResult(p){const g=p.record.payload.consumers.template_recommendations[0].groups[0];return{schema_version:'native-qualified-learning-template-suggestions-v1',workspace_id:workspace,projection_id:p.record.id,projection_sha256:p.record_sha256,
  source_binding:p.record.payload.source_binding,catalog_sha256:'9'.repeat(64),catalog_version:'subtitle-catalog-v1',mock:p.record.payload.mock,real_audience_observation:!p.record.payload.mock,recommendation_only:true,automatic_application:false,
  human_selection_required:true,provider_calls:0,publishing_enabled:false,token_returned:false,suggestions_truncated:false,unmatched_historical_styles:[],suggestions:g?[{recorded_subtitle_feature:g.value,template_ref:'karaoke@1',name:'Tiếng Việt karaoke',style:{mode:'karaoke'},
    requires_word_timestamps:true,historical_full_style_verified:false,match_kind:'recorded_template_reference',human_selection_required:true,automatic_application:false,sample_count:g.sample_count,control_count:g.control_count,score_difference:g.score_difference,snapshot_ids:g.snapshot_ids,control_snapshot_ids:g.control_snapshot_ids}]:[]};}
function harness(positive=false){const nodes=new Map();class Node{constructor(){this.children=[];this.checked=false;this.dataset={};this.listeners={};this.textContent='';}set id(v){this._id=v;nodes.set(v,this);}get id(){return this._id;}append(...v){this.children.push(...v);}replaceChildren(...v){this.children=[...v];}addEventListener(k,v){this.listeners[k]=v;}}
  const root={createElement:()=>new Node(),getElementById(v){if(!nodes.has(v))nodes.set(v,new Node());return nodes.get(v);}},get=id=>root.getElementById('native-qualified-learning-'+id),state={workspace_id:workspace,project:{id:project,revision:1},canManage:true,busy:false,dirty:false,active:false},calls=[],messages=[];
  let selected=learning(positive),handler,count=0,saved;const defaultHandler=async(path,body)=>body?(saved=result(selected,body)):templateResult(saved);
  handler=defaultHandler;const controller=initializeNativeQualifiedLearning({root,getState:()=>({...state}),getBinding:()=>({learning:selected}),api:async(...v)=>{calls.push(v);return handler(...v);},onWorking:v=>{state.busy=v;},onMessage:(...v)=>messages.push(v),uuid:()=> 'explicit-projection-key-'+(++count)});
  return{get,state,calls,messages,controller,defaultHandler,handler:v=>handler=v,learning:v=>selected=v,current:()=>selected};}
const ack=h=>{h.get('ack').checked=h.get('mock-ack').checked=true;h.controller.controls();};
test('initialization and synchronization remain inert without implicit API calls',async()=>{const h=harness();h.controller.sync();h.controller.controls();await h.controller.readTemplates();assert.equal(h.calls.length,0);assert.equal(h.get('create').disabled,true);});
test('explicit projection binds exact saved learning hash channel platform and raw acknowledgements',async()=>{const h=harness();ack(h);await h.controller.createProjection();assert.deepEqual(h.calls[0],['/api/trends/learning/qualified',{schema_version:'native-qualified-learning-feedback-request-v1',project_id:project,learning_id:h.current().learning_id,expected_learning_sha256:sha,
  channel_profile_ref:'ai-education-reference@1',platform:'youtube',acknowledged_recommendation_only:true,acknowledged_protocol_mock:true,request_key:'native-qualified-learning-explicit-projection-key-1'}]);assert.equal(h.messages.length,0);assert.equal(h.get('consumers').children.length,4);assert.equal(h.get('ack').checked,false);assert.match(h.get('status').textContent,/chưa có phản hồi khán giả thật/);});
test('missing acknowledgement and viewer cannot project and busy work cannot read or save',async()=>{const h=harness();await h.controller.createProjection();h.get('ack').checked=true;await h.controller.createProjection();h.state.canManage=false;ack(h);await h.controller.createProjection();h.state.canManage=true;h.state.busy=true;await h.controller.createProjection();await h.controller.readTemplates();assert.equal(h.calls.length,0);});
test('foreign learning mock relabel unsupported channel and malformed source digest never call API',async()=>{for(const change of[l=>l.workspace_id='wsp_foreign',l=>l.project_id='0'.repeat(32),l=>l.mock=1,l=>l.real_audience_observation=true,l=>l.snapshot_sha256='bad',l=>l.snapshot.scope.channel_profile_sha256='bad',l=>l.snapshot.scope.channel_profile_ref='unversioned',l=>l.snapshot.scope.platform='unknown']){const h=harness(),l=learning();change(l);h.learning(l);h.controller.sync();ack(h);await h.controller.createProjection();assert.equal(h.calls.length,0);assert.equal(h.messages.length,1);}});
test('uncertain projection key survives retry and project revision or role changes',async()=>{const h=harness();ack(h);h.handler(async()=>{throw new Error('Uncertain reply');});await h.controller.createProjection();const key=h.calls[0][1].request_key;h.state.project.revision++;h.controller.sync();h.state.canManage=false;h.controller.sync();h.state.canManage=true;h.controller.sync();ack(h);h.handler(h.defaultHandler);await h.controller.createProjection();assert.equal(h.calls.at(-1)[1].request_key,key);});
test('known replay preserves request identity and prevents duplicate projections',async()=>{const h=harness();ack(h);await h.controller.createProjection();const key=h.calls[0][1].request_key;ack(h);await h.controller.createProjection();assert.equal(h.calls[1][1].request_key,key);assert.equal(h.calls.length,2);});
test('changed saved learning hash gets its own key and returning to original preserves original key',async()=>{const h=harness();ack(h);await h.controller.createProjection();const key=h.calls[0][1].request_key,original=learning(),changed=learning();changed.snapshot_sha256='0'.repeat(64);h.learning(changed);h.controller.sync();ack(h);await h.controller.createProjection();assert.notEqual(h.calls.at(-1)[1].request_key,key);h.learning(original);h.controller.sync();ack(h);await h.controller.createProjection();assert.equal(h.calls.at(-1)[1].request_key,key);});
test('cross-workspace or project namespace resets cannot reuse another workspace key',async()=>{const h=harness();ack(h);await h.controller.createProjection();const key=h.calls[0][1].request_key;h.state.project.id='0'.repeat(32);h.controller.sync();h.state.project.id=project;h.controller.sync();ack(h);await h.controller.createProjection();assert.notEqual(h.calls.at(-1)[1].request_key,key);});
test('late projection cannot cross workspace project role selected learning revision or archive change',async()=>{for(const change of[h=>h.state.workspace_id='wsp_other',h=>h.state.project.id='0'.repeat(32),h=>h.state.canManage=false,h=>h.state.project.revision++,h=>h.state.project.archived=true,h=>h.learning({...learning(),snapshot_sha256:'0'.repeat(64)})]){const h=harness();ack(h);let release;h.handler((path,body)=>new Promise(resolve=>{release=()=>resolve(result(learning(),body));}));const pending=h.controller.createProjection();change(h);h.controller.sync();release();await pending;assert.equal(h.get('detail').textContent,'');assert.equal(h.messages.length,0);assert.equal(h.state.busy,false);}});
test('foreign response request hash binding dimensions or controls are rejected and key retained',async()=>{for(const change of[v=>v.workspace_id='other',v=>v.record_sha256='bad',v=>v.provider_calls=1,v=>v.publishing_enabled=true,v=>v.record.payload.request.expected_learning_sha256='0'.repeat(64),v=>v.record.payload.source_binding.learning_sha256='0'.repeat(64),v=>v.record.payload.channel_selection.profile_sha256='0'.repeat(64),v=>v.record.payload.consumers.idea_engine=[],v=>v.record.payload.real_audience_observation=true,v=>v.record.payload.automatic_application=true]){const h=harness();ack(h);h.handler(async(path,body)=>{const v=result(h.current(),body);change(v);return v;});await h.controller.createProjection();assert.equal(h.get('detail').textContent,'');assert.equal(h.messages.length,1);const key=h.calls[0][1].request_key;ack(h);h.handler(h.defaultHandler);await h.controller.createProjection();assert.equal(h.calls.at(-1)[1].request_key,key);}});
test('sparse templates show insufficient evidence without applying timeline or loading provider',async()=>{const h=harness();ack(h);await h.controller.createProjection();await h.controller.readTemplates();assert.equal(h.calls.length,2);assert.equal(h.calls[1][0],'/api/trends/learning/qualified/'+'7'.repeat(32)+'/templates');assert.match(h.get('suggestions').children[0].textContent,/Chưa có khuyến nghị/);assert.equal(h.messages.length,0);});
test('positive subtitle association displays manual choice word timing and historical style limit',async()=>{const h=harness(true);ack(h);await h.controller.createProjection();await h.controller.readTemplates();assert.match(h.get('consumers').children[3].children[2].textContent,/Nhóm 3 \/ đối chiếu 3 · Chênh lệch 40/);assert.match(h.get('suggestions').children[0].textContent,/Cần thời điểm từng từ/);assert.match(h.get('suggestions').children[0].textContent,/Chọn và lưu riêng/);assert.match(h.get('suggestions').children[0].textContent,/chưa xác minh/);assert.equal(h.calls.length,2);});
test('template source digest flags group counts evidence and historical verification drift are rejected',async()=>{for(const change of[v=>v.projection_sha256='0'.repeat(64),v=>v.source_binding.learning_sha256='0'.repeat(64),v=>v.mock=1,v=>v.automatic_application=true,v=>v.suggestions[0].sample_count=2,v=>v.suggestions[0].score_difference='40',v=>v.suggestions[0].snapshot_ids=['other'],v=>v.suggestions[0].historical_full_style_verified=true,v=>v.suggestions[0].requires_word_timestamps=1,v=>v.suggestions[0].recorded_subtitle_feature='unknown']){const h=harness(true);ack(h);await h.controller.createProjection();h.handler(async()=>{const v=templateResult(result(h.current(),h.calls[0][1]));change(v);return v;});await h.controller.readTemplates();assert.equal(h.get('suggestions').children.length,0);assert.equal(h.messages.length,1);}});
test('late template response is discarded after selected source change',async()=>{const h=harness(true);ack(h);await h.controller.createProjection();let release;h.handler(()=>new Promise(resolve=>{release=()=>resolve(templateResult(result(h.current(),h.calls[0][1])));}));const pending=h.controller.readTemplates();h.state.project.revision++;h.controller.sync();release();await pending;assert.equal(h.get('suggestions').children.length,0);assert.equal(h.get('detail').textContent,'');assert.equal(h.messages.length,0);});
test('real audience source uses raw false mock acknowledgement and honest qualifier',async()=>{const h=harness(),l=learning();l.mock=l.snapshot.scope.mock=false;l.real_audience_observation=true;h.learning(l);h.controller.sync();h.get('ack').checked=true;h.controller.controls();await h.controller.createProjection();assert.equal(h.calls[0][1].acknowledged_protocol_mock,false);assert.match(h.get('status').textContent,/quan sát nền tảng/);assert.equal(h.get('mock-ack').disabled,false);assert.equal(h.messages.length,0);});
