import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';
import{initializeNativeOfficialVision,validateOfficialVisionRuntime,validateOfficialVisionHistory}from'../native-official-vision.mjs';
const fixture=JSON.parse(readFileSync(new URL('./fixtures/native-official-vision-v1.json',import.meta.url)));assert.equal(fixture.fixture_kind,'explicit_nonplayable_protocol_mock_not_provider_or_owner_acceptance');const seed=fixture.histories[0];
const clone=v=>structuredClone(v),page=(seed,items,cursor=null)=>({schema_version:'native-official-vision-page-v1',workspace_id:seed.workspace_id,project_id:seed.project_id,items,next_cursor:cursor,limit:25,automatic_dispatch:false,publishing_enabled:false,owner_uat_accepted:false});
function pending(seed,body){const v=clone(seed);v.status='approved';v.claim_id=v.cost_operation_id=v.response_id=v.result_sha256=v.result=v.response=null;v.snapshot.request={...body};delete v.snapshot.request.request_key;v.snapshot.deadline=new Date(Date.parse(v.snapshot.approved_at)+body.valid_for_seconds*1000).toISOString();v.idempotent_replay=false;return v;}
function harness(saved=seed){const nodes=new Map();class Node{constructor(){this.children=[];this.value='';this.checked=false;this.dataset={};this.listeners={};this.textContent='';this.style={};}set id(v){this._id=v;nodes.set(v,this);}get id(){return this._id;}append(...v){this.children.push(...v);}replaceChildren(...v){this.children=[...v];}addEventListener(k,v){this.listeners[k]=v;}}
 const root={createElement:()=>new Node(),getElementById(v){if(!nodes.has(v))nodes.set(v,new Node());return nodes.get(v);}},get=id=>root.getElementById('native-official-vision-'+id),state={workspace_id:saved.workspace_id,project:{id:saved.project_id,revision:saved.snapshot.request.revision},canManage:true,dirty:false,busy:false,active:false},calls=[],messages=[],work=[];let current=null,handler,count=0,stamp=Date.parse(saved.snapshot.approved_at);
 const defaultHandler=async(path,body)=>{if(path==='/api/connections/official-vision')return clone(fixture.runtime);if(path.endsWith('/media-frames'))return{project_id:saved.project_id,observations:[clone(saved.snapshot.source.source_observation.observation)]};if(path.includes('?'))return page(saved,fixture.histories.filter(v=>v.project_id===saved.project_id));
  if(path.endsWith('/process'))return clone(saved);if(path.endsWith('/cancel'))return{...clone(current??saved),status:'cancelled',result:null,result_sha256:null};if(body){current=pending(saved,body);return current;}return clone(current??saved);};handler=defaultHandler;
 const controller=initializeNativeOfficialVision({root,api:async(...args)=>{calls.push(args);return handler(...args);},getState:()=>({...state}),onMessage:(...v)=>messages.push(v),onWorking:v=>work.push(v),uuid:()=> 'explicit-ui-vision-key-'+(++count),now:()=>stamp});
 return{root,get,state,calls,messages,work,controller,defaultHandler,handler:v=>{handler=v;},time:v=>{stamp=v;},current:()=>current};}
async function ready(h){await h.controller.readConfig();await h.controller.readSources();h.get('profile').value=seed.snapshot.request.profile_id;h.get('observation').value=h.state.project.id===seed.project_id?seed.snapshot.request.observation_id:fixture.histories.find(v=>v.project_id===h.state.project.id).snapshot.request.observation_id;h.get('ceiling').value='500';h.get('duration').value='600';h.get('ack').checked=h.get('mock-ack').checked=true;h.controller.controls();}
function text(n){return[n.textContent,...n.children.map(text)].join(' ');}

test('initialization sync and controls perform no discovery dispatch or approval',()=>{const h=harness();h.controller.sync();h.controller.controls();assert.equal(h.calls.length,0);assert.equal(h.get('create').disabled,true);assert.equal(h.get('process').disabled,true);assert.equal(h.get('ack').checked,false);assert.equal(h.get('ceiling').value,'');});
test('explicit configured source consent binds finite profile mock and money; creates but never processes',async()=>{const h=harness();await ready(h);await h.controller.createIntent();const[path,b]=h.calls.at(-1);assert.equal(path,`/api/projects/${seed.project_id}/official-vision`);assert.equal(b.revision,seed.snapshot.request.revision);assert.equal(b.profile_id,seed.snapshot.request.profile_id);assert.equal(b.observation_id,seed.snapshot.request.observation_id);assert.equal(b.expected_configuration_sha256,seed.snapshot.request.expected_configuration_sha256);assert.equal(b.acknowledged_external_image_analysis,true);assert.equal(b.acknowledged_protocol_mock,true);assert.equal(b.max_operation_cost_vnd,'500');assert.equal(b.valid_for_seconds,600);assert.equal(h.controller.currentBinding().status,'approved');assert.equal(h.get('ack').checked,false);assert.equal(h.calls.filter(([p])=>p.endsWith('/process')).length,0);});
test('process is separate explicit snapshot-bound click and never invokes another operation on controls',async()=>{const h=harness();await ready(h);await h.controller.createIntent();await h.controller.processSelected();const[path,b]=h.calls.at(-1);assert.match(path,/nvoi_[a-f0-9]{32}\/process$/);assert.deepEqual(b,{expected_snapshot_sha256:seed.snapshot_sha256});assert.equal(h.controller.currentBinding().status,'succeeded');const count=h.calls.length;h.controller.controls();await h.controller.processSelected();assert.equal(h.calls.length,count);});
test('non-owner dirty active busy archived and coerced raw acknowledgement never dispatch',async()=>{const h=harness();await ready(h);const count=h.calls.length;for(const change of[{canManage:false},{dirty:true},{active:true},{busy:true},{project:{id:seed.project_id,revision:4,archived:true}}]){Object.assign(h.state,{canManage:true,dirty:false,active:false,busy:false,project:{id:seed.project_id,revision:seed.snapshot.request.revision}},change);await h.controller.createIntent();assert.equal(h.calls.length,count);}
 for(const[field,value]of[['duration',''],['duration','59'],['duration','901'],['duration','NaN'],['ceiling',''],['ceiling','NaN'],['ceiling','-1'],['ceiling','1.0000001'],['ack',1],['mock-ack',1]]){const h=harness();await ready(h);if(field==='ack'||field==='mock-ack')h.get(field).checked=value;else h.get(field).value=value;const n=h.calls.length;await h.controller.createIntent();assert.equal(h.calls.length,n);}});
test('default off discovery and disabled profile never permit analysis consent',async()=>{for(const change of[v=>v.enabled=false,v=>v.profiles[0].status='NOT_CONFIGURED']){const h=harness();h.handler(async(p,b)=>{const v=await h.defaultHandler(p,b);if(p==='/api/connections/official-vision')change(v);return v;});await ready(h);const n=h.calls.length;await h.controller.createIntent();assert.equal(h.calls.length,n);assert.equal(h.controller.currentBinding(),null);}});
test('exact request key survives unknown reply and successful reply releases it for a new manual intent',async()=>{const h=harness();await ready(h);h.handler(async()=>{throw new Error('PRIVATE provider diagnostics');});await h.controller.createIntent();const first=h.calls.at(-1)[1].request_key;h.handler(h.defaultHandler);await h.controller.createIntent();assert.equal(h.calls.at(-1)[1].request_key,first);h.controller.prepareNew();h.get('ack').checked=h.get('mock-ack').checked=true;await h.controller.createIntent();assert.notEqual(h.calls.at(-1)[1].request_key,first);assert.equal(h.messages.some(v=>v[0].includes('PRIVATE')),false);});
test('original finite consent expires without automatic renewal or second process',async()=>{const h=harness();await ready(h);await h.controller.createIntent();h.time(Date.parse(h.controller.currentBinding().snapshot.deadline));const count=h.calls.length;h.controller.controls();assert.equal(h.get('process').disabled,true);await h.controller.processSelected();assert.equal(h.calls.length,count);});
test('local cancellation is a separate snapshot-bound operation without repeat dispatch',async()=>{const h=harness();await ready(h);await h.controller.createIntent();await h.controller.cancelSelected();assert.match(h.calls.at(-1)[0],/\/cancel$/);assert.deepEqual(h.calls.at(-1)[1],{expected_snapshot_sha256:seed.snapshot_sha256});assert.equal(h.controller.currentBinding().status,'cancelled');const count=h.calls.length;await h.controller.processSelected();assert.equal(h.calls.length,count);});
test('viewer can read immutable history without configuration or credentials and keeps mock labels',async()=>{const h=harness();h.state.canManage=false;h.controller.sync();await h.controller.readHistory();assert.equal(h.calls.length,1);assert.equal(h.get('config').disabled,true);assert.equal(h.get('process').disabled,true);assert.match(text(h.get('results')),/Mô phỏng giao thức/);assert.match(text(h.get('results')),/tiền đã tính hóa đơn: chưa có/);assert.equal(h.controller.currentBinding().result.mock,true);});
test('uncertain outcome cannot auto-process or become a successful result',async()=>{const saved=fixture.histories.find(v=>v.status==='outcome_unknown'),h=harness(saved);await ready(h);h.handler(async()=>page(saved,[saved]));await h.controller.readHistory();const count=h.calls.length;assert.equal(h.get('process').disabled,true);await h.controller.processSelected();assert.equal(h.calls.length,count);assert.equal(h.controller.currentBinding().result,null);});
test('project workspace revision access dirty active or busy drift suppresses late configuration',async()=>{for(const change of[h=>h.state.project.id='f'.repeat(32),h=>h.state.workspace_id='foreign',h=>h.state.project.revision++,h=>h.state.canManage=false,h=>h.state.dirty=true,h=>h.state.active=true,h=>h.state.busy=true]){const h=harness();let release;h.handler(()=>new Promise(r=>release=r));const wait=h.controller.readConfig();change(h);h.controller.sync();release(clone(fixture.runtime));await wait;assert.equal(h.get('profile').children.length,0);assert.equal(h.messages.length,0);assert.equal(h.controller.isWorking(),false);}});
test('late create result cannot bind a different selected source or project',async()=>{const h=harness();await ready(h);let release;h.handler(()=>new Promise(r=>release=r));const wait=h.controller.createIntent(),body=h.calls.at(-1)[1];h.get('observation').value='';h.get('observation').listeners.change();release(pending(seed,body));await wait;assert.equal(h.controller.currentBinding(),null);assert.equal(h.messages.length,0);});
test('malformed page does not replace valid old history; bounded cursor is encoded',async()=>{const h=harness();h.handler(async()=>page(seed,[seed],'valid_cursor-01'));await h.controller.readHistory();h.handler(async()=>page(seed,[]));await h.controller.readHistory(true);assert.match(h.calls.at(-1)[0],/cursor=valid_cursor-01$/);for(const v of[{...page(seed,[seed]),workspace_id:'foreign'},page(seed,[seed],'x'.repeat(1001)),page(seed,[seed],'opaque+/='),{...page(seed,[seed]),automatic_dispatch:0}]){h.handler(async()=>v);await h.controller.readHistory();assert.equal(h.controller.currentBinding().vision_id,seed.vision_id);}assert.equal(h.messages.length,4);});
test('result renderer uses only bounded same-project frame URLs and plain text for captions',async()=>{const h=harness(),v=clone(seed);v.result.frames[0].caption='<img src=x onerror=PRIVATE>';h.handler(async()=>page(seed,[v]));await h.controller.readHistory();const image=h.get('results').children.flatMap(n=>n.children).find(n=>n.src);assert.match(image.src,new RegExp('^/api/projects/'+seed.project_id+'/media-frames/mfr_[a-f0-9]{24}/image$'));assert.match(text(h.get('results')),/<img src=x onerror=PRIVATE>/);assert.equal(h.get('results').innerHTML,undefined);});
test('runtime refuses reclassified mocks private data duplicate profiles and raw safety aliases',()=>{validateOfficialVisionRuntime(clone(fixture.runtime),seed.workspace_id);for(const mutate of[v=>v.enabled=1,v=>v.automatic_dispatch=0,v=>v.profiles.push(v.profiles[0]),v=>v.profiles[0].profile.key_receipt.api_key='PRIVATE',v=>v.profiles[0].mock=1,v=>v.profiles[0].workspace_id='foreign',v=>v.profiles[0].profile.key_receipt.key_returned=0]){const v=clone(fixture.runtime);mutate(v);assert.throws(()=>validateOfficialVisionRuntime(v,seed.workspace_id));}});
test('history rejects changed source costs mocks invoices crops and semantic planning claims',()=>{const state={workspace_id:seed.workspace_id,project:{id:seed.project_id}};for(const row of fixture.histories)validateOfficialVisionHistory(clone(row),{workspace_id:row.workspace_id,project:{id:row.project_id}});
 for(const mutate of[v=>v.owner_uat_accepted=0,v=>v.snapshot.request.acknowledged_external_image_analysis=1,v=>v.snapshot.input_binding.source_sha256='f'.repeat(64),v=>v.snapshot.source.source_observation.sha256='f'.repeat(64),v=>v.response.mock_transport=false,v=>v.response.input_tokens=null,v=>v.response.cached_input_tokens=121,v=>v.result.mock=false,v=>v.result.semantic_inference_performed=true,v=>v.result.observed_actual_billed_cost_vnd='0',v=>v.result.automatic_planning_eligible=0,v=>v.result.subject_tracks={length:0},v=>v.result.frames[0].evidence_frame_reference='foreign',v=>v.result.frames[0].confidence=2,v=>v.result.thumbnail_candidate_ids=['vfr_'+'f'.repeat(24)],v=>v.result.reframe_plans[0].needs_attention=false]){const v=clone(seed);mutate(v);assert.throws(()=>validateOfficialVisionHistory(v,state));}});
test('wrong selected operation or configuration reply is refused without replacing original',async()=>{const h=harness();await ready(h);await h.controller.createIntent();const original=clone(h.controller.currentBinding());h.handler(async()=>({...clone(seed),vision_id:'nvoi_'+'f'.repeat(32)}));await h.controller.readSelected();assert.deepEqual(h.controller.currentBinding(),original);assert.equal(h.messages.length,1);});
test('parent shell and signed static routing include separate card while legacy capability stays false',()=>{const native=readFileSync(new URL('../native.mjs',import.meta.url),'utf8'),html=readFileSync(new URL('../native.html',import.meta.url),'utf8'),server=readFileSync(new URL('../../../services/windows_native/server.py',import.meta.url),'utf8');assert.match(html,/id="native-official-vision-card" hidden/);assert.match(native,/native_vision_review===true&&session.access\?\.mode==='registry'/);assert.match(native,/officialVisionUI\?\.sync\(\)/);assert.match(server,/static\['\/native-official-vision.mjs'\]/);assert.match(server,/"native_official_vision":False/);});
