import test from 'node:test';import assert from 'node:assert/strict';
import {initializeNativeOfficialLearning}from'../native-official-learning.mjs';
const workspace='wsp_official_learning_fixture',project='a'.repeat(32),pub='nopu_'+'b'.repeat(32),aid='nowa_'+'c'.repeat(32),rid='noam_'+'d'.repeat(32),ash='e'.repeat(64),
  winnerPolicy='f'.repeat(64),basis='1'.repeat(64),candidateSha='2'.repeat(64),learningId='nols_'+'3'.repeat(32),keys=['trend_family','hook','duration','visual_strategy','subtitle_style','voice_profile','publishing_window'];
const query=()=>({start_date:'2026-10-01',end_date:'2026-10-02',include_revenue:false});
const scope=()=>({workspace_id:workspace,target_binding_sha256:'4'.repeat(64),platform:'youtube',provider_key:'youtube-analytics-api',mock:true,source_kind:'official_protocol_mock',source_external_call:false,
  query:query(),niche:'technology',format:{width:1080,height:1920,video_codec:'h264'},winner_algorithm_version:'winner-channel-assessment-v1'});
const assessment=()=>({assessment_id:aid,snapshot_sha256:ash,publication_id:pub,result_snapshot_id:rid,mock:true,assessment:{algorithm_version:'winner-channel-assessment-v1'},snapshot:{policy_sha256:winnerPolicy,candidate:{scope:{...scope(),duration_bucket:'0-30'}}}});
const source=()=>({schema_version:'native-official-learning-source-binding-v1',workspace_id:workspace,project_id:project,assessment_id:aid,assessment_sha256:ash,publication_id:pub,result_snapshot_id:rid,candidate_sha256:candidateSha,
  scope:scope(),winner_policy_sha256:winnerPolicy,winner_factor_basis_sha256:basis,qualified_scope:true,mock:true,real_audience_observation:false,recommendation_only:true,automatic_action:false,publishing_enabled:false,token_returned:false});
const policy=()=>({schema_version:'channel-learning-policy-v1',minimum_group_posts:3,minimum_control_posts:3,maximum_posts:100,minimum_score_difference:10});
const config=()=>({schema_version:'native-official-learning-capabilities-v1',workspace_id:workspace,default_policy:policy(),dimensions:keys,maximum_candidate_rows:500,automatic_learning:false,provider_calls_enabled:false,recommendation_only:true,automatic_action:false,publishing_enabled:false,token_returned:false});
const request=()=>({schema_version:'native-official-learning-request-v1',assessment_id:aid,expected_assessment_sha256:ash,policy:policy(),acknowledged_recommendation_only:true,acknowledged_protocol_mock:true});
function row(body=request()){
  const{request_key,...bounded}=body;const dims=keys.map(dimension=>({dimension,state:'insufficient_data',missing_feature_posts:0,groups:[],groups_truncated:false}));
  return{schema_version:'native-official-learning-history-v1',learning_id:learningId,workspace_id:workspace,project_id:project,publication_id:pub,anchor_assessment_id:aid,anchor_result_snapshot_id:rid,snapshot_sha256:'5'.repeat(64),
    observation_count:0,status:'insufficient_data',mock:true,real_audience_observation:false,recommendation_only:true,automatic_action:false,external_call:false,publishing_enabled:false,token_returned:false,dimensions:dims,
    snapshot:{schema_version:'native-official-learning-snapshot-v1',workspace_id:workspace,project_id:project,publication_id:pub,anchor_assessment_id:aid,anchor_result_snapshot_id:rid,anchor_candidate_sha256:candidateSha,
      request:bounded,scope:scope(),winner_policy_sha256:winnerPolicy,winner_factor_basis_sha256:basis,recommendation_only:true,automatic_action:false,publishing_enabled:false,candidate_rows_truncated:false,selected_posts_truncated:false,
      observations:[],selected_assessments:[],dimensions:structuredClone(dims)}};
}
function positive(){const v=row();const observations=Array.from({length:6},(_,i)=>({snapshot_id:'noam_'+String(i+1).repeat(32),publication_id:'nopu_'+String(i+1).repeat(32),assessment_id:'nowa_'+String(i+1).repeat(32),
  remote_post_sha256:String(i+1).repeat(64),feature_context_sha256:'6'.repeat(64),score:i<3?90:50,winner_policy_sha256:winnerPolicy,assessment_basis_sha256:basis,
  features:{...Object.fromEntries(keys.map(k=>[k,null])),hook:i<3?'question':'list'}}));
  v.status='recommendations_available';v.observation_count=6;v.snapshot.observations=observations;v.snapshot.selected_assessments=observations.map(o=>({project_id:project,assessment_id:o.assessment_id,snapshot_sha256:'7'.repeat(64),candidate_sha256:'8'.repeat(64),observation:structuredClone(o)}));
  v.dimensions=keys.map(dimension=>({dimension,state:dimension==='hook'?'recommendations_available':'insufficient_data',missing_feature_posts:dimension==='hook'?0:6,groups_truncated:false,
    groups:dimension==='hook'?[{value:'question',state:'recommendation_candidate',sample_count:3,control_count:3,median_assessment_score:90,control_median_score:50,score_difference:40,
      snapshot_ids:observations.slice(0,3).map(o=>o.snapshot_id),control_snapshot_ids:observations.slice(3).map(o=>o.snapshot_id),recommendation:'Reviewed experiment only'}]:[]}));v.snapshot.dimensions=structuredClone(v.dimensions);return v;
}
const page=(items,cursor=null)=>({schema_version:'native-official-learning-page-v1',workspace_id:workspace,project_id:project,publication_id:pub,items,next_cursor:cursor,recommendation_only:true,automatic_action:false,external_call:false,publishing_enabled:false,token_returned:false});
function harness(){const nodes=new Map();class Node{constructor(){this.children=[];this.value='';this.checked=false;this.dataset={};this.listeners={};}set id(v){this._id=v;nodes.set(v,this);}get id(){return this._id;}
  append(...v){this.children.push(...v);}replaceChildren(...v){this.children=[...v];}addEventListener(k,v){this.listeners[k]=v;}}
  const root={createElement:()=>new Node(),getElementById(v){if(!nodes.has(v))nodes.set(v,new Node());return nodes.get(v);}},get=id=>root.getElementById('native-official-learning-'+id),
    state={workspace_id:workspace,project:{id:project,revision:1},canManage:true,dirty:false,busy:false,active:false},calls=[],messages=[],selections=[];let binding={assessment:assessment()},current=row(),handler,count=0;
  const defaultHandler=async(path,body)=>{if(path.includes('/connections/'))return config();if(path.includes('/source/'))return source();if(body){current=row(body);return current;}if(path.includes('?'))return page([current]);return current;};handler=defaultHandler;
  const controller=initializeNativeOfficialLearning({api:async(...args)=>{calls.push(args);return handler(...args);},root,getState:()=>({...state}),getBinding:()=>binding,onMessage:(...v)=>messages.push(v),onWorking:v=>{state.busy=v;},onSelection:()=>selections.push(true),uuid:()=> 'explicit-learning-key-'+(++count)});
  return{controller,state,calls,get,messages,selections,defaultHandler,handler:v=>{handler=v;},binding:v=>{binding=v;},current:v=>{current=v;}};
}
function ack(h){h.get('ack').checked=h.get('mock-ack').checked=true;}
async function ready(h){await h.controller.readSource();await h.controller.readConfig();ack(h);h.controller.controls();}

test('initialization is inert and selected assessment plus qualified source are required',async()=>{const h=harness();assert.equal(h.calls.length,0);assert.equal(h.get('create').disabled,true);h.binding({assessment:null});h.controller.sync();await h.controller.readSource();assert.equal(h.calls.length,0);
  h.binding({assessment:assessment()});h.handler(async()=>({...source(),qualified_scope:false}));await h.controller.readSource();h.handler(h.defaultHandler);await h.controller.readConfig();ack(h);h.controller.controls();assert.equal(h.get('create').disabled,true);});
test('explicit learning freezes selected server hash policy and acknowledgements without polling',async()=>{const h=harness();await ready(h);assert.equal(h.get('create').disabled,false);await h.controller.createLearning();
  assert.deepEqual(h.calls.at(-1),[`/api/projects/${project}/official-learning`,{...request(),request_key:'native-official-learning-explicit-learning-key-1'}]);assert.equal(h.calls.length,3);assert.equal(h.get('ack').checked,false);assert.equal(h.get('recommendations').children.length,7);assert.match(h.get('status').textContent,/Chưa đủ dữ liệu/);});
test('uncertain request key survives preparation with old selected history and known replay may start new key',async()=>{const h=harness();await ready(h);await h.controller.readHistory();let count=0;
  h.handler(async(path,body)=>{if(body&&!count++)throw new Error('Explicit uncertain reply');return h.defaultHandler(path,body);});await h.controller.createLearning();const key=h.calls.at(-1)[1].request_key;h.controller.prepareNew();ack(h);await h.controller.createLearning();assert.equal(h.calls.at(-1)[1].request_key,key);
  h.controller.prepareNew();ack(h);await h.controller.createLearning();assert.notEqual(h.calls.at(-1)[1].request_key,key);});
test('source or configuration foreign mock relabel automatic action and digest drift are refused',async()=>{for(const mutate of[v=>({...v,workspace_id:'wsp_foreign'}),v=>({...v,mock:1}),v=>({...v,real_audience_observation:true}),v=>({...v,assessment_sha256:'9'.repeat(64)}),v=>({...v,scope:{...scope(),niche:'property'}})]){
  const h=harness();h.handler(async()=>mutate(source()));await h.controller.readSource();assert.equal(h.get('create').disabled,true);assert.equal(h.messages.length,1);}
  const h=harness();await h.controller.readSource();h.handler(async()=>({...config(),automatic_learning:true}));await h.controller.readConfig();assert.equal(h.get('minimum-group-posts').value,'');});
test('policy sample bounds blanks nonfinite difference insufficient total and missing mock acknowledgement never save',async()=>{const h=harness();await ready(h);h.get('mock-ack').checked=false;const count=h.calls.length;await h.controller.createLearning();assert.equal(h.calls.length,count);ack(h);
  for(const[field,value]of[['minimum-group-posts','2'],['minimum-control-posts','3.5'],['maximum-posts','5'],['maximum-posts','101'],['minimum-score-difference','Infinity'],['minimum-score-difference',''],['minimum-group-posts','50']]){
    await h.controller.readConfig();h.get(field).value=value;if(field==='minimum-group-posts'&&value==='50')h.get('maximum-posts').value='6';const before=h.calls.length;await h.controller.createLearning();assert.equal(h.calls.length,before);}});
test('viewer may review immutable history while manage and busy operations are refused',async()=>{const h=harness();h.state.canManage=false;h.controller.sync();await h.controller.readSource();await h.controller.readHistory();assert.equal(h.get('recommendations').children.length,7);
  const count=h.calls.length;await h.controller.readConfig();await h.controller.createLearning();h.controller.prepareNew();assert.equal(h.calls.length,count);h.state.busy=true;await h.controller.readStored();assert.equal(h.calls.length,count);});
test('late responses cannot cross workspace project role or selected assessment',async()=>{for(const change of[h=>h.state.workspace_id='wsp_foreign',h=>h.state.project.id='9'.repeat(32),h=>h.state.canManage=false,h=>h.binding({assessment:{...assessment(),assessment_id:'nowa_'+'8'.repeat(32)}})]){
  const h=harness();let release;h.handler(()=>new Promise(resolve=>{release=resolve;}));const pending=h.controller.readSource();change(h);h.controller.sync();release(source());await pending;assert.equal(h.get('detail').textContent,'');assert.equal(h.messages.length,0);assert.equal(h.state.busy,false);}});
test('qualified mock association displays group control medians missing features and descriptive qualifier',async()=>{const h=harness();await h.controller.readSource();h.current(positive());await h.controller.readHistory();assert.equal(h.messages.length,0);assert.equal(h.get('recommendations').children.length,7);
  assert.match(h.get('recommendations').children[1].children[2].textContent,/Nhóm: 3 · Đối chiếu: 3/);assert.match(h.get('recommendations').children[1].children[2].textContent,/90 \/ 50 · Chênh lệch: 40/);assert.match(h.get('status').textContent,/chưa có phản hồi khán giả thật/);assert.match(h.get('status').textContent,/liên hệ mô tả/);});
test('foreign counts source relabel fabricated sparse recommendation duplicate posts or numeric strings are rejected',async()=>{for(const mutate of[v=>({...v,project_id:'8'.repeat(32)}),v=>({...v,observation_count:'0'}),v=>({...v,real_audience_observation:true}),v=>({...v,automatic_action:true})]){
  const h=harness();await h.controller.readSource();h.handler(async()=>page([mutate(row())]));await h.controller.readHistory();assert.equal(h.get('recommendations').children.length,0);assert.equal(h.messages.length,1);}
  for(const mutate of[v=>{v.snapshot.observations[1].remote_post_sha256=v.snapshot.observations[0].remote_post_sha256;},v=>{v.dimensions[1].groups[0].sample_count=2;v.snapshot.dimensions=structuredClone(v.dimensions);},v=>{v.snapshot.selected_assessments[0].snapshot_sha256='wrong';}]){
    const h=harness();await h.controller.readSource();const value=positive();mutate(value);h.handler(async()=>page([value]));await h.controller.readHistory();assert.equal(h.get('recommendations').children.length,0);assert.equal(h.messages.length,1);}});
test('historical report interval and winner policy remain readable with original anchor evidence',async()=>{const h=harness();await h.controller.readSource();const v=row(),old='nowa_'+'9'.repeat(32);v.anchor_assessment_id=v.snapshot.anchor_assessment_id=v.snapshot.request.assessment_id=old;
  v.snapshot.scope.query={...query(),start_date:'2026-09-01'};v.snapshot.winner_policy_sha256='8'.repeat(64);v.snapshot.winner_factor_basis_sha256='7'.repeat(64);h.current(v);await h.controller.readHistory();assert.equal(h.messages.length,0);assert.match(h.get('detail').textContent,/2026-09-01/);});
test('save reply must match exact submitted request and failed reply retains request key',async()=>{const h=harness();await ready(h);h.handler(async()=>row({...request(),policy:{...policy(),minimum_score_difference:20}}));await h.controller.createLearning();const key=h.calls.at(-1)[1].request_key;
  assert.equal(h.get('detail').textContent,'');assert.match(h.messages.at(-1)[0],/không đúng yêu cầu/);h.controller.prepareNew();ack(h);h.handler(h.defaultHandler);await h.controller.createLearning();assert.equal(h.calls.at(-1)[1].request_key,key);});
test('bounded cursor pages and archived current project preserve original readable history',async()=>{const h=harness();await h.controller.readSource();h.handler(async()=>page([row()],'opaque+/='));await h.controller.readHistory();h.handler(async()=>page([]));await h.controller.readHistory(true);assert.match(h.calls.at(-1)[0],/&cursor=opaque%2B%2F%3D$/);
  h.handler(async()=>page([],'x'.repeat(2049)));await h.controller.readHistory();assert.equal(h.messages.length,1);h.state.project.revision=2;h.state.project.archived=true;h.state.dirty=true;h.state.active=true;h.controller.sync();h.handler(h.defaultHandler);await h.controller.readSource();await h.controller.readHistory();await h.controller.readStored();assert.equal(h.get('recommendations').children.length,7);});
test('qualified downstream binding exposes only selected verified learning and notifies source reset',async()=>{const h=harness();assert.deepEqual(h.controller.currentBinding(),{learning:null});const initial=h.selections.length;await h.controller.readSource();await h.controller.readHistory();assert.deepEqual(h.controller.currentBinding(),{learning:row()});assert.ok(h.selections.length>initial);const count=h.selections.length;h.controller.prepareNew();assert.deepEqual(h.controller.currentBinding(),{learning:null});assert.equal(h.selections.length,count+1);});
test('changed project invalidates downstream selected learning and callback without network',async()=>{const h=harness();await h.controller.readSource();await h.controller.readHistory();const count=h.selections.length,before=h.calls.length;h.state.project.revision++;h.controller.sync();assert.deepEqual(h.controller.currentBinding(),{learning:null});assert.equal(h.selections.length,count+1);assert.equal(h.calls.length,before);});
