import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';
import{initializeNativeRenderThumbnail,validateRenderThumbnail,renderThumbnailImageUrl}from'../native-render-thumbnail.mjs';
const fixture=JSON.parse(readFileSync(new URL('./fixtures/native-render-thumbnail-v1.json',import.meta.url)));assert.equal(fixture.fixture_kind,'explicit_owned_cpu_render_thumbnail_original_mock_vision_not_owner_or_provider_acceptance');
const clone=v=>structuredClone(v),seed=fixture.selections[0],page=(items,cursor=null)=>({schema_version:'native-render-thumbnail-page-v1',workspace_id:seed.workspace_id,project_id:seed.project_id,items,limit:25,next_cursor:cursor,publishing_authorized:false,owner_uat_accepted:false});
function harness(){const nodes=new Map();class Node{constructor(tag='details'){this.tagName=tag.toUpperCase();this.children=[];this.value='';this.checked=false;this.dataset={};this.listeners={};this.style={};this.textContent='';}set id(v){this._id=v;nodes.set(v,this);}get id(){return this._id;}append(...v){this.children.push(...v);}replaceChildren(...v){this.children=[...v];}addEventListener(k,v){this.listeners[k]=v;}}
 const root={createElement:tag=>new Node(tag),getElementById(v){if(!nodes.has(v))nodes.set(v,new Node());return nodes.get(v);}},get=id=>root.getElementById('native-render-thumbnail-'+id),state={workspace_id:seed.workspace_id,project:clone(fixture.project),canEdit:true,dirty:false,busy:false,active:false},calls=[],messages=[],work=[];let handler,review=clone(fixture.reviewed_vision),count=0;
 const defaultHandler=async(p,b)=>{if(p.includes('/render-vision/input/'))return clone(fixture.input);if(p.includes('?'))return page(clone(fixture.selections));if(b){const row=clone(fixture.selections.find(r=>r.snapshot.request.frame_id===b.frame_id&&(r.snapshot.reviewed_vision!==null)===(b.reviewed_vision!==null)));assert.ok(row);assert.deepEqual(row.snapshot.request,Object.fromEntries(Object.entries(b).filter(([k])=>k!=='request_key')));return{...row,idempotent_replay:false};}throw new Error('Unexpected route');};handler=defaultHandler;
 const controller=initializeNativeRenderThumbnail({root,api:async(...v)=>{calls.push(v);return handler(...v);},getState:()=>({...state}),getReviewedVision:()=>review,onMessage:(...v)=>messages.push(v),onWorking:v=>work.push(v),uuid:()=> 'explicit-thumbnail-test-key-'+(++count)});
 return{root,get,state,calls,messages,work,controller,defaultHandler,handler:v=>{handler=v;},review:v=>{review=v;}};
}
async function ready(h){h.get('video').value=fixture.input.render_job_id;await h.controller.readInput();h.get('frame').value=seed.snapshot.frame.frame_id;h.get('frame').listeners.change();h.get('ack').checked=true;h.controller.controls();}
function text(n){return[n.textContent,...n.children.map(text)].join(' ');}

test('mount refresh and controls do not read select render process or publish automatically',()=>{const h=harness();h.controller.sync();h.controller.controls();assert.equal(h.calls.length,0);assert.equal(h.get('save').disabled,true);assert.equal(h.get('ack').checked,false);assert.equal(h.get('vision').checked,false);assert.equal(h.get('video').children.length,2);assert.equal(h.controller.currentSelection(),null);});
test('parent project-loading guard settles before user selection so the first input read is retained',async()=>{const h=harness();h.state.busy=true;h.controller.sync();h.state.busy=false;h.controller.controls();h.get('video').value=fixture.input.render_job_id;h.get('video').listeners.change();await h.controller.readInput();assert.equal(h.calls.length,1);assert.equal(h.get('video').value,fixture.input.render_job_id);assert.equal(h.get('frames').children.length,8);assert.equal(h.messages.length,0);assert.equal(h.get('ack').checked,false);});
test('all original retained thumbnail rows and exact scoped original PNG routes validate',()=>{const s={workspace_id:seed.workspace_id,project:fixture.project};for(const v of fixture.selections)assert.equal(validateRenderThumbnail(v,s),v);assert.equal(renderThumbnailImageUrl(seed.project_id,seed.thumbnail_asset_id),`/api/projects/${seed.project_id}/render-thumbnails/${seed.thumbnail_asset_id}/image`);for(const args of[['bad',seed.thumbnail_asset_id],[seed.project_id,'ast_other'],[seed.project_id,seed.thumbnail_asset_id+'/../private']])assert.throws(()=>renderThumbnailImageUrl(...args));});
test('manual choice uses exact original render input frame and its own raw acknowledgement',async()=>{const h=harness();await ready(h);await h.controller.create();const[p,b]=h.calls.at(-1);assert.equal(p,`/api/projects/${seed.project_id}/render-thumbnails`);assert.deepEqual(Object.fromEntries(Object.entries(b).filter(([k])=>k!=='request_key')),seed.snapshot.request);assert.equal(b.acknowledged_thumbnail,true);assert.equal(b.reviewed_vision,null);assert.equal(h.controller.currentSelection().snapshot.image.rights_status,'unknown');assert.equal(h.controller.currentSelection().publishing_authorized,false);assert.equal(h.controller.currentSelection().snapshot.final_video_approved,false);assert.equal(h.get('ack').checked,false);assert.match(h.get('status').textContent,/chưa cho phép xuất bản/);assert.ok(!h.calls.some(([p])=>p.endsWith('/process')||p.endsWith('/jobs')||p.includes('publication')));});
test('rendered Vision is optional with a separate mock acknowledgement and original binding',async()=>{const h=harness();await ready(h);h.get('vision').checked=true;const n=h.calls.length;await h.controller.create();assert.equal(h.calls.length,n);h.get('mock').checked=true;await h.controller.create();const b=h.calls.at(-1)[1];assert.deepEqual(b.reviewed_vision,fixture.selections[2].snapshot.request.reviewed_vision);assert.equal(h.controller.currentSelection().snapshot.reviewed_vision.semantic_inference_performed,false);assert.equal(h.get('vision').checked,false);assert.equal(h.get('mock').checked,false);assert.equal(h.calls.filter(([p])=>p.endsWith('/process')).length,0);});
test('wrong Source consent purpose foreign and incomplete Vision cannot select a thumbnail',async()=>{for(const mutate of[v=>v.vision_id='nvoi_'+'a'.repeat(32),v=>v.snapshot.configuration.profile.purpose='asset_analysis',v=>v.project_id='f'.repeat(32),v=>v.workspace_id='foreign',v=>v.result.render_input_sha256='a'.repeat(64),v=>v.status='outcome_unknown',v=>v.result.mock=1,v=>v.result.publishing_authorized=true]){const h=harness();await ready(h);const v=clone(fixture.reviewed_vision);mutate(v);h.review(v);h.get('vision').checked=h.get('mock').checked=true;const n=h.calls.length;await h.controller.create();assert.equal(h.calls.length,n);assert.equal(h.controller.currentSelection(),null);}});
test('viewer can read original history and frame evidence but cannot record a choice',async()=>{const h=harness();h.state.canEdit=false;h.controller.sync();h.get('video').value=fixture.input.render_job_id;await h.controller.readInput();await h.controller.readHistory();assert.equal(h.get('save').disabled,true);assert.equal(h.get('ack').disabled,true);assert.equal(h.get('frame').disabled,true);assert.equal(h.get('history').disabled,false);const n=h.calls.length;h.get('ack').checked=true;h.get('frame').value=seed.snapshot.frame.frame_id;await h.controller.create();assert.equal(h.calls.length,n);assert.equal(h.controller.currentSelection().snapshot.image.rights_status,'unknown');});
test('dirty busy active archived stale version and non-editor states prevent selection',async()=>{for(const change of[{canEdit:false},{dirty:true},{busy:true},{active:true},{project:{...fixture.project,archived:true}},{project:{...fixture.project,revision:fixture.project.revision+1}}]){const h=harness();await ready(h);Object.assign(h.state,change);const n=h.calls.length;await h.controller.create();assert.equal(h.calls.length,n);assert.equal(h.controller.currentSelection(),null);}});
test('raw acknowledgement black frames absent choice and mismatched input prevent selection',async()=>{for(const mutate of[h=>h.get('ack').checked=1,h=>h.get('ack').checked='true',h=>h.get('frame').value='',h=>h.get('video').value='f'.repeat(32)]){const h=harness();await ready(h);mutate(h);const n=h.calls.length;await h.controller.create();assert.equal(h.calls.length,n);}
 const h=harness();h.handler(async(p,b)=>{const v=await h.defaultHandler(p,b);if(p.includes('/input/'))v.binding.record.observation.frames[0].pixel_facts.black_sample=true;return v;});await ready(h);const n=h.calls.length;await h.controller.create();assert.equal(h.calls.length,n);assert.equal(h.get('frame').children.some(v=>v.value===seed.snapshot.frame.frame_id),false);
});
test('changing frame and video clears every saved selection acknowledgement',async()=>{const h=harness();await ready(h);h.get('vision').checked=h.get('mock').checked=true;h.get('frame').listeners.change();assert.equal(h.get('ack').checked,false);assert.equal(h.get('vision').checked,false);assert.equal(h.get('mock').checked,false);h.get('ack').checked=true;h.get('video').listeners.change();assert.equal(h.get('frames').children.length,0);assert.equal(h.get('ack').checked,false);assert.equal(h.get('save').disabled,true);});
test('unknown create reply retains the same request key and success releases it',async()=>{const h=harness();await ready(h);h.handler(async()=>{throw new Error('PRIVATE credentials from transport');});await h.controller.create();const key=h.calls.at(-1)[1].request_key;h.handler(h.defaultHandler);await h.controller.create();assert.equal(h.calls.at(-1)[1].request_key,key);h.get('ack').checked=true;await h.controller.create();assert.notEqual(h.calls.at(-1)[1].request_key,key);assert.ok(!h.messages.some(v=>v[0].includes('PRIVATE')));});
test('idempotent replay response remains an unapproved image choice',async()=>{const h=harness();await ready(h);h.handler(async(p,b)=>({...await h.defaultHandler(p,b),idempotent_replay:true}));await h.controller.create();assert.equal(h.controller.currentSelection().idempotent_replay,true);assert.equal(h.controller.currentSelection().owner_uat_accepted,false);assert.equal(h.controller.currentSelection().snapshot.rights_independently_verified,false);});
test('scope drift discards late frame input and does not show private errors',async()=>{for(const change of[h=>h.state.project.id='f'.repeat(32),h=>h.state.workspace_id='foreign',h=>h.state.project.revision++,h=>h.state.canEdit=false,h=>h.state.dirty=true,h=>h.state.busy=true,h=>h.state.active=true]){const h=harness();h.get('video').value=fixture.input.render_job_id;let release;h.handler(()=>new Promise(r=>release=r));const wait=h.controller.readInput();change(h);h.controller.sync();release(clone(fixture.input));await wait;assert.equal(h.get('frames').children.length,0);assert.equal(h.messages.length,0);assert.equal(h.controller.isWorking(),false);}});
test('changed selected video discards late evidence',async()=>{const h=harness();h.get('video').value=fixture.input.render_job_id;let release;h.handler(()=>new Promise(r=>release=r));const wait=h.controller.readInput();h.get('video').value='f'.repeat(32);h.get('video').listeners.change();release(clone(fixture.input));await wait;assert.equal(h.get('frames').children.length,0);assert.equal(h.controller.currentSelection(),null);});
test('late create result cannot replace current frame or project choice',async()=>{for(const change of[h=>h.get('frame').listeners.change(),h=>{h.state.project.revision++;h.controller.sync();}]){const h=harness();await ready(h);let release;h.handler(()=>new Promise(r=>release=r));const wait=h.controller.create();change(h);release({...clone(seed),idempotent_replay:false});await wait;assert.equal(h.controller.currentSelection(),null);assert.equal(h.messages.length,0);}});
test('history pagination is bounded encoded and keeps original rows without automatic image generation',async()=>{const h=harness();h.handler(async()=>page([seed],'exact_cursor-01'));await h.controller.readHistory();h.handler(async()=>page([fixture.selections[1]]));await h.controller.readHistory(true);assert.match(h.calls.at(-1)[0],/limit=25&cursor=exact_cursor-01$/);assert.equal(h.get('list').children.length,2);h.get('list').children[1].listeners.click();assert.equal(h.controller.currentSelection().thumbnail_asset_id,fixture.selections[1].thumbnail_asset_id);assert.equal(h.calls.length,2);});
test('malformed pages and publication or UAT claims preserve old valid history',async()=>{const h=harness();h.handler(async()=>page([seed]));await h.controller.readHistory();for(const v of[{...page([seed]),workspace_id:'foreign'},page([seed],'x'.repeat(1001)),page([seed],'opaque+/='),{...page([seed]),publishing_authorized:0},{...page([seed]),limit:100},{...page([seed]),owner_uat_accepted:true},page(Array(26).fill(seed))]){h.handler(async()=>v);await h.controller.readHistory();assert.equal(h.controller.currentSelection().thumbnail_asset_id,seed.thumbnail_asset_id);}assert.equal(h.messages.length,7);});
test('historical original thumbnail remains readable after a project edit',async()=>{const h=harness();h.state.project.revision++;h.controller.sync();h.handler(async()=>page([seed]));await h.controller.readHistory();assert.equal(h.controller.currentSelection().snapshot.request.revision,fixture.project.revision);assert.equal(h.get('selected').children[0].children[0].src,renderThumbnailImageUrl(seed.project_id,seed.thumbnail_asset_id));assert.equal(h.get('save').disabled,true);});
test('loaded image nodes survive acknowledgement and identical history reads but clear on scope change',async()=>{const h=harness();await ready(h);const image=h.get('frames').children[0].children[0];h.get('ack').listeners.change();assert.equal(h.get('frames').children[0].children[0],image);h.handler(async()=>page([seed]));await h.controller.readHistory();const selected=h.get('selected').children[0].children[0];await h.controller.readHistory();assert.equal(h.get('selected').children[0].children[0],selected);h.state.project.revision++;h.controller.sync();assert.equal(h.get('frames').children.length,0);assert.equal(h.get('selected').children.length,0);});
test('thumbnail validator rejects raw authority fabricated rights lost provenance and malformed dates',()=>{const state={workspace_id:seed.workspace_id,project:fixture.project};for(const mutate of[v=>v.publishing_authorized=0,v=>v.snapshot.owner_uat_accepted=true,v=>v.snapshot.provider_authorized=true,v=>v.snapshot.source_asset_consent_reused=true,v=>v.snapshot.external_provider_calls=false,v=>v.snapshot.image.rights_status='owned',v=>v.snapshot.image.license='invented',v=>v.snapshot.image.sha256='a'.repeat(64),v=>v.snapshot.frame.pixel_facts.black_sample=true,v=>v.snapshot.request.acknowledged_thumbnail=1,v=>v.snapshot.request.revision=true,v=>v.created_at=v.snapshot.created_at=0,v=>v.created_at=v.snapshot.created_at='2026-02-31T00:00:00Z',v=>v.snapshot.api_key='PRIVATE',v=>v.snapshot.image.data_url='data:PRIVATE',v=>v.workspace_id='foreign',v=>v.project_id='f'.repeat(32)]){const v=clone(seed);mutate(v);assert.throws(()=>validateRenderThumbnail(v,state));}});
test('optional Vision provenance cannot acquire semantics or publishing authority from a mock',()=>{const state={workspace_id:seed.workspace_id,project:fixture.project};for(const mutate of[v=>v.snapshot.reviewed_vision.semantic_inference_performed=true,v=>v.snapshot.reviewed_vision.confidence_calibrated=true,v=>v.snapshot.reviewed_vision.publishing_authorized=true,v=>v.snapshot.reviewed_vision.source_asset_consent_reused=true,v=>v.snapshot.reviewed_vision.snapshot_sha256='a'.repeat(64),v=>v.snapshot.request.reviewed_vision.acknowledged_protocol_mock=1]){const v=clone(fixture.selections[2]);mutate(v);assert.throws(()=>validateRenderThumbnail(v,state));}});
test('shell mounts the thumbnail beside portrait review and keeps separate real-provider gates',()=>{const native=readFileSync(new URL('../native.mjs',import.meta.url),'utf8'),html=readFileSync(new URL('../native.html',import.meta.url),'utf8'),shot=readFileSync(new URL('../shot-studio.mjs',import.meta.url),'utf8'),server=readFileSync(new URL('../../../services/windows_native/server.py',import.meta.url),'utf8');assert.match(html,/id="native-render-thumbnail-card" hidden/);assert.match(native,/native_render_thumbnail_review===true/);assert.match(native,/renderThumbnailUI\?\.sync\(\)/);assert.match(native,/renderThumbnailUI\?\.isWorking/);assert.match(native,/getReviewedVision:\(\)=>renderVisionUI\?\.currentBinding\(\)/);assert.match(shot,/move\('#native-render-thumbnail-card','video-review-body'\)/);assert.match(shot,/append\(thumbnail\)/);assert.match(server,/static\['\/native-render-thumbnail.mjs'\]/);assert.match(server,/"native_official_vision":False/);assert.match(native,/canEdit:session.access\?\.mode!=='registry'\|\|session.access.permissions\?\.includes\('edit'\)===true/);});
