// Isolated DOM prototype over explicitly labelled public protocol mocks.
import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';
import{initializeNativeGoogleOAuth,validateGoogleOAuthRuntime,validateGoogleOAuthHistory,validateGoogleAuthorizationURL}from'../native-google-oauth.mjs';
const fixture=JSON.parse(readFileSync(new URL('./fixtures/native-google-oauth-v1.json',import.meta.url)));assert.equal(fixture.fixture_kind,'explicit_nonplayable_protocol_mock_not_provider_or_owner_acceptance');
const seed=fixture.authorizations.find(v=>v.snapshot.slot.client.purpose==='analytics'),original=fixture.operations.find(v=>v.status==='succeeded'&&v.snapshot.operation==='authorization_code'),stamp=Date.parse(seed.snapshot.approved_at),origin=new URL(seed.snapshot.request.redirect_uri).origin;
function pending(body){const v=structuredClone(seed);v.status='awaiting_callback';v.operation_id=null;v.snapshot.request={...body};delete v.snapshot.request.request_key;v.idempotent_replay=false;return v;}
function page(kind,items,cursor=null){return{schema_version:'native-google-oauth-page-v1',workspace_id:seed.workspace_id,project_id:seed.project_id,kind,items,truncated:cursor!==null,next_cursor:cursor,token_returned:false,publishing_enabled:false,automatic_refresh:false};}
function url(auth){const p=new URLSearchParams({client_id:auth.snapshot.slot.client_id,redirect_uri:auth.snapshot.request.redirect_uri,response_type:'code',scope:auth.snapshot.slot.scopes.join(' '),code_challenge:'x'.repeat(43),code_challenge_method:'S256',state:auth.authorization_id+'.'+'x'.repeat(64),prompt:'consent'});
  return{schema_version:'native-google-oauth-authorization-url-v1',authorization_id:auth.authorization_id,authorization_url:'https://accounts.google.com/o/oauth2/v2/auth?'+p,external_human_browser_required:true,token_returned:false,publishing_enabled:false};}
function harness(){const nodes=new Map();class Node{constructor(){this.children=[];this.value='';this.checked=false;this.dataset={};this.listeners={};this.textContent='';}set id(v){this._id=v;nodes.set(v,this);}get id(){return this._id;}append(...v){this.children.push(...v);}replaceChildren(...v){this.children=[...v];}addEventListener(k,v){this.listeners[k]=v;}removeAttribute(name){delete this[name];}}
 const root={createElement:()=>new Node(),getElementById(v){if(!nodes.has(v))nodes.set(v,new Node());return nodes.get(v);}},get=id=>root.getElementById('native-google-oauth-'+id),state={workspace_id:seed.workspace_id,project:{id:seed.project_id,revision:1},canManage:true,dirty:false,busy:false,active:false},calls=[],messages=[];let current=null,handler,count=0,time=stamp;
 const defaultHandler=async(path,body)=>{if(path==='/api/connections/google-oauth')return structuredClone(fixture.runtime);if(path.endsWith('/authorization-url'))return url(current);if(path.endsWith('/cancel'))return{...current,status:'cancelled'};
  if(path.endsWith('/refresh')){const v=structuredClone(fixture.operations.find(v=>v.snapshot.operation==='refresh_token'));v.snapshot.request={...body};delete v.snapshot.request.request_key;v.snapshot.source_result_sha256=body.expected_result_sha256;return v;}
  if(body){current=pending(body);return current;}if(path.includes('/authorizations?'))return page('authorization',fixture.authorizations);if(path.includes('/operations?'))return page('operation',[original]);return current;};handler=defaultHandler;
 const controller=initializeNativeGoogleOAuth({root,api:async(...args)=>{calls.push(args);return handler(...args);},getState:()=>({...state}),onMessage:(...v)=>messages.push(v),uuid:()=> 'explicit-ui-connection-key-'+(++count),now:()=>time,origin:()=>origin});
 return{root,get,state,calls,messages,controller,defaultHandler,handler:v=>{handler=v;},time:v=>{time=v;},current:()=>current};}
async function ready(h){await h.controller.readConfig();h.get('slot').value=seed.snapshot.slot.slot_id;h.get('ack').checked=h.get('mock-ack').checked=true;h.controller.controls();}
test('initialization sync controls and default disabled discovery are inert',async()=>{const h=harness();h.controller.sync();h.controller.controls();assert.equal(h.calls.length,0);assert.equal(h.get('create').disabled,true);assert.equal(h.get('external-link').hidden,true);
 h.handler(async()=>({...fixture.runtime,enabled:false}));await ready(h);const count=h.calls.length;await h.controller.createAuthorization();assert.equal(h.calls.length,count);assert.equal(h.controller.currentBinding().authorization,null);});
test('explicit start binds project dedicated purpose configuration mock and finite consent',async()=>{const h=harness();await ready(h);await h.controller.createAuthorization();const[path,b]=h.calls.at(-1);
 assert.equal(path,`/api/projects/${seed.project_id}/google-oauth/authorizations`);assert.equal(b.revision,1);assert.equal(b.slot_id,seed.snapshot.slot.slot_id);assert.equal(b.expected_configuration_sha256,seed.snapshot.slot.client.configuration_sha256);assert.equal(b.acknowledged_credential_operation,true);assert.equal(b.acknowledged_protocol_mock,true);assert.equal(b.valid_for_seconds,600);assert.equal(b.redirect_uri,origin+'/oauth/google/callback');assert.equal(h.get('ack').checked,false);assert.equal(h.get('external-link').hidden,true);});
test('owner raw acknowledgments finite input dirty active archived and busy guard dispatch',async()=>{const h=harness();await ready(h);const count=h.calls.length;for(const[field,value]of[['duration',''],['duration','59'],['duration','901'],['duration','NaN'],['ack',1],['mock-ack',1]]){h.get('duration').value='600';h.get('ack').checked=h.get('mock-ack').checked=true;if(field==='duration')h.get(field).value=value;else h.get(field).checked=value;await h.controller.createAuthorization();assert.equal(h.calls.length,count);}
 for(const change of[{canManage:false},{dirty:true},{active:true},{busy:true},{project:{id:seed.project_id,revision:1,archived:true}}]){Object.assign(h.state,{canManage:true,dirty:false,active:false,busy:false,project:{id:seed.project_id,revision:1}},change);h.get('duration').value='600';h.get('ack').checked=h.get('mock-ack').checked=true;await h.controller.createAuthorization();assert.equal(h.calls.length,count);}});
test('private authorization link requires explicit click and clears on context changes',async()=>{const h=harness();await ready(h);await h.controller.createAuthorization();const count=h.calls.length;await h.controller.getAuthorizationLink();assert.equal(h.calls.length,count+1);assert.equal(h.get('external-link').hidden,false);assert.match(h.get('external-link').href,/^https:\/\/accounts.google.com/);assert.equal(h.get('external-link').rel,'noopener noreferrer');assert.equal(h.get('external-link').target,'_blank');assert.equal(h.get('external-link').dataset.vfPermission,'manage');assert.doesNotMatch(h.get('detail').textContent,/authorization_url|state=|code_verifier/);
 h.state.project.revision=2;h.controller.sync();assert.equal(h.get('external-link').hidden,true);assert.equal(h.get('external-link').href,'');assert.equal(h.controller.currentBinding().authorization,null);});
test('expired selected authorization does not return a new private link',async()=>{const h=harness();await ready(h);await h.controller.createAuthorization();h.time(stamp+601000);const count=h.calls.length;await h.controller.getAuthorizationLink();assert.equal(h.calls.length,count);assert.equal(h.get('external-link').hidden,true);});
test('external navigation click rechecks deadline and clears an expired private link',async()=>{const h=harness();await ready(h);await h.controller.createAuthorization();await h.controller.getAuthorizationLink();h.time(stamp+601000);let prevented=false;h.get('external-link').listeners.click({preventDefault(){prevented=true;}});assert.equal(prevented,true);assert.equal(h.get('external-link').hidden,true);assert.equal(h.get('external-link').href,'');assert.equal(h.calls.length,3);});
test('expired history remains readable with runtime absent and viewer role',async()=>{const h=harness();h.state.canManage=false;h.controller.sync();h.time(stamp+86400000);await h.controller.readHistory('authorization');assert.equal(h.calls.length,1);assert.equal(h.get('history').children.length,fixture.authorizations.length);assert.notEqual(h.controller.currentBinding().authorization,null);assert.equal(h.get('cancel').disabled,true);const count=h.calls.length;await h.controller.readConfig();await h.controller.cancelAuthorization();await h.controller.refreshGrant();assert.equal(h.calls.length,count);});
test('unknown create key persists through explicit new preparation and verified retry',async()=>{const h=harness();await ready(h);let first=true;h.handler(async(path,body)=>{if(body&&first){first=false;throw new Error('UNKNOWN PRIVATE EXCEPTION');}return h.defaultHandler(path,body);});await h.controller.createAuthorization();const key=h.calls.at(-1)[1].request_key;h.controller.prepareNew();h.get('ack').checked=true;await h.controller.createAuthorization();assert.equal(h.calls.at(-1)[1].request_key,key);assert.equal(h.controller.currentBinding().authorization.status,'awaiting_callback');assert.doesNotMatch(JSON.stringify(h.messages),/UNKNOWN PRIVATE EXCEPTION/);});
test('verified consumed idempotent start reply closes original key without repeating exchange',async()=>{const h=harness();await ready(h);h.handler(async(path,body)=>({...pending(body),status:'consumed',operation_id:original.operation_id,idempotent_replay:true}));await h.controller.createAuthorization();const key=h.calls.at(-1)[1].request_key;assert.equal(h.controller.currentBinding().authorization.status,'consumed');h.controller.prepareNew();h.get('ack').checked=true;await h.controller.createAuthorization();assert.notEqual(h.calls.at(-1)[1].request_key,key);assert.equal(h.calls.filter(([p])=>p.includes('/exchange')).length,0);});
test('invalid create reply retains original key and does not establish a pending grant',async()=>{const h=harness();await ready(h);let first=true;h.handler(async(path,body)=>{const v=await h.defaultHandler(path,body);return first?(first=false,{...v,workspace_id:'foreign'}):v;});await h.controller.createAuthorization();const key=h.calls.at(-1)[1].request_key;assert.equal(h.controller.currentBinding().authorization,null);h.get('ack').checked=true;await h.controller.createAuthorization();assert.equal(h.calls.at(-1)[1].request_key,key);});
test('explicit cancellation binds original snapshot and does not revoke a grant',async()=>{const h=harness();await ready(h);await h.controller.createAuthorization();const prior=h.controller.currentBinding().authorization;await h.controller.cancelAuthorization();assert.deepEqual(h.calls.at(-1),[`/api/projects/${seed.project_id}/google-oauth/authorizations/${prior.authorization_id}/cancel`,{expected_snapshot_sha256:prior.snapshot_sha256}]);assert.equal(h.controller.currentBinding().authorization.status,'cancelled');assert.equal(h.get('cancel').disabled,true);});
test('refresh requires separate acknowledgment and exact original result generation',async()=>{const h=harness();await ready(h);await h.controller.readHistory('operation');const count=h.calls.length;await h.controller.refreshGrant();assert.equal(h.calls.length,count);h.get('refresh-ack').checked=h.get('mock-ack').checked=true;await h.controller.refreshGrant();const[path,b]=h.calls.at(-1);assert.equal(path,`/api/projects/${seed.project_id}/google-oauth/refresh`);assert.equal(b.source_operation_id,original.operation_id);assert.equal(b.expected_result_sha256,original.result_sha256);assert.equal(b.acknowledged_credential_operation,true);assert.equal(b.acknowledged_protocol_mock,true);assert.equal(h.get('refresh-ack').checked,false);assert.equal(h.controller.currentBinding().operation.result.credential_selected,false);});
test('refresh cannot automatically rotate an original generation already in history',async()=>{const h=harness();await ready(h);h.handler(async()=>page('operation',fixture.operations));await h.controller.readHistory('operation');const list=h.get('history').children,index=fixture.operations.findIndex(v=>v.operation_id===original.operation_id);list[index].listeners.click();h.get('refresh-ack').checked=h.get('mock-ack').checked=true;h.controller.controls();assert.equal(h.get('refresh').disabled,true);const count=h.calls.length;await h.controller.refreshGrant();assert.equal(h.calls.length,count);});
test('late configuration replies cannot cross workspace project revision archive role or source state',async()=>{for(const change of[h=>h.state.workspace_id='foreign',h=>h.state.project.id='a'.repeat(32),h=>h.state.project.revision=2,h=>h.state.project.archived=true,h=>h.state.canManage=false,h=>h.state.dirty=true,h=>h.state.active=true,h=>h.state.busy=true]){
 const h=harness();let release;h.handler(()=>new Promise(resolve=>{release=resolve;}));const pending=h.controller.readConfig();change(h);h.controller.sync();release(fixture.runtime);await pending;assert.equal(h.get('slot').children.length,0);assert.equal(h.get('external-link').hidden,true);assert.equal(h.messages.length,0);assert.equal(h.controller.isWorking(),false);}});
test('late private URL cannot survive changed slot selection',async()=>{const h=harness();await ready(h);await h.controller.createAuthorization();let release;h.handler(()=>new Promise(resolve=>{release=resolve;}));const pending=h.controller.getAuthorizationLink();h.get('slot').value=fixture.runtime.slots.find(v=>v.slot_id!==seed.snapshot.slot.slot_id).slot_id;h.get('slot').listeners.change();release(url(h.current()));await pending;assert.equal(h.get('external-link').hidden,true);assert.equal(h.get('external-link').href,'');assert.equal(h.messages.length,0);});
test('malformed foreign page preserves earlier history and cursor is bounded and encoded',async()=>{const h=harness();h.handler(async()=>page('authorization',fixture.authorizations,'opaque+/='));await h.controller.readHistory('authorization');h.handler(async()=>page('authorization',[]));await h.controller.readHistory('authorization',true);assert.match(h.calls.at(-1)[0],/&cursor=opaque%2B%2F%3D$/);const count=h.get('history').children.length;
 for(const v of[page('operation',[]),{...page('authorization',[]),workspace_id:'foreign'},page('authorization',[],'x'.repeat(2049)),{...page('authorization',[]),automatic_refresh:true}]){h.handler(async()=>v);await h.controller.readHistory('authorization');assert.equal(h.get('history').children.length,count);}assert.equal(h.messages.length,4);});
test('runtime rejects duplicate broader scopes raw safety aliases and private fields',()=>{assert.equal(validateGoogleOAuthRuntime(structuredClone(fixture.runtime),seed.workspace_id).mock,true);for(const mutate of[v=>v.enabled=1,v=>v.mock=1,v=>v.default_enabled=true,v=>v.startup_decryption=0,v=>v.slots.push(v.slots[0]),v=>v.slots[0].scopes.push('openid'),v=>v.slots[0].client.client_secret='PRIVATE',v=>v.slots[0].target.workspace_id='foreign',v=>v.slots[0].client.bytes=true]){const v=structuredClone(fixture.runtime);mutate(v);assert.throws(()=>validateGoogleOAuthRuntime(v,seed.workspace_id));}});
test('history validates original raw false flags current scope and nullable expiry without credentials',()=>{const state={workspace_id:seed.workspace_id,project:{id:seed.project_id}};for(const v of fixture.authorizations)assert.equal(validateGoogleOAuthHistory(structuredClone(v),state,'authorization').authorization_id,v.authorization_id);for(const v of fixture.operations)assert.equal(validateGoogleOAuthHistory(structuredClone(v),state,'operation').operation_id,v.operation_id);
 for(const mutate of[v=>v.token_returned=0,v=>v.snapshot.mock=1,v=>v.snapshot.request.acknowledged_credential_operation=1,v=>v.result.credential_selected=0,v=>v.result.grant_proof.account_verified=true,v=>v.result.grant_proof.refresh_expires_at='2026-10-09T12:00:00',v=>v.result.grant_proof.mock=false,v=>v.snapshot.request.source_operation_id='ngop_foreign',v=>v.result.grant_receipt.access_token='PRIVATE']){const v=structuredClone(fixture.operations.find(v=>v.snapshot.operation==='refresh_token'));mutate(v);assert.throws(()=>validateGoogleOAuthHistory(v,state,'operation'));}});
test('refresh reply cannot replace the selected original operation with another valid identity',async()=>{const h=harness();await ready(h);await h.controller.readHistory('operation');const prior=structuredClone(h.controller.currentBinding().operation);h.get('refresh-ack').checked=h.get('mock-ack').checked=true;h.handler(async(path,body)=>{const v=await h.defaultHandler(path,body);v.snapshot.request.source_operation_id='ngop_'+'f'.repeat(32);return v;});await h.controller.refreshGrant();assert.deepEqual(h.controller.currentBinding().operation,prior);assert.equal(h.messages.length,1);});
test('authorization URL rejects unrelated hosts redirects duplicate fields and altered state purpose',()=>{const auth=pending({...seed.snapshot.request,request_key:'fixture-key'}),value=url(auth);assert.match(validateGoogleAuthorizationURL(value,auth,origin+'/oauth/google/callback',stamp),/^https:/);for(const mutate of[v=>v.authorization_url=v.authorization_url.replace('accounts.google.com','untrusted.invalid'),v=>v.authorization_url+='&state=duplicate',v=>v.authorization_url+='&client_secret=PRIVATE',v=>v.token_returned=0,v=>v.external_human_browser_required=1,v=>v.authorization_url=v.authorization_url.replace('S256','plain'),v=>v.authorization_url=v.authorization_url.replace(auth.authorization_id,'ngoa_'+'f'.repeat(32))]){const v=structuredClone(value);mutate(v);assert.throws(()=>validateGoogleAuthorizationURL(v,auth,origin+'/oauth/google/callback',stamp));}assert.throws(()=>validateGoogleAuthorizationURL(value,auth,origin+'/oauth/google/callback',stamp+601000));});
