import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';
import{initializeNativeGoogleAnalyticsSelections,initializeNativeGoogleSelections,validateSelectionRuntime,validateSelectionHistory}from'../native-google-oauth-selections.mjs';
const fixture=JSON.parse(readFileSync(new URL('./fixtures/native-google-analytics-selection-v1.json',import.meta.url))),publishing=JSON.parse(readFileSync(new URL('./fixtures/native-google-selection-v1.json',import.meta.url)));
assert.equal(fixture.fixture_kind,'explicit_protocol_mock_not_owner_or_real_provider_acceptance');const source=fixture.source,stamp=Date.parse(fixture.pending.snapshot.approved_at);
function page(items){return{schema_version:'native-google-analytics-selection-page-v1',workspace_id:source.workspace_id,project_id:source.project_id,items,next_cursor:null,truncated:false,token_returned:false,publishing_enabled:false,automatic_refresh:false};}
function harness(){const nodes=new Map();class Node{constructor(){this.children=[];this.value='';this.checked=false;this.dataset={};this.listeners={};this.textContent='';}set id(v){this._id=v;nodes.set(v,this);}get id(){return this._id;}append(...v){this.children.push(...v);}replaceChildren(...v){this.children=[...v];}addEventListener(k,v){this.listeners[k]=v;}}
  const root={createElement:()=>new Node(),getElementById(v){if(!nodes.has(v))nodes.set(v,new Node());return nodes.get(v);}},get=v=>root.getElementById('native-google-analytics-selection-'+v),state={workspace_id:source.workspace_id,project:{id:source.project_id,revision:1},canManage:true,busy:false,dirty:false,active:false},calls=[],messages=[];let time=stamp,count=0,handler;
  const defaultHandler=async(path,body)=>{if(path==='/api/connections/google-oauth-analytics-selections')return structuredClone(fixture.runtime);
    if(path.includes('/operations?'))return{schema_version:'native-google-oauth-page-v1',workspace_id:source.workspace_id,project_id:source.project_id,kind:'operation',items:[structuredClone(source)],next_cursor:null,truncated:false,token_returned:false,publishing_enabled:false,automatic_refresh:false};
    if(path.endsWith('/verify'))return structuredClone(fixture.active);if(path.endsWith('/revoke'))return structuredClone(fixture.revoked);if(body)return structuredClone(fixture.pending);return page([structuredClone(fixture.active)]);};handler=defaultHandler;
  const controller=initializeNativeGoogleAnalyticsSelections({root,getState:()=>({...state}),api:async(...args)=>{calls.push(args);return handler(...args);},onMessage:(...v)=>messages.push(v),uuid:()=> 'explicit-analytics-ui-key-'+(++count),now:()=>time,purpose:'publishing'});
  return{root,get,state,calls,messages,controller,defaultHandler,handler:v=>{handler=v;},time:v=>{time=v;}};}
async function ready(h){await h.controller.readConfig();await h.controller.readGrants();h.get('ack').checked=h.get('account-ack').checked=h.get('mock-ack').checked=true;h.controller.controls();}
test('analytics connection initialization is inert with a dedicated card and DOM namespace',()=>{const h=harness();h.controller.sync();assert.equal(h.calls.length,0);assert.equal(h.get('create').disabled,true);assert.equal(h.controller.current(),null);
  const pub=initializeNativeGoogleSelections({root:h.root,getState:()=>h.state,api:()=>{throw Error('No startup read');}});assert.equal(pub.current(),null);assert.notEqual(h.root.getElementById('native-google-selection-ack'),h.get('ack'));});
test('analytics history and runtime reject publishing-purpose records and private or malformed evidence',()=>{const h=harness();assert.equal(validateSelectionRuntime(fixture.runtime,source.workspace_id,'analytics'),fixture.runtime);assert.equal(validateSelectionHistory(fixture.active,h.state,'analytics'),fixture.active);
  assert.throws(()=>validateSelectionRuntime(publishing.runtime,source.workspace_id,'analytics'));assert.throws(()=>validateSelectionHistory(publishing.active,h.state,'analytics'));assert.throws(()=>validateSelectionHistory(fixture.active,h.state));
  for(const change of[v=>v.publishing_enabled=true,v=>v.result.mock=false,v=>v.snapshot.grant_proof.purpose='publishing',v=>v.snapshot.request.acknowledged_account_access=1,v=>v.snapshot.slot.target.workspace_id='foreign',v=>v.snapshot.grant_receipt.access_token='private',v=>v.snapshot.authority.expires_at='2026-02-31T12:00:00Z']){const v=structuredClone(fixture.active);change(v);assert.throws(()=>validateSelectionHistory(v,h.state,'analytics'));}});
test('separate analytics create and verify select a readonly grant without launching statistics or publication',async()=>{const h=harness();await ready(h);await h.controller.createSelection();const[path,body]=h.calls.at(-1);assert.ok(path.endsWith('/analytics-selections'));assert.equal(body.source_operation_id,source.operation_id);assert.equal(body.expected_result_sha256,source.result_sha256);assert.equal(body.acknowledged_account_access,true);assert.equal(body.acknowledged_credential_selection,true);assert.equal(body.acknowledged_protocol_mock,true);
  assert.equal(h.controller.current().status,'pending_verification');assert.equal(h.calls.some(([p])=>p.endsWith('/verify')),false);await h.controller.verifySelection();assert.equal(h.controller.current().status,'active');assert.equal(h.controller.current().publishing_enabled,false);assert.equal(h.calls.some(([p])=>/analytics\/(?:collect|refresh)|publications/.test(p)),false);});
test('raw independent account choice and mock acknowledgments are all required',async()=>{const h=harness();await ready(h);for(const name of['ack','account-ack','mock-ack']){h.get(name).checked=false;h.controller.controls();assert.equal(h.get('create').disabled,true);const n=h.calls.length;await h.controller.createSelection();assert.equal(h.calls.length,n);h.get(name).checked=true;}h.controller.controls();assert.equal(h.get('create').disabled,false);});
test('publishing sources are filtered and cannot be selected for analytics',async()=>{const h=harness();await h.controller.readConfig();h.handler(async(path,body)=>path.includes('/operations?')?{...(await h.defaultHandler(path,body)),items:[structuredClone(publishing.source)]}:h.defaultHandler(path,body));await h.controller.readGrants();assert.equal(h.get('grant').children.length,0);assert.equal(h.get('create').disabled,true);});
test('local analytics revoke preserves the same immutable original evidence',async()=>{const h=harness();await h.controller.readHistory();await h.controller.revokeSelection();assert.equal(h.controller.current().status,'revoked');assert.equal(h.controller.current().snapshot_sha256,fixture.active.snapshot_sha256);assert.ok(h.calls.at(-1)[0].includes('/analytics-selections/ngasel_'));assert.equal(h.controller.current().automatic_refresh,false);});
test('viewer dirty active archived and busy contexts cannot prepare or verify',async()=>{for(const change of[{canManage:false},{dirty:true},{active:true},{busy:true},{project:{id:source.project_id,revision:1,archived:true}}]){const h=harness();await ready(h);Object.assign(h.state,change);h.controller.controls();const n=h.calls.length;await h.controller.createSelection();await h.controller.verifySelection();assert.equal(h.calls.length,n);}});
test('uncertain analytics preparation reuses its idempotency key without automatic request replay',async()=>{const h=harness();await ready(h);h.handler(async()=>{throw Error('Unknown response');});await h.controller.createSelection();const first=h.calls.at(-1)[1].request_key;assert.equal(h.controller.current(),null);await h.controller.createSelection();assert.equal(h.calls.at(-1)[1].request_key,first);assert.equal(h.calls.filter(([,body])=>body).length,2);});
test('late response never attaches a selection to a new project',async()=>{const h=harness();await ready(h);let reply;h.handler(()=>new Promise(resolve=>{reply=resolve;}));const pending=h.controller.createSelection();h.state.project={id:'f'.repeat(32),revision:1};h.controller.sync();reply(structuredClone(fixture.pending));await pending;assert.equal(h.controller.current(),null);assert.ok(h.messages.length);});
test('foreign cursor and original snapshot changes are refused',async()=>{const h=harness();h.handler(async()=>({...page([structuredClone(fixture.active)]),truncated:true,next_cursor:publishing.active.selection_id}));await h.controller.readHistory();assert.equal(h.controller.current(),null);h.handler(h.defaultHandler);await ready(h);await h.controller.createSelection();h.handler(async()=>{const v=structuredClone(fixture.active);v.snapshot.grant_receipt.cipher_sha256='a'.repeat(64);return v;});await h.controller.verifySelection();assert.equal(h.controller.current().status,'pending_verification');});
test('selection expiry and disabled runtime do not refresh credentials or start syncs',async()=>{const h=harness();await ready(h);await h.controller.createSelection();h.time(Date.parse(fixture.pending.snapshot.deadline));const n=h.calls.length;await h.controller.verifySelection();assert.equal(h.calls.length,n);const off=harness();off.handler(async(path,body)=>path.includes('/connections/')?{...structuredClone(fixture.runtime),enabled:false}:off.defaultHandler(path,body));await ready(off);assert.equal(off.get('create').disabled,true);assert.equal(off.calls.some(([,body])=>body),false);});
test('analytics card is connected to Native Studio shell and permission-aware refresh',()=>{const html=readFileSync(new URL('../native.html',import.meta.url),'utf8'),js=readFileSync(new URL('../native.mjs',import.meta.url),'utf8');assert.ok(html.includes('id="native-google-analytics-selections-card"'));assert.ok(js.includes('googleAnalyticsSelectionUI?.controls()'));assert.ok(js.includes('googleAnalyticsSelectionUI?.sync()'));assert.ok(js.includes('initializeNativeGoogleAnalyticsSelections'));});
