import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';
import{initializeNativeRenderThumbnailRights,validateRenderThumbnailRightsInput,validateRenderThumbnailRights}from'../native-render-thumbnail-rights.mjs';
import{initializeNativeRenderThumbnail}from'../native-render-thumbnail.mjs';
const fixture=JSON.parse(readFileSync(new URL('./fixtures/native-render-thumbnail-rights-v1.json',import.meta.url))),clone=v=>structuredClone(v),seed=fixture.rights[0];
assert.equal(fixture.fixture_kind,'original_retained_cpu_thumbnail_and_synthetic_owner_rights_records_not_owner_or_provider_acceptance');
const flags=['rights_independently_verified','publishing_authorized','source_asset_rights_granted','provider_authorized','canonical_timeline_mutated','project_revision_changed','final_video_approved','owner_uat_accepted','real_provider_tested'];
const runtime=enabled=>({schema_version:'native-render-thumbnail-rights-runtime-v1',workspace_id:seed.workspace_id,enabled,purpose:'render_thumbnail_rights_exception',current_owner_required:true,separate_thumbnail_ack_required:true,finite_expiry_required:true,rights_status:'unknown',license:null,external_calls:0,paid_operations:0,...Object.fromEntries(flags.map(k=>[k,false]))});
const page=(items,cursor=null)=>({schema_version:'native-render-thumbnail-rights-page-v1',workspace_id:seed.workspace_id,project_id:seed.project_id,items,limit:25,next_cursor:cursor,rights_status:'unknown',rights_independently_verified:false,publishing_authorized:false,owner_uat_accepted:false});
function harness(){const nodes=new Map();class Node{constructor(tag='details'){this.tagName=tag.toUpperCase();this.children=[];this.value='';this.checked=false;this.dataset={};this.listeners={};this.textContent='';this.style={};}set id(v){this._id=v;nodes.set(v,this);}get id(){return this._id;}append(...v){this.children.push(...v);}replaceChildren(...v){this.children=[...v];}addEventListener(k,v){this.listeners[k]=v;}}
 const root={createElement:tag=>new Node(tag),getElementById(v){if(!nodes.has(v))nodes.set(v,new Node());return nodes.get(v);}},get=id=>root.getElementById('native-render-thumbnail-rights-'+id),state={workspace_id:seed.workspace_id,project:clone(fixture.project),canManage:true,dirty:false,busy:false,active:false},calls=[],messages=[],work=[];let selected=clone(fixture.selection),handler,count=0;
 const defaultHandler=async(p,b)=>{if(p==='/api/connections/render-thumbnail-rights')return runtime(true);if(p.includes('/input/'))return clone(fixture.input);if(p.includes('?'))return page(clone([...fixture.rights].reverse()));if(b){const row=fixture.rights.find(r=>r.action===b.action&&r.snapshot.request.allow_publishing_review===b.allow_publishing_review&&r.snapshot.request.override_id===b.override_id);assert.ok(row);assert.deepEqual(row.snapshot.request,Object.fromEntries(Object.entries(b).filter(([k])=>k!=='request_key')));return{...clone(row),idempotent_replay:false};}throw new Error('Unexpected route');};handler=defaultHandler;
 const controller=initializeNativeRenderThumbnailRights({root,api:async(...v)=>{calls.push(v);return handler(...v);},getState:()=>({...state}),getSelection:()=>selected,onMessage:(...v)=>messages.push(v),onWorking:v=>work.push(v),uuid:()=> 'explicit-rights-test-key-'+(++count)});
 return{root,get,state,calls,messages,work,controller,defaultHandler,handler:v=>handler=v,selection:v=>selected=v};}
function fill(h,publish=false){h.get('reason').value=seed.snapshot.request.reason;h.get('reference').value=seed.snapshot.request.evidence_reference;h.get('days').value='7';h.get('publish').checked=publish;h.get('ack').checked=h.get('independent').checked=true;h.controller.controls();}
async function ready(h,publish=false){await h.controller.readConfig();await h.controller.readInput();fill(h,publish);}

test('mount refresh and controls never read grant license or publish automatically',()=>{const h=harness();h.controller.sync();h.controller.controls();assert.equal(h.calls.length,0);assert.equal(h.get('grant').disabled,true);assert.equal(h.get('revoke').disabled,true);assert.equal(h.get('ack').checked,false);assert.equal(h.get('publish').checked,false);assert.equal(h.controller.currentRecord(),null);});
test('settled parent loading guard keeps the first explicit input read',async()=>{const h=harness();h.state.busy=true;h.controller.sync();h.state.busy=false;h.controller.controls();await h.controller.readInput();assert.equal(h.calls.length,1);assert.ok(h.get('detail').textContent.includes(fixture.input.rights_input_sha256));assert.equal(h.messages.length,0);});
test('all original grant revoke image and source bindings validate without renewing Owner authority',()=>{const state={workspace_id:seed.workspace_id,project:fixture.project};for(const row of fixture.rights)assert.equal(validateRenderThumbnailRights(row,state),row);assert.equal(validateRenderThumbnailRightsInput(fixture.input,state,fixture.selection),fixture.input);assert.equal(seed.owner_uat_accepted,false);assert.equal(seed.snapshot.final_video_approved,false);});
test('grant uses exact original image hashes and two separate acknowledgements with default local review',async()=>{const h=harness();await ready(h);await h.controller.record('grant');const[p,b]=h.calls.at(-1);assert.equal(p,`/api/projects/${seed.project_id}/render-thumbnail-rights`);assert.equal(b.thumbnail_asset_id,fixture.selection.thumbnail_asset_id);assert.equal(b.expected_thumbnail_snapshot_sha256,fixture.selection.snapshot_sha256);assert.equal(b.expected_rights_input_sha256,fixture.input.rights_input_sha256);assert.equal(b.allow_publishing_review,false);assert.equal(b.acknowledged_thumbnail_rights_exception,true);assert.equal(b.acknowledged_not_independent_license_verification,true);assert.equal(h.controller.currentRecord().rights_status,'unknown');assert.equal(h.controller.currentRecord().license,null);assert.equal(h.get('ack').checked,false);assert.equal(h.get('independent').checked,false);assert.equal(h.get('publish').checked,false);assert.ok(!h.calls.some(([p])=>/process|jobs|publications/.test(p)));});
test('publishing review scope is separately opt in and does not approve video or source assets',async()=>{const h=harness();await ready(h,true);await h.controller.record('grant');const v=h.controller.currentRecord();assert.equal(v.snapshot.request.allow_publishing_review,true);assert.equal(v.publishing_authorized,false);assert.equal(v.snapshot.source_asset_rights_granted,false);assert.equal(v.snapshot.final_video_approved,false);assert.equal(v.snapshot.owner_uat_accepted,false);});
test('default off prevents new grants but permits explicit revocation of original latest grant',async()=>{const h=harness();h.handler(async(p,b)=>p==='/api/connections/render-thumbnail-rights'?runtime(false):p.includes('?')?page([clone(fixture.rights[1]),clone(seed)]):h.defaultHandler(p,b));await ready(h);const n=h.calls.length;await h.controller.record('grant');assert.equal(h.calls.length,n);await h.controller.readHistory();fill(h,true);await h.controller.record('revoke');const b=h.calls.at(-1)[1];assert.equal(b.override_id,fixture.rights[1].override_id);assert.equal(b.expected_override_sha256,fixture.rights[1].snapshot_sha256);assert.equal(b.allow_publishing_review,false);assert.equal(h.controller.currentRecord().action,'revoke');assert.equal(h.controller.currentRecord().snapshot.expires_at,null);});
test('non Owner reads scoped input and immutable history but cannot read configuration or write',async()=>{const h=harness();h.state.canManage=false;h.controller.sync();await h.controller.readConfig();assert.equal(h.calls.length,0);await h.controller.readInput();await h.controller.readHistory();fill(h,true);const n=h.calls.length;await h.controller.record('grant');await h.controller.record('revoke');assert.equal(h.calls.length,n);assert.equal(h.get('config').disabled,true);assert.equal(h.get('ack').disabled,true);assert.equal(h.get('history').disabled,false);assert.equal(h.controller.currentRecord().publishing_authorized,false);});
test('grant requires explicit runtime and original input independently of checked acknowledgements',async()=>{for(const omit of['runtime','input']){const h=harness();if(omit!=='runtime')await h.controller.readConfig();if(omit!=='input')await h.controller.readInput();fill(h,true);const n=h.calls.length;await h.controller.record('grant');assert.equal(h.calls.length,n);assert.equal(h.controller.currentRecord(),null);}});
test('raw boolean substitutes unsafe references reason and expiry never reach the write API',async()=>{for(const mutate of[h=>h.get('ack').checked=1,h=>h.get('independent').checked='true',h=>h.get('publish').checked=1,h=>h.get('days').value='0',h=>h.get('days').value='31',h=>h.get('days').value='1.5',h=>h.get('reason').value='short',h=>h.get('reference').value='https://example.test/?access_token=PRIVATE',h=>h.get('reference').value='https://user:PRIVATE@example.test/',h=>h.get('reference').value='file:///C:/PRIVATE',h=>h.get('reference').value='document:PRIVATE#token']){const h=harness();await ready(h);mutate(h);const n=h.calls.length;await h.controller.record('grant');assert.equal(h.calls.length,n);assert.equal(h.controller.currentRecord(),null);}});
test('dirty busy archived active stale version and changed selected image invalidate grants',async()=>{for(const change of[h=>h.state.dirty=true,h=>h.state.busy=true,h=>h.state.active=true,h=>h.state.canManage=false,h=>h.state.project.archived=true,h=>h.state.project.revision++,h=>h.selection({...fixture.selection,thumbnail_asset_id:'ast_rthumb_'+'f'.repeat(32)})]){const h=harness();await ready(h);change(h);const n=h.calls.length;await h.controller.record('grant');assert.equal(h.calls.length,n);assert.equal(h.get('ack').checked,false);assert.equal(h.controller.currentRecord(),null);}});
test('historical records remain readable after edit but cannot grant for an old image',async()=>{const h=harness();h.state.project.revision++;h.controller.sync();await h.controller.readHistory();await h.controller.readInput();await h.controller.readConfig();fill(h);const n=h.calls.length;await h.controller.record('grant');assert.equal(h.calls.length,n);assert.equal(h.controller.currentRecord().snapshot.request.revision,fixture.project.revision);});
test('superseded and already revoked records cannot be selected for revocation',async()=>{const h=harness();await ready(h);await h.controller.readHistory();h.get('list').children[3].listeners.click();fill(h);const n=h.calls.length;await h.controller.record('revoke');assert.equal(h.calls.length,n);h.get('list').children[1].listeners.click();fill(h);await h.controller.record('revoke');assert.equal(h.calls.length,n);});
test('unknown response retains request key success releases it and private error text is suppressed',async()=>{const h=harness();await ready(h);h.handler(async()=>{throw new Error('PRIVATE credential transport details');});await h.controller.record('grant');const key=h.calls.at(-1)[1].request_key;h.handler(h.defaultHandler);await h.controller.record('grant');assert.equal(h.calls.at(-1)[1].request_key,key);fill(h);await h.controller.record('grant');assert.notEqual(h.calls.at(-1)[1].request_key,key);assert.ok(!h.messages.some(v=>v[0].includes('PRIVATE')));});
test('late input or grant cannot cross project workspace role draft or thumbnail selection',async()=>{for(const operation of['input','grant'])for(const change of[h=>h.state.project.id='f'.repeat(32),h=>h.state.workspace_id='foreign',h=>h.state.canManage=false,h=>h.state.dirty=true,h=>h.selection(null)]){const h=harness();if(operation==='grant')await ready(h);let release;h.handler(()=>new Promise(r=>release=r));const wait=operation==='grant'?h.controller.record('grant'):h.controller.readInput();change(h);h.controller.sync();release(operation==='grant'?{...clone(fixture.rights[1]),idempotent_replay:false}:clone(fixture.input));await wait;assert.equal(h.controller.currentRecord(),null);assert.equal(h.get('ack').checked,false);assert.equal(h.controller.isWorking(),false);assert.equal(h.messages.length,0);}});
test('changing form during outstanding write discards late reply without automatic retry',async()=>{const h=harness();await ready(h);let release;h.handler(()=>new Promise(r=>release=r));const wait=h.controller.record('grant');h.get('reason').value='another explicit review reason';h.get('reason').listeners.change();release({...clone(fixture.rights[1]),idempotent_replay:false});await wait;assert.equal(h.controller.currentRecord(),null);assert.equal(h.calls.length,3);assert.equal(h.messages.length,0);});
test('history pagination is bounded encoded original and does not authorize expired evidence',async()=>{const h=harness();h.handler(async()=>page([clone(fixture.rights[3])],'original_cursor-01'));await h.controller.readHistory();h.handler(async()=>page([clone(fixture.rights[1])]));await h.controller.readHistory(true);assert.match(h.calls.at(-1)[0],/limit=25&cursor=original_cursor-01$/);assert.equal(h.get('list').children.length,2);assert.equal(h.controller.currentRecord().owner_uat_accepted,false);assert.equal(h.get('revoke').disabled,true);assert.equal(h.calls.length,2);});
test('history displays familiar dates and original expiry without claiming a currently valid license',async()=>{const h=harness();await h.controller.readHistory();assert.ok(!h.get('list').children[0].textContent.includes('T17:'));assert.match(h.get('decision').textContent,/thời hạn đến/);assert.match(h.get('decision').textContent,/còn cần kiểm tra quyền/);h.get('list').children[1].listeners.click();assert.match(h.get('decision').textContent,/Đã ghi thu hồi/);assert.equal(h.get('ack').checked,false);});
test('invalid runtime pages and returned private values preserve original readable evidence',async()=>{const h=harness();await h.controller.readHistory();const original=h.controller.currentRecord();for(const v of[{...page([seed]),workspace_id:'foreign'},page([seed],'x'.repeat(1001)),page([seed],'unsafe+/='),{...page([seed]),owner_uat_accepted:true},{...page([seed]),rights_status:'owned'},page(Array(26).fill(seed)),{...page([seed]),api_key:'PRIVATE'}]){h.handler(async()=>v);await h.controller.readHistory();assert.equal(h.controller.currentRecord(),original);}for(const v of[{...runtime(true),enabled:1},{...runtime(true),provider_authorized:true},{...runtime(true),paid_operations:1}]){h.handler(async()=>v);await h.controller.readConfig();assert.equal(h.get('grant').disabled,true);}});
test('input refuses lost provenance fabricated licenses and swapped final video',()=>{const state={workspace_id:seed.workspace_id,project:fixture.project};for(const mutate of[v=>v.binding.image.rights_status='licensed',v=>v.binding.image.license='invented',v=>v.binding.image.sha256='a'.repeat(64),v=>v.binding.final_sha256='a'.repeat(64),v=>v.binding.image.evidence_frame_reference='../../private',v=>v.binding.source_asset_rights_granted=true,v=>v.binding.image.data_url='PRIVATE',v=>v.publishing_authorized=0]){const v=clone(fixture.input);mutate(v);assert.throws(()=>validateRenderThumbnailRightsInput(v,state,fixture.selection));}});
test('original records reject coercion wrong purpose impossible dates revoked expiry and altered chains',()=>{const state={workspace_id:seed.workspace_id,project:fixture.project};for(const mutate of[v=>v.sequence=true,v=>v.snapshot.request.acknowledged_thumbnail_rights_exception=1,v=>v.snapshot.request.acknowledged_not_independent_license_verification='true',v=>v.snapshot.request.allow_publishing_review=1,v=>v.snapshot.paid_operations=false,v=>v.snapshot.provider_authorized=true,v=>v.snapshot.purpose='source_asset_rights',v=>v.snapshot.owner_identity.identity_revision_sha256='bad',v=>v.created_at=v.snapshot.created_at='2026-02-31T00:00:00Z',v=>v.snapshot.expires_at=v.snapshot.created_at,v=>v.snapshot.request.request_key='unexpected',v=>v.snapshot.api_key='PRIVATE',v=>v.snapshot.rights_input.image.license='invented',v=>v.workspace_id='foreign']){const v=clone(seed);mutate(v);assert.throws(()=>validateRenderThumbnailRights(v,state));}for(const mutate of[v=>v.snapshot.expires_at=v.snapshot.created_at,v=>v.snapshot.previous_record.sequence=v.sequence,v=>v.snapshot.request.override_id='nro_'+'a'.repeat(32)]){const v=clone(fixture.rights[2]);mutate(v);assert.throws(()=>validateRenderThumbnailRights(v,state));}});
test('rights operation locks thumbnail actions without discarding the exact selected original',async()=>{const h=harness(),thumbnail=initializeNativeRenderThumbnail({root:h.root,api:async()=>({schema_version:'native-render-thumbnail-page-v1',workspace_id:seed.workspace_id,project_id:seed.project_id,items:[clone(fixture.selection)],limit:25,next_cursor:null,publishing_authorized:false,owner_uat_accepted:false}),getState:()=>({workspace_id:seed.workspace_id,project:fixture.project,canEdit:true,dirty:false,busy:false,active:false,locked:h.controller.isWorking()})});await thumbnail.readHistory();h.selection(thumbnail.currentSelection());h.controller.sync();await ready(h);const chosen=thumbnail.currentSelection();let release;h.handler(()=>new Promise(r=>release=r));const wait=h.controller.record('grant');thumbnail.controls();assert.equal(h.root.getElementById('native-render-thumbnail-history').disabled,true);assert.equal(thumbnail.currentSelection(),chosen);release({...clone(fixture.rights[1]),idempotent_replay:false});await wait;thumbnail.controls();assert.equal(thumbnail.currentSelection(),chosen);assert.equal(h.controller.currentRecord().action,'grant');});
test('shell keeps Owner role original selection portrait review and default publishing gates separate',()=>{const native=readFileSync(new URL('../native.mjs',import.meta.url),'utf8'),html=readFileSync(new URL('../native.html',import.meta.url),'utf8'),shot=readFileSync(new URL('../shot-studio.mjs',import.meta.url),'utf8'),server=readFileSync(new URL('../../../services/windows_native/server.py',import.meta.url),'utf8');assert.match(html,/id="native-render-thumbnail-rights-card" hidden/);assert.match(native,/native_render_thumbnail_rights_review===true&&session.access\?\.mode==='registry'/);assert.match(native,/getSelection:\(\)=>renderThumbnailUI\?\.currentSelection\(\)/);assert.match(native,/renderThumbnailRightsUI\?\.sync\(\)/);assert.match(native,/locked:renderThumbnailRightsUI\?\.isWorking\(\)/);assert.match(shot,/move\('#native-render-thumbnail-rights-card','video-review-body'\)/);assert.match(shot,/append\(thumbnailRights\)/);assert.match(server,/static\['\/native-render-thumbnail-rights.mjs'\]/);assert.match(server,/render_thumbnail_rights_enabled=False/);assert.match(server,/"native_live_publishing":False/);});
