import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';
import{initializeNativeGoogleSelections,validateSelectionRuntime,validateSelectionHistory}from'../native-google-oauth-selections.mjs';
const fixture=JSON.parse(readFileSync(new URL('./fixtures/native-google-selection-v1.json',import.meta.url)));assert.equal(fixture.fixture_kind,'explicit_protocol_mock_not_owner_or_real_provider_acceptance');
const source=fixture.source,stamp=Date.parse(fixture.pending.snapshot.approved_at);
function page(items){return{schema_version:'native-google-selection-page-v1',workspace_id:source.workspace_id,project_id:source.project_id,items,next_cursor:null,truncated:false,token_returned:false,publishing_enabled:false,automatic_refresh:false};}
function harness(){const nodes=new Map();class Node{constructor(){this.children=[];this.value='';this.checked=false;this.dataset={};this.listeners={};this.textContent='';}set id(v){this._id=v;nodes.set(v,this);}get id(){return this._id;}append(...v){this.children.push(...v);}replaceChildren(...v){this.children=[...v];}addEventListener(k,v){this.listeners[k]=v;}}
  const root={createElement:()=>new Node(),getElementById(v){if(!nodes.has(v))nodes.set(v,new Node());return nodes.get(v);}},get=v=>root.getElementById('native-google-selection-'+v),state={workspace_id:source.workspace_id,project:{id:source.project_id,revision:1},canManage:true,busy:false,dirty:false,active:false},calls=[],messages=[];let time=stamp,count=0,handler;
  const defaultHandler=async(path,body)=>{if(path==='/api/connections/google-oauth-selections')return structuredClone(fixture.runtime);
    if(path.includes('/operations?'))return{schema_version:'native-google-oauth-page-v1',workspace_id:source.workspace_id,project_id:source.project_id,kind:'operation',items:[structuredClone(source)],next_cursor:null,truncated:false,token_returned:false,publishing_enabled:false,automatic_refresh:false};
    if(path.endsWith('/verify'))return structuredClone(fixture.active);if(path.endsWith('/revoke'))return structuredClone(fixture.revoked);if(body)return structuredClone(fixture.pending);return page([structuredClone(fixture.active)]);};handler=defaultHandler;
  const controller=initializeNativeGoogleSelections({root,getState:()=>({...state}),api:async(...args)=>{calls.push(args);return handler(...args);},onMessage:(...v)=>messages.push(v),uuid:()=> 'explicit-selection-ui-key-'+(++count),now:()=>time});
  return{root,get,state,calls,messages,controller,defaultHandler,handler:v=>{handler=v;},time:v=>{time=v;}};}
async function ready(h){await h.controller.readConfig();await h.controller.readGrants();h.get('ack').checked=h.get('account-ack').checked=h.get('mock-ack').checked=true;h.controller.controls();}
test('inert init no provider startup or implicit OAuth publication selection',()=>{const h=harness();h.controller.sync();assert.equal(h.calls.length,0);assert.equal(h.get('create').disabled,true);assert.equal(h.get('verify').disabled,true);assert.equal(h.controller.current(),null);});
test('dedicated runtime and history preserve mock disabled public and exact grant scope',()=>{const h=harness();assert.equal(validateSelectionRuntime(fixture.runtime,source.workspace_id),fixture.runtime);assert.equal(validateSelectionHistory(fixture.active,h.state),fixture.active);
  for(const change of[v=>v.publishing_enabled=true,v=>v.result.mock=false,v=>v.result.account_verified=1,v=>v.snapshot.grant_proof.purpose='analytics',v=>v.snapshot.request.acknowledged_account_access=1,v=>v.snapshot.slot.target.workspace_id='foreign',v=>v.snapshot.grant_receipt.token='private',v=>v.snapshot.authority.expires_at='2026-02-31T12:00:00Z']){const v=structuredClone(fixture.active);change(v);assert.throws(()=>validateSelectionHistory(v,h.state));}});
test('explicit create then verify requires separate click and keeps publication disabled',async()=>{const h=harness();await ready(h);await h.controller.createSelection();const[path,body]=h.calls.at(-1);assert.ok(path.endsWith('/selections'));assert.equal(body.source_operation_id,source.operation_id);assert.equal(body.expected_result_sha256,source.result_sha256);assert.equal(body.acknowledged_account_access,true);assert.equal(body.acknowledged_credential_selection,true);assert.equal(body.acknowledged_protocol_mock,true);assert.equal(h.controller.current().status,'pending_verification');assert.equal(h.calls.some(([p])=>p.endsWith('/verify')),false);
  await h.controller.verifySelection();assert.equal(h.controller.current().status,'active');assert.equal(h.controller.current().publishing_enabled,false);assert.deepEqual(h.calls.at(-1)[1],{expected_snapshot_sha256:fixture.pending.snapshot_sha256});});
test('local revoke exact selected snapshot has no publishing or refresh action',async()=>{const h=harness();await h.controller.readHistory();await h.controller.revokeSelection();assert.equal(h.controller.current().status,'revoked');assert.ok(h.calls.at(-1)[0].endsWith('/revoke'));assert.equal(h.calls.some(([p])=>p.endsWith('/refresh')||p.includes('official-publications')),false);});
test('dirty archived role blocked and expiry refuse before any write',async()=>{for(const[flag,value]of[['dirty',true],['active',true],['canManage',false],['busy',true]]){const h=harness();await ready(h);h.state[flag]=value;const count=h.calls.length;await h.controller.createSelection();assert.equal(h.calls.length,count);}const h=harness();await ready(h);h.time(Date.parse(source.result.grant_proof.expires_at)-89999);const count=h.calls.length;await h.controller.createSelection();assert.equal(h.calls.length,count);});
test('separate raw acknowledgement checkboxes all required before write',async()=>{for(const field of['ack','account-ack','mock-ack']){const h=harness();await ready(h);h.get(field).checked=false;const count=h.calls.length;await h.controller.createSelection();assert.equal(h.calls.length,count);}});
test('unknown create outcome reuses exact request key and never auto verifies',async()=>{const h=harness();await ready(h);let attempt=0;h.handler(async(path,body)=>{if(body&&++attempt===1)throw new Error('mock uncertain');return h.defaultHandler(path,body);});await h.controller.createSelection();const first=h.calls.at(-1)[1];await h.controller.createSelection();assert.equal(h.calls.at(-1)[1].request_key,first.request_key);assert.equal(h.calls.filter(([p])=>p.endsWith('/verify')).length,0);});
test('changed original grant reply not accepted or auto verified',async()=>{const h=harness();await ready(h);h.handler(async(path,body)=>{const v=await h.defaultHandler(path,body);if(body)v.snapshot.source_operation_snapshot_sha256='f'.repeat(64);return v;});await h.controller.createSelection();assert.equal(h.controller.current(),null);assert.equal(h.messages.length,1);});
test('late create reply cannot bind a new project and tells user to read history',async()=>{const h=harness();await ready(h);let resolve;h.handler(()=>new Promise(r=>{resolve=r;}));const pending=h.controller.createSelection();h.state.project={...h.state.project,id:'f'.repeat(32)};h.controller.sync();resolve(structuredClone(fixture.pending));await pending;assert.equal(h.controller.current(),null);assert.equal(h.messages.length,1);});
test('original snapshot altered on verify reply refused without replacing history',async()=>{const h=harness();await ready(h);await h.controller.createSelection();h.handler(async()=>{const v=structuredClone(fixture.active);v.snapshot.document_sha256='e'.repeat(64);return v;});await h.controller.verifySelection();assert.equal(h.controller.current().status,'pending_verification');assert.equal(h.messages.length,1);});
test('expired verification button recomputed before API and no token refresh inferred',async()=>{const h=harness();await ready(h);await h.controller.createSelection();h.time(Date.parse(fixture.pending.snapshot.deadline));const count=h.calls.length;await h.controller.verifySelection();assert.equal(h.calls.length,count);assert.equal(h.controller.current().status,'pending_verification');});
test('runtime disabled and missing publishing source never creates or verifies',async()=>{const h=harness();h.handler(async(path,body)=>{const v=await h.defaultHandler(path,body);if(path==='/api/connections/google-oauth-selections')v.enabled=false;return v;});await ready(h);const count=h.calls.length;await h.controller.createSelection();assert.equal(h.calls.length,count);});
