import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';
import{initializeNativeRenderVision,validateRenderVisionRuntime,validateRenderVisionInput,validateRenderVisionHistory,renderVisionFrameUrl}from'../native-render-vision.mjs';
const fixture=JSON.parse(readFileSync(new URL('./fixtures/native-render-vision-v1.json',import.meta.url)));assert.equal(fixture.fixture_kind,'explicit_owned_render_pixels_protocol_mock_not_owner_or_provider_acceptance');
const seed=fixture.histories.find(v=>v.status==='succeeded'&&v.snapshot.configuration.configuration_sha256===fixture.runtime.profiles[0].configuration_sha256),clone=v=>structuredClone(v);
const page=(items,cursor=null)=>({schema_version:'native-render-vision-page-v1',workspace_id:seed.workspace_id,project_id:seed.project_id,items,next_cursor:cursor,limit:25,automatic_dispatch:false,publishing_enabled:false,owner_uat_accepted:false});
function pending(body){const v=clone(seed);v.status='approved';v.claim_id=v.cost_operation_id=v.response_id=v.result_sha256=v.result=v.response=null;v.snapshot.request={...body};delete v.snapshot.request.request_key;v.snapshot.deadline=new Date(Date.parse(v.snapshot.approved_at)+body.valid_for_seconds*1000).toISOString();v.idempotent_replay=false;return v;}
function harness(){const nodes=new Map();class Node{constructor(){this.children=[];this.value='';this.checked=false;this.dataset={};this.listeners={};this.textContent='';this.style={};}set id(v){this._id=v;nodes.set(v,this);}get id(){return this._id;}append(...v){this.children.push(...v);}replaceChildren(...v){this.children=[...v];}addEventListener(k,v){this.listeners[k]=v;}}
 const root={createElement:()=>new Node(),getElementById(v){if(!nodes.has(v))nodes.set(v,new Node());return nodes.get(v);}},get=id=>root.getElementById('native-render-vision-'+id),state={workspace_id:seed.workspace_id,project:clone(fixture.project),canManage:true,dirty:false,busy:false,active:false},calls=[],messages=[],work=[];let current=null,handler,count=0,stamp=Date.parse(seed.snapshot.approved_at);
 const defaultHandler=async(path,body)=>{if(path==='/api/connections/render-vision')return clone(fixture.runtime);if(path.endsWith('/input/'+seed.snapshot.request.render_job_id))return clone(fixture.input);if(path.includes('?'))return page(fixture.histories);
  if(path.endsWith('/process'))return clone(seed);if(path.endsWith('/cancel'))return{...clone(current??seed),status:'cancelled',result:null,result_sha256:null};if(body){current=pending(body);return current;}return clone(current??seed);};handler=defaultHandler;
 const controller=initializeNativeRenderVision({root,api:async(...v)=>{calls.push(v);return handler(...v);},getState:()=>({...state}),onMessage:(...v)=>messages.push(v),onWorking:v=>work.push(v),uuid:()=> 'explicit-ui-render-vision-key-'+(++count),now:()=>stamp});
 return{root,get,state,calls,messages,work,controller,defaultHandler,handler:v=>{handler=v;},time:v=>{stamp=v;}};
}
async function ready(h){await h.controller.readConfig();h.get('video').value=seed.snapshot.request.render_job_id;await h.controller.readInput();h.get('profile').value=seed.snapshot.request.profile_id;h.get('ceiling').value='500';h.get('duration').value='600';h.get('ack').checked=h.get('mock-ack').checked=true;h.controller.controls();}
function text(n){return[n.textContent,...n.children.map(text)].join(' ');}

test('mount sync and controls make no discovery approval or provider request',()=>{const h=harness();h.controller.sync();h.controller.controls();assert.equal(h.calls.length,0);assert.equal(h.get('create').disabled,true);assert.equal(h.get('process').disabled,true);assert.equal(h.get('ack').checked,false);assert.equal(h.get('ceiling').value,'');assert.equal(h.get('video').children.length,2);});
test('original fixture runtime input all keyless histories and bounded PNG routes validate',()=>{const s={workspace_id:seed.workspace_id,project:fixture.project};validateRenderVisionRuntime(clone(fixture.runtime),s.workspace_id);validateRenderVisionInput(clone(fixture.input),s);for(const row of fixture.histories)validateRenderVisionHistory(clone(row),s);assert.match(renderVisionFrameUrl(seed.project_id,seed.snapshot.request.render_job_id,0),/\/render-vision\/input\/[a-f0-9]{32}\/frame\/0$/);for(const args of[['bad',seed.snapshot.request.render_job_id,0],[seed.project_id,'bad',0],[seed.project_id,seed.snapshot.request.render_job_id,8],[seed.project_id,seed.snapshot.request.render_job_id,true]])assert.throws(()=>renderVisionFrameUrl(...args));});
test('explicit finite rendered-image consent binds original render and config but never processes',async()=>{const h=harness();await ready(h);await h.controller.createIntent();const[path,b]=h.calls.at(-1);assert.equal(path,`/api/projects/${seed.project_id}/render-vision`);assert.equal(b.render_job_id,fixture.input.render_job_id);assert.equal(b.expected_render_input_sha256,fixture.input.input_sha256);assert.equal(b.expected_configuration_sha256,fixture.runtime.profiles[0].configuration_sha256);assert.equal(b.acknowledged_rendered_frame_analysis,true);assert.equal(b.acknowledged_protocol_mock,true);assert.equal(b.max_operation_cost_vnd,'500');assert.equal(b.valid_for_seconds,600);assert.equal(b.acknowledged_external_image_analysis,undefined);assert.equal(h.controller.currentBinding().status,'approved');assert.equal(h.get('ack').checked,false);assert.equal(h.calls.filter(([p])=>p.endsWith('/process')).length,0);});
test('process is a separate exact snapshot-bound action and success never replays',async()=>{const h=harness();await ready(h);await h.controller.createIntent();await h.controller.processSelected();assert.match(h.calls.at(-1)[0],/\/nrvi_[a-f0-9]{32}\/process$/);assert.deepEqual(h.calls.at(-1)[1],{expected_snapshot_sha256:seed.snapshot_sha256});assert.equal(h.controller.currentBinding().status,'succeeded');const n=h.calls.length;h.controller.controls();await h.controller.processSelected();assert.equal(h.calls.length,n);});
test('non-owner dirty busy active archived stale render and raw acknowledgements cannot create',async()=>{const h=harness();await ready(h);const n=h.calls.length;for(const change of[{canManage:false},{dirty:true},{busy:true},{active:true},{project:{...fixture.project,archived:true}},{project:{...fixture.project,revision:fixture.project.revision+1}}]){Object.assign(h.state,{canManage:true,dirty:false,busy:false,active:false,project:clone(fixture.project)},change);await h.controller.createIntent();assert.equal(h.calls.length,n);}
 for(const[field,value]of[['duration',''],['duration','59'],['duration','901'],['duration','NaN'],['ceiling',''],['ceiling','NaN'],['ceiling','-1'],['ceiling','1.0000001'],['ack',1],['mock-ack',1]]){const h=harness();await ready(h);if(field==='ack'||field==='mock-ack')h.get(field).checked=value;else h.get(field).value=value;const count=h.calls.length;await h.controller.createIntent();assert.equal(h.calls.length,count);}});
test('default-off disabled profile and historical input never allow a new consent',async()=>{for(const change of[v=>v.enabled=false,v=>v.profiles[0].status='NOT_CONFIGURED']){const h=harness();h.handler(async(p,b)=>{const v=await h.defaultHandler(p,b);if(p==='/api/connections/render-vision')change(v);return v;});await ready(h);const n=h.calls.length;await h.controller.createIntent();assert.equal(h.calls.length,n);}
 const h=harness();h.handler(async(p,b)=>{const v=await h.defaultHandler(p,b);if(p.includes('/input/'))v.binding.matches_current_project_document=false;return v;});await ready(h);const n=h.calls.length;await h.controller.createIntent();assert.equal(h.calls.length,n);});
test('unknown create reply preserves exact idempotency key and successful response releases it',async()=>{const h=harness();await ready(h);h.handler(async()=>{throw new Error('PRIVATE provider diagnostics');});await h.controller.createIntent();const key=h.calls.at(-1)[1].request_key;h.handler(h.defaultHandler);await h.controller.createIntent();assert.equal(h.calls.at(-1)[1].request_key,key);h.controller.prepareNew();h.get('ack').checked=h.get('mock-ack').checked=true;await h.controller.createIntent();assert.notEqual(h.calls.at(-1)[1].request_key,key);assert.equal(h.messages.some(v=>v[0].includes('PRIVATE')),false);});
test('finite original deadline disables process without renewal',async()=>{const h=harness();await ready(h);await h.controller.createIntent();h.time(Date.parse(h.controller.currentBinding().snapshot.deadline));const n=h.calls.length;h.controller.controls();assert.equal(h.get('process').disabled,true);await h.controller.processSelected();assert.equal(h.calls.length,n);});
test('explicit local cancellation is snapshot-bound and terminal state cannot process',async()=>{const h=harness();await ready(h);await h.controller.createIntent();await h.controller.cancelSelected();assert.match(h.calls.at(-1)[0],/\/cancel$/);assert.deepEqual(h.calls.at(-1)[1],{expected_snapshot_sha256:seed.snapshot_sha256});assert.equal(h.controller.currentBinding().status,'cancelled');const n=h.calls.length;await h.controller.processSelected();assert.equal(h.calls.length,n);});
test('viewer reads keyless original history with mock and unverified billing labels',async()=>{const h=harness();h.state.canManage=false;h.controller.sync();h.handler(async()=>page([seed]));await h.controller.readHistory();assert.equal(h.calls.length,1);assert.equal(h.get('config').disabled,true);assert.equal(h.get('process').disabled,true);assert.match(text(h.get('results')),/Diễn tập trên khung hình thật/);assert.match(text(h.get('results')),/hóa đơn thực tế: chưa có/);assert.equal(h.controller.currentBinding().result.hard_qc_replaced,false);});
test('unknown or review-required history cannot process or become semantic acceptance',async()=>{for(const saved of fixture.histories.filter(v=>['outcome_unknown','review_required'].includes(v.status))){const h=harness();h.handler(async()=>page([saved]));await h.controller.readHistory();const n=h.calls.length;await h.controller.processSelected();assert.equal(h.calls.length,n);assert.equal(h.controller.currentBinding().result,null);}});
test('project workspace revision permission dirty active and busy drift discard late config',async()=>{for(const change of[h=>h.state.project.id='f'.repeat(32),h=>h.state.workspace_id='foreign',h=>h.state.project.revision++,h=>h.state.canManage=false,h=>h.state.dirty=true,h=>h.state.active=true,h=>h.state.busy=true]){const h=harness();let release;h.handler(()=>new Promise(r=>release=r));const wait=h.controller.readConfig();change(h);h.controller.sync();release(clone(fixture.runtime));await wait;assert.equal(h.get('profile').children.length,0);assert.equal(h.messages.length,0);assert.equal(h.controller.isWorking(),false);}});
test('selected video change discards late input and clears acknowledgement',async()=>{const h=harness();h.get('video').value=fixture.input.render_job_id;let release;h.handler(()=>new Promise(r=>release=r));const wait=h.controller.readInput();h.get('video').value='f'.repeat(32);h.get('video').listeners.change();release(clone(fixture.input));await wait;assert.equal(h.get('input-frames').children.length,0);assert.equal(h.get('ack').checked,false);assert.equal(h.messages.length,0);});
test('late consent reply cannot bind a different profile video or project',async()=>{const h=harness();await ready(h);let release;h.handler(()=>new Promise(r=>release=r));const wait=h.controller.createIntent(),body=h.calls.at(-1)[1];h.get('video').value='';h.get('video').listeners.change();release(pending(body));await wait;assert.equal(h.controller.currentBinding(),null);assert.equal(h.messages.length,0);});
test('malformed pages preserve old history and bounded cursors are encoded',async()=>{const h=harness();h.handler(async()=>page([seed],'valid_cursor-01'));await h.controller.readHistory();h.handler(async()=>page([]));await h.controller.readHistory(true);assert.match(h.calls.at(-1)[0],/cursor=valid_cursor-01$/);for(const v of[{...page([seed]),workspace_id:'foreign'},page([seed],'x'.repeat(1001)),page([seed],'opaque+/='),{...page([seed]),automatic_dispatch:0}]){h.handler(async()=>v);await h.controller.readHistory();assert.equal(h.controller.currentBinding().vision_id,seed.vision_id);}assert.equal(h.messages.length,4);});
test('actual frame rendering uses bounded same-project routes and plain text for captions',async()=>{const h=harness(),v=clone(seed);v.result.frames[0].caption='<img src=x onerror=PRIVATE>';h.handler(async()=>page([v]));await h.controller.readHistory();const image=h.get('results').children.flatMap(n=>n.children).find(n=>n.src);assert.equal(image.src,renderVisionFrameUrl(seed.project_id,seed.snapshot.request.render_job_id,0));assert.match(text(h.get('results')),/<img src=x onerror=PRIVATE>/);assert.equal(h.get('results').innerHTML,undefined);});
test('runtime rejects private fields coerced flags source-purpose profiles and duplicate entries',()=>{for(const mutate of[v=>v.enabled=1,v=>v.automatic_dispatch=0,v=>v.profiles.push(v.profiles[0]),v=>v.profiles[0].profile.key_receipt.api_key='PRIVATE',v=>v.profiles[0].mock=1,v=>v.profiles[0].profile.purpose='asset_analysis',v=>v.profiles[0].profile.profile_id='nvip_'+'a'.repeat(32),v=>v.profiles[0].asset_analysis_consent_reused=true]){const v=clone(fixture.runtime);mutate(v);assert.throws(()=>validateRenderVisionRuntime(v,seed.workspace_id));}});
test('input rejects wrong scope PTS sample bytes role metadata and fabricated semantic authority',()=>{const s={workspace_id:seed.workspace_id,project:fixture.project};for(const mutate of[v=>v.provider_authorized=0,v=>v.render_job_id='f'.repeat(32),v=>v.binding.source_asset_analysis_consent_reused=true,v=>v.binding.record.observation.semantic_inference_performed=true,v=>v.binding.record.observation.confidence=0,v=>v.binding.record.observation.frames[0].decoded_render_pts++,v=>v.binding.record.observation.frames[0].sha256='bad',v=>v.binding.record.observation.frames[0].width=961,v=>v.binding.input_metadata.width++,v=>v.binding.separate_owner_provider_consent_required=1]){const v=clone(fixture.input);mutate(v);assert.throws(()=>validateRenderVisionInput(v,s));}});
test('history rejects changed render mock invoice or hard-QC and UAT promotions',()=>{const s={workspace_id:seed.workspace_id,project:fixture.project};for(const mutate of[v=>v.owner_uat_accepted=0,v=>v.snapshot.request.acknowledged_rendered_frame_analysis=1,v=>v.snapshot.request.render_job_id='f'.repeat(32),v=>v.snapshot.configuration.profile.purpose='asset_analysis',v=>v.response.mock_transport=false,v=>v.response.input_tokens=null,v=>v.result.mock=false,v=>v.result.semantic_inference_performed=true,v=>v.result.hard_qc_replaced=true,v=>v.result.decoded_render_pts_verified=1,v=>v.result.observed_actual_billed_cost_vnd='0',v=>v.result.frames[0].evidence_frame_reference='foreign',v=>v.result.adapter_provenance.artifact_evidence[0].sha256='f'.repeat(64),v=>v.result.subject_tracks={length:0},v=>v.result.thumbnail_candidate_ids=['vfr_'+'f'.repeat(24)]]){const v=clone(seed);mutate(v);assert.throws(()=>validateRenderVisionHistory(v,s));}});
test('wrong selected operation reply never replaces immutable binding',async()=>{const h=harness();await ready(h);await h.controller.createIntent();const original=clone(h.controller.currentBinding());h.handler(async()=>({...clone(seed),vision_id:'nrvi_'+'f'.repeat(32)}));await h.controller.readSelected();assert.deepEqual(h.controller.currentBinding(),original);assert.equal(h.messages.length,1);});
test('native shell separates render QC from asset Vision and keeps shot review layout',()=>{const native=readFileSync(new URL('../native.mjs',import.meta.url),'utf8'),html=readFileSync(new URL('../native.html',import.meta.url),'utf8'),shot=readFileSync(new URL('../shot-studio.mjs',import.meta.url),'utf8'),server=readFileSync(new URL('../../../services/windows_native/server.py',import.meta.url),'utf8');assert.match(html,/id="native-render-vision-card" hidden/);assert.match(native,/native_render_vision_review===true&&session.access\?\.mode==='registry'/);assert.match(native,/renderVisionUI\?\.sync\(\)/);assert.match(native,/renderVisionUI\?\.isWorking/);assert.match(shot,/move\('#native-render-vision-card','video-review-body'\)/);assert.match(server,/static\['\/native-render-vision.mjs'\]/);assert.match(server,/"native_official_vision":False/);});
test('form and identical history refresh preserve loaded frame nodes while scope changes clear them',async()=>{const h=harness();await ready(h);const inputImage=h.get('input-frames').children[0].children[0];h.get('ack').listeners.change();assert.equal(h.get('input-frames').children[0].children[0],inputImage);h.handler(async()=>page([seed]));await h.controller.readHistory();const resultImage=h.get('results').children.find(n=>n.children[0]?.src).children[0];await h.controller.readHistory();assert.equal(h.get('results').children.find(n=>n.children[0]?.src).children[0],resultImage);h.state.project.revision++;h.controller.sync();assert.equal(h.get('input-frames').children.length,0);assert.equal(h.get('results').children.length,0);});
