const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
export const projectAssets=project=>project?.document?.assets??(project?.document?.asset?[project.document.asset]:[]);
export function filterAssets(assets,{query='',kind='all'}={}) {
  const text=query.toLocaleLowerCase('vi').trim();
  return assets.filter(a=>(kind==='all'||a.kind===kind||kind==='visual'&&['image','video'].includes(a.kind??'image'))&&(!text||`${a.filename??''} ${(a.tags??[]).join(' ')}`.toLocaleLowerCase('vi').includes(text)));
}
export function assetFacts(asset) {
  const dimensions=asset.width&&asset.height?`${asset.width}×${asset.height}`:'Thông số trong chi tiết';
  const label=asset.canonical_role==='logo'?'Logo PNG giữ alpha':asset.canonical_role==='music'?'Nhạc':({video:'Video',audio:'Âm thanh',subtitle:'Phụ đề',image:'Ảnh'}[asset.kind]??'Ảnh');
  return `${label} · ${dimensions}${['video','audio','subtitle'].includes(asset.kind)?` · ${Number(asset.duration_seconds??0).toFixed(1)} giây`:''}`;
}
export function assetPreview(asset,source){
  const media=asset.kind==='video'?`<video controls playsinline preload="metadata" src="${esc(source)}"></video>`:
    asset.kind==='audio'?`<audio controls preload="metadata" src="${esc(source)}"></audio>`:
    asset.kind==='subtitle'?`<pre>${esc((asset.cues??[]).slice(0,30).map(c=>`${c.start} → ${c.end}\n${c.text}`).join('\n\n'))}</pre>`:
    `<img src="${esc(source)}" alt="${esc(asset.filename)}">`;
  return `${media}<p>${esc(asset.filename)}</p><p class="hint">${esc(assetFacts(asset))}</p>`;
}
export function confirmAction({title,description,confirmLabel='Xác nhận'}) {
  return new Promise(resolve=>{const dialog=document.createElement('dialog');dialog.className='confirm-dialog';dialog.setAttribute('aria-labelledby','studio-confirm-title');dialog.innerHTML='<h2 id="studio-confirm-title"></h2><p></p><div class="dialog-footer"><button type="button" class="secondary" data-studio-nav>Hủy</button><button type="button" class="destructive" data-studio-nav></button></div>';dialog.querySelector('h2').textContent=title;dialog.querySelector('p').textContent=description;const buttons=dialog.querySelectorAll('button');buttons[1].textContent=confirmLabel;const done=value=>{dialog.close();dialog.remove();resolve(value);};buttons[0].addEventListener('click',()=>done(false));buttons[1].addEventListener('click',()=>done(true));dialog.addEventListener('cancel',e=>{e.preventDefault();done(false);});document.body.append(dialog);dialog.showModal();buttons[0].focus();});
}
export function assetCard(asset,{thumbnail,used=false,selected=false,picker=false,attached=false,library=false}={}) {
  const provenance=asset.provenance?.source_type??(asset.library_source?'Thư viện':'Tải lên');
  return `<article class="asset-card ${selected?'is-selected':''}" data-asset-card="${esc(asset.id)}">
    <button type="button" class="asset-thumbnail" data-asset-preview="${esc(asset.id)}" aria-label="Xem ${esc(asset.filename)}">${['audio','subtitle'].includes(asset.kind)?`<span>${esc(assetFacts(asset))}</span>`:`<img src="${esc(thumbnail)}" alt="" loading="${library||picker?'eager':'lazy'}">`}</button>
    <div class="asset-card-body"><strong>${esc(asset.filename??'Tư liệu')}</strong><small>${esc(assetFacts(asset))}</small><span class="status-badge ${used?'success':''}">${used?'Đang dùng':attached?'Trong dự án':'Thư viện'}</span><small>${esc(provenance)} · ${asset.rights_confirmed?'Có quyền sử dụng':'Cần kiểm tra quyền'}</small>
    ${asset.available===false?'<small class="error">Tệp nguồn chưa khả dụng</small>':''}
    ${picker?`<label class="asset-selection"><input type="checkbox" data-asset-select="${esc(asset.id)}" ${selected?'checked':''} ${asset.available===false?'disabled':''}> ${selected?'Đã chọn':'Chọn tư liệu'}</label>`:`<div class="asset-actions"><button type="button" class="secondary" data-asset-preview="${esc(asset.id)}">Xem</button>${library?`<button type="button" class="secondary" data-library-add="${esc(asset.id)}" data-workspace-control ${attached||asset.available===false?'disabled':''}>${attached?'Đã có trong dự án':'Thêm vào dự án'}</button>`:`<button type="button" class="secondary" data-asset-choose="${esc(asset.id)}" data-asset-control ${['audio','subtitle'].includes(asset.kind)?'disabled':''}>Dùng cho shot</button><button type="button" class="text-button" data-asset-action="remove" data-asset-id="${esc(asset.id)}" data-asset-control ${used?'disabled':''}>Gỡ khỏi dự án</button>`}</div><details><summary>Chi tiết nguồn</summary><p>${asset.illustration?'Hình minh họa; cần đối chiếu nguồn.':'Tư liệu của bạn; cần kiểm tra nội dung.'}</p><p>Gỡ khỏi dự án giữ nguyên tư liệu thư viện. Nguồn đang dùng cần thay ở shot trước.</p></details>`}
    ${!picker&&!library?`<label>Nhãn tư liệu<input class="asset-tags" data-asset-tags="${esc(asset.id)}" data-asset-control value="${esc((asset.tags??[]).join(', '))}"></label><button type="button" class="text-button" data-asset-action="tag" data-asset-id="${esc(asset.id)}" data-asset-control>Lưu nhãn</button>`:''}</div></article>`;
}

export function initializeAssetLibrary({api,getProject,onAttach,onMessage,picker,container}) {
  container.innerHTML='<div class="card"><div class="workspace-heading"><div><h2>Tư liệu đã lưu</h2><p class="hint">Tư liệu gốc được giữ lại khi gỡ khỏi dự án. Chọn dự án ở thanh bên để thêm nguồn.</p></div><button type="button" class="primary" data-library-picker data-studio-nav>Chọn nhiều tư liệu</button></div><div class="asset-picker-toolbar"><label>Tìm tư liệu<input type="search" data-library-query placeholder="Tên tệp hoặc nhãn"></label><label>Loại<select data-library-kind><option value="all">Tất cả tư liệu</option><option value="visual">Ảnh & video</option><option value="image">Ảnh</option><option value="video">Video</option><option value="audio">Âm thanh / nhạc</option><option value="subtitle">Phụ đề</option></select></label><button type="button" class="secondary" data-library-search data-studio-nav>Tìm</button></div><p data-library-state role="status" aria-live="polite"></p><div class="asset-grid" data-library-grid></div><div class="dialog-footer"><button type="button" class="secondary" data-library-prev data-studio-nav>← Trước</button><span data-library-page></span><button type="button" class="secondary" data-library-next data-studio-nav>Sau →</button></div></div>';
  container.querySelectorAll('input,select,button').forEach(el=>el.dataset.workspaceControl='');
  const $=s=>container.querySelector(s);let page=1,rows=[],request=0;
  async function refresh(){const n=++request;$('[data-library-state]').textContent='Đang tải thư viện…';try{const params=new URLSearchParams({page:String(page),page_size:'24',q:$('[data-library-query]').value,kind:$('[data-library-kind]').value});const result=await api(`/api/assets?${params}`);if(n!==request)return;rows=result.items;const attached=new Set(projectAssets(getProject()).map(a=>a.id));$('[data-library-grid]').innerHTML=rows.map(a=>assetCard(a,{thumbnail:`/api/assets/${encodeURIComponent(a.id)}/thumbnail`,attached:attached.has(a.id),library:true})).join('')||'<div class="empty-state"><h3>Thư viện chưa có tư liệu</h3><p>Tạo dự án, mở Assets và tải ảnh/video để bắt đầu.</p><a class="secondary" href="/?new=1">Tạo video mới</a></div>';$('[data-library-state]').textContent=getProject()?`Dự án nhận tư liệu: ${getProject().document.name}`:'Mở hoặc tạo dự án để thêm tư liệu; bạn vẫn có thể xem thư viện.';$('[data-library-page]').textContent=`Trang ${page} · ${result.total} tư liệu`;$('[data-library-prev]').disabled=page<=1;$('[data-library-next]').disabled=page*24>=result.total;}catch(e){$('[data-library-state]').textContent=`Không đọc được thư viện. ${e.message}. Bấm Tìm để thử lại.`;}}
  $('[data-library-search]').addEventListener('click',()=>{page=1;void refresh();});$('[data-library-kind]').addEventListener('change',()=>{page=1;void refresh();});$('[data-library-query]').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();page=1;void refresh();}});$('[data-library-prev]').addEventListener('click',()=>{page--;void refresh();});$('[data-library-next]').addEventListener('click',()=>{page++;void refresh();});
  $('[data-library-picker]').addEventListener('click',()=>picker.open({source:'library',multiple:true,onChoose:refresh}));
  container.addEventListener('click',async e=>{const preview=e.target.closest('[data-asset-preview]');if(preview){picker.open({source:'library',multiple:false,previewAsset:rows.find(a=>a.id===preview.dataset.assetPreview)});return;}const add=e.target.closest('[data-library-add]');if(!add)return;add.disabled=true;try{await onAttach([add.dataset.libraryAdd]);await refresh();onMessage('Đã thêm tư liệu vào dự án; nguồn gốc được giữ nguyên.');}catch(error){onMessage(error.message,true);add.disabled=false;}});
  return {refresh};
}

/** One picker is reused by project assets, storyboard and the shot inspector. */
export function createAssetPicker({api,getProject,onAttach,onMessage,capabilities={}}) {
  const dialog=document.createElement('dialog');dialog.className='asset-picker';dialog.id='asset-picker-dialog';
  dialog.setAttribute('aria-labelledby','asset-picker-title');
  dialog.innerHTML=`<header class="dialog-header"><div><h2 id="asset-picker-title">Chọn tư liệu</h2><p class="hint">Xem hình, chọn nguồn rồi xác nhận.</p></div><button type="button" class="secondary" data-picker-close aria-label="Đóng cửa sổ chọn tư liệu">Đóng</button></header>
    <div class="asset-picker-toolbar"><label>Nguồn<select data-picker-source><option value="project">Dự án này</option><option value="library">Thư viện</option></select></label><label>Loại<select data-picker-kind><option value="all">Tất cả tư liệu</option><option value="visual">Ảnh & video</option><option value="image">Ảnh</option><option value="video">Video</option><option value="audio">Âm thanh / nhạc</option><option value="subtitle">Phụ đề</option></select></label><label>Tìm tư liệu<input type="search" data-picker-query placeholder="Tên tệp hoặc nhãn"></label><button class="secondary" type="button" data-picker-search>Tìm</button></div>
    <p data-picker-status role="status" aria-live="polite"></p><div class="asset-picker-body"><div class="asset-grid" data-picker-grid></div><aside class="asset-picker-preview" hidden><h3>Xem tư liệu</h3><div data-picker-preview></div></aside></div>
    <footer class="dialog-footer"><button type="button" class="secondary" data-picker-prev>← Trước</button><span data-picker-page></span><button type="button" class="secondary" data-picker-next>Sau →</button><span class="picker-selection-count" role="status"></span><button type="button" class="primary" data-picker-confirm>Xác nhận lựa chọn</button></footer>`;
  dialog.querySelectorAll('input,select,button').forEach(el=>el.dataset.workspaceControl='');
  document.body.append(dialog);
  const $=s=>dialog.querySelector(s);let rows=[],selected=new Map(),page=1,total=0,options={},opener=null,request=0,busy=false,openedProjectId=null;
  const librarySupported=capabilities.asset_library===true;
  $('[data-picker-source] option[value="library"]').disabled=!librarySupported;
  const thumbnail=a=>$('[data-picker-source]').value==='library'?`/api/assets/${encodeURIComponent(a.id)}/thumbnail`:`/api/projects/${getProject().id}/media/${encodeURIComponent(a.id)}/thumbnail`;
  function count(){$('.picker-selection-count').textContent=`${selected.size} đã chọn`;$('[data-picker-confirm]').disabled=busy||selected.size===0||!getProject();}
  function render(){const used=new Set((getProject()?.document.scene_media??[]).map(b=>b.asset_id));$('[data-picker-grid]').innerHTML=rows.map(a=>assetCard(a,{thumbnail:thumbnail(a),used:used.has(a.id),selected:selected.has(a.id),picker:true,attached:projectAssets(getProject()).some(p=>p.id===a.id)})).join('')||'<div class="empty-state"><h3>Chưa tìm thấy tư liệu</h3><p>Đổi bộ lọc hoặc tải ảnh/video tại bước Assets.</p></div>';$('[data-picker-grid]').querySelectorAll('input,button').forEach(el=>el.dataset.workspaceControl='');$('[data-picker-page]').textContent=`Trang ${page} · ${total} tư liệu`;$('[data-picker-prev]').disabled=busy||page<=1;$('[data-picker-next]').disabled=busy||page*24>=total;count();}
  async function load(){const n=++request;busy=true;count();$('[data-picker-status]').textContent='Đang tải tư liệu…';try{const filters={query:$('[data-picker-query]').value,kind:options.visualOnly&&!['image','video'].includes($('[data-picker-kind]').value)?'visual':$('[data-picker-kind]').value};let result;if($('[data-picker-source]').value==='library'){const params=new URLSearchParams({page:String(page),page_size:'24',kind:filters.kind,q:filters.query});result=await api(`/api/assets?${params}`);}else{const filtered=filterAssets(projectAssets(getProject()),filters);result={items:filtered.slice((page-1)*24,page*24),total:filtered.length};}if(n!==request)return;rows=result.items;total=result.total;$('[data-picker-status]').textContent='Chọn tư liệu để thêm vào dự án hoặc dùng cho shot.';render();}catch(e){if(n===request){rows=[];total=0;render();$('[data-picker-status]').textContent=`Không tải được tư liệu. ${e.message}. Bấm Tìm để thử lại.`;}}finally{if(n===request){busy=false;render();}}}
  function close(){request++;busy=false;dialog.close();$('[data-picker-preview]').textContent='';const target=options.returnFocus??(opener?.isConnected?opener:[...document.querySelectorAll('#asset-library-picker,[data-library-picker],#shot-choose-asset')].find(el=>el.getClientRects().length));target?.focus({preventScroll:true});}
  $('[data-picker-close]').addEventListener('click',close);dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
  for(const selector of ['[data-picker-source]','[data-picker-kind]'])$(selector).addEventListener('change',()=>{page=1;void load();});
  $('[data-picker-search]').addEventListener('click',()=>{page=1;void load();});$('[data-picker-query]').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();page=1;void load();}});
  $('[data-picker-prev]').addEventListener('click',()=>{page--;void load();});$('[data-picker-next]').addEventListener('click',()=>{page++;void load();});
  dialog.addEventListener('change',e=>{const input=e.target.closest('[data-asset-select]');if(!input)return;const asset=rows.find(a=>a.id===input.dataset.assetSelect);if(!asset)return;if(options.multiple===false)selected.clear();if(input.checked)selected.set(asset.id,asset);else selected.delete(asset.id);render();});
  function showPreview(asset){const source=$('[data-picker-source]').value==='library'?`/api/assets/${encodeURIComponent(asset.id)}/file`:`/api/projects/${getProject().id}/media/${encodeURIComponent(asset.id)}`;$('[data-picker-preview]').innerHTML=assetPreview(asset,source);$('.asset-picker-preview').hidden=false;}
  dialog.addEventListener('click',e=>{const target=e.target.closest('[data-asset-preview]');if(!target)return;const asset=rows.find(a=>a.id===target.dataset.assetPreview);if(asset)showPreview(asset);});
  $('[data-picker-confirm]').addEventListener('click',async()=>{if(busy||!selected.size)return;busy=true;count();try{const chosen=[...selected.values()],project=getProject();if(!project)throw new Error('Tạo hoặc mở dự án trước khi thêm tư liệu.');if(project.id!==openedProjectId)throw new Error('Dự án đã thay đổi. Đóng cửa sổ và chọn tư liệu lại.');const missing=chosen.filter(a=>!projectAssets(project).some(p=>p.id===a.id));if(missing.length)await onAttach(missing.map(a=>a.id));await options.onChoose?.(chosen);close();onMessage('Đã chọn tư liệu. Lưu shot nếu bạn vừa thay nguồn cảnh.');}catch(e){$('[data-picker-status]').textContent=e.message;}finally{busy=false;count();}});
  return {open(opts={}){options=opts;openedProjectId=getProject()?.id??null;opener=document.activeElement;selected=new Map();page=1;$('[data-picker-source]').value=opts.source==='library'&&librarySupported?'library':'project';$('[data-picker-kind]').value='all';$('[data-picker-query]').value='';$('.asset-picker-preview').hidden=true;if(opts.visualOnly)$('[data-picker-kind]').value='visual';dialog.showModal();void load().then(()=>{const asset=opts.previewAsset??rows.find(a=>a.id===opts.initialPreviewId);if(asset)showPreview(asset);});$('[data-picker-query]').focus();},dialog};
}
