import {newProjectQuality} from './project-quality.mjs';
export const activeOperation = bundle => bundle?.operations?.some(o=>['QUEUED','RUNNING'].includes(o.status))??false;
export const currentIdeas = bundle => (bundle?.ideas??[]).filter(i=>i.generation===bundle.run.generation&&i.status!=='SUPERSEDED');
export const canSendBrief = (bundle,dirty,busy) => Boolean(bundle?.brief?.status==='APPROVED'&&bundle.brief.approval&&!dirty&&!busy&&!activeOperation(bundle)&&bundle.opportunity.status==='APPROVED');
export const canApproveBrief = (bundle,dirty,busy,ack,reviewer) => Boolean(bundle?.brief?.status==='DRAFT'&&!dirty&&!busy&&!activeOperation(bundle)&&ack&&reviewer.trim());
export const safeLink = value => {try {const url=new URL(value);return url.protocol==='https:'&&!url.username&&!url.password?url.href:'#';}catch{return '#';}};
export const initialResearchRun=(search,saved)=>search.get('run')??(search.get('profile')||search.get('new')==='1'?null:saved);
export const ideaStatusName=value=>({CANDIDATE:'Đề xuất',SELECTED:'Đã chọn',REJECTED:'Đã bỏ',SUPERSEDED:'Bản cũ'})[value]??'Chưa rõ trạng thái';
export const supportsProductionIntelligence=session=>(session?.capabilities?.production_intelligence??session?.production_intelligence)===true;
export const briefSendRequest=(brief,session)=>({version:brief.version,...newProjectQuality(session)});
export const briefApprovalRequest=(brief,supported,check,reviewer,acknowledged)=>({path:`/api/${supported?'production':'intelligence'}/briefs/${brief.id}/approve`,body:{version:brief.version,reviewer,acknowledged,...(supported?{binding_sha256:check?.binding_sha256}:{})}});
export const canApprovePreflight=(check,brief,ack,note)=>Boolean(check&&check.brief_id===brief?.id&&check.brief_version===brief?.version&&(!check.human_override_required||(ack&&note.trim())));
export const escapeHtml = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);


export async function installIntelligenceShell(session, options = {}, importer = () => import('./studio-shell.mjs')) {
  if(session?.capabilities?.native_studio_ux !== true)return false;
  try { const shell=await importer();shell.loadStudioShellStyles();shell.mountStudioShell({page:options.page || 'intelligence',context:options.context || 'Nghiên cứu nguồn và lựa chọn ý tưởng'});
    if(session.access?.mode==='registry'){const access=await import('./native-access.mjs');access.installNativeAccess(session);}
    return true; } catch { return false; }
}

if(typeof document!=='undefined'){
  const $=id=>document.getElementById(id),esc=escapeHtml;
  let csrf=null,catalog=null,bundle=null,busy=false,dirty=false,timer=null,preflight=null,phase10=false,creationSession=null;
  const names={NEW:'Mới',REVIEWING:'Đang xem xét',APPROVED:'Đã duyệt brief',REJECTED:'Đã bỏ',IN_PRODUCTION:'Đang sản xuất',PRODUCED:'Đã duyệt video cuối'};
  const dimensions={relevance:'Liên quan',freshness:'Độ mới',audience_fit:'Phù hợp người xem',product_fit:'Phù hợp dự án',hook_strength:'Hook',evidence_strength:'Nguồn căn cứ',production_feasibility:'Khả năng sản xuất',lead_potential:'CTA/khách hàng',novelty:'Khác biệt',risk:'Rủi ro · cao là bất lợi'};
  const messages={INTELLIGENCE_HUMAN_REVIEW_REQUIRED:'Nhập người lựa chọn/duyệt và xác nhận đã kiểm tra.',INTELLIGENCE_STALE_VERSION_RELOAD:'Phiên bản đã thay đổi. Làm mới trước khi tiếp tục.',INTELLIGENCE_APPROVED_BRIEF_REQUIRED:'Lưu và duyệt brief trước khi chuyển sang Studio.',RESEARCH_PUBLIC_HTTPS_URL_REQUIRED:'Chỉ dùng URL HTTPS công khai; không dùng địa chỉ máy nội bộ.',RESEARCH_NO_RELEVANT_SOURCED_FINDINGS:'Nguồn chưa có trích dẫn phù hợp. Tạo nghiên cứu mới với bài cụ thể hơn.',INTELLIGENCE_RESEARCH_IMMUTABLE_CREATE_NEW_RUN:'Nghiên cứu đã lưu giữ nguyên nguồn. Tạo nội dung mới để lấy nguồn lại.',INTELLIGENCE_ALREADY_IN_PRODUCTION_CREATE_NEW_RUN:'Brief đã chuyển sang sản xuất. Tạo nghiên cứu mới cho nội dung khác.'};
  function message(value,error=false){$('ci-message').textContent=value;$('ci-message').hidden=false;$('ci-message').classList.toggle('error',error);}
  async function api(path,body){let response,result;try{response=await fetch(path,{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'Content-Type':'application/json','X-VF-CSRF':csrf}:{},body:body?JSON.stringify(body):undefined});result=await response.json();}catch{throw new Error('Không kết nối được Studio. Bấm Làm mới để kiểm tra và thử lại.');}if(response.status===401&&result.code==='NATIVE_AUTH_SESSION_REQUIRED')location.assign('/login');if(response.status===403&&result.code==='NATIVE_AUTH_FORBIDDEN')throw new Error('Vai trò hiện tại không có quyền thực hiện thao tác này.');if(!response.ok)throw new Error(messages[result.code]??'Thao tác chưa hoàn tất. Kiểm tra kết nối và làm mới để thử lại.');return result;}
  function controls(){const blocked=busy||activeOperation(bundle);document.querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=blocked);$('ci-refresh').disabled=busy;$('ci-runs').disabled=blocked||dirty;$('ci-new').disabled=blocked||dirty;$('ci-create').disabled=blocked||Boolean(bundle);$('ci-query').disabled=blocked||Boolean(bundle);$('ci-urls').disabled=blocked||Boolean(bundle);$('ci-profile').disabled=blocked||Boolean(bundle);$('ci-research').disabled=blocked||!bundle||bundle.run.status!=='NEW';$('ci-generate').disabled=blocked||dirty||!bundle?.findings.length||['IN_PRODUCTION','PRODUCED'].includes(bundle?.opportunity.status);$('ci-approve-brief').disabled=!canApproveBrief(bundle,dirty,busy,$('ci-ack').checked,$('ci-reviewer').value)||(phase10&&!canApprovePreflight(preflight,bundle?.brief,$('ci-override-ack').checked,$('ci-override-note').value));$('ci-send').disabled=!canSendBrief(bundle,dirty,busy);$('ci-save-brief').disabled=blocked||!bundle?.brief||['IN_PRODUCTION','PRODUCED'].includes(bundle?.opportunity.status);document.querySelectorAll('[data-idea]').forEach(row=>{const idea=bundle.ideas.find(i=>i.id===row.dataset.idea);row.querySelector('[data-select]').disabled=blocked||dirty||idea.status==='REJECTED'||['IN_PRODUCTION','PRODUCED'].includes(bundle.opportunity.status);row.querySelector('[data-save-idea]').disabled=blocked||['IN_PRODUCTION','PRODUCED'].includes(bundle.opportunity.status);row.querySelector('[data-reject]').disabled=blocked||['IN_PRODUCTION','PRODUCED'].includes(bundle.opportunity.status);});if(bundle?.opportunity.production_project_id)document.querySelectorAll('#ci-brief-card textarea,#ci-brief-card input').forEach(el=>el.disabled=true);}
  async function queue(){$('ci-queue').innerHTML='<div class="loading-state hint" role="status">Đang đọc cơ hội nội dung…</div>';let values;try{values=await api('/api/intelligence/queue');}catch(error){$('ci-queue').innerHTML='<div class="empty-state hint"><strong>Chưa đọc được cơ hội nội dung</strong><p>Bấm Làm mới để kiểm tra kết nối và thử lại.</p></div>';throw error;}const filter=$('ci-filter').value;$('ci-queue').innerHTML=values.filter(v=>!filter||v.status===filter).map(v=>`<article><button class="text-button" data-open-run="${v.run_id}">${esc(v.topic)}</button><p>${esc(v.related_project??'Nội dung thương hiệu/thị trường')} · ${esc(names[v.status])} · ${Number(v.opportunity_score).toFixed(1)}/100</p><p class="hint">${esc(v.reason_now)}<br>${esc(v.research_freshness)}</p><p>${esc(v.suggested_hook)}${v.candidate_format?' · '+esc(v.candidate_format):''}</p></article>`).join('')||'<div class="empty-state hint"><strong>Chưa có cơ hội ở trạng thái này</strong><p>Đổi bộ lọc hoặc lưu một chủ đề mới để bắt đầu nghiên cứu.</p><a class="button secondary" href="#ci-query">Đến chủ đề và nguồn</a></div>';}
  async function runs(){const values=await api('/api/intelligence/runs');$('ci-runs').innerHTML='<option value="">Chọn nghiên cứu…</option>'+values.map(r=>`<option value="${r.id}">${esc(r.query)}</option>`).join('');$('ci-runs').value=bundle?.run.id??'';}
  async function readPreflight(){preflight=phase10&&bundle?.brief?await api(`/api/production/briefs/${bundle.brief.id}/preflight`):null;}
  function renderPreflight(){const current=phase10&&preflight&&preflight.brief_id===bundle?.brief?.id&&preflight.brief_version===bundle?.brief?.version;$('ci-production-preflight').hidden=!current;if(!current)return;const dates={FRESH:'Nguồn còn trong khoảng theo dõi',STALE:'Có nguồn lịch sử',DATE_UNKNOWN:'Có nguồn chưa rõ ngày công bố',FUTURE_DATE:'Có ngày công bố cần kiểm tra',NO_SOURCES:'Chưa có nguồn'};$('ci-freshness-summary').textContent=(dates[preflight.freshness.status]??preflight.freshness.status)+(preflight.freshness.needs_revalidation?' · cần đối chiếu thời điểm trước khi dùng.':'.');$('ci-similarity-warnings').innerHTML=preflight.similarity.warnings.map(w=>`<article><strong>${escapeHtml(w.title)}</strong><p class="hint">${w.fields.map(f=>`${({title:'Tiêu đề',hook:'Hook',script:'Lời đọc',topic:'Chủ đề'})[f.field]}: ${(f.similarity*100).toFixed(0)}% từ giống`).join(' · ')} · Gợi ý kiểm tra, không phải kết luận trùng nội dung.</p></article>`).join('');$('ci-similarity-override').hidden=!preflight.human_override_required;$('ci-override-ack').checked=false;$('ci-override-note').value=preflight.similarity_override?.note??'';const names={relevance:'Liên quan',freshness:'Độ mới',campaign_priority:'Chiến dịch',project_priority:'Dự án',readiness:'Mức sẵn sàng'};$('ci-priority-details').innerHTML=Object.entries(preflight.priority.components).map(([k,v])=>`<p>${names[k]}: ${Number(v).toFixed(1)} · trọng số ${preflight.priority.weights[k]}</p>`).join('')+`<p>Tổng ${preflight.priority.score}/100 · phạt gần giống ${preflight.priority.duplicate_penalty}. Điểm gợi ý từ cấu hình, chưa dự báo hiệu quả.</p>`;}
  function input(label,field,value,type='textarea'){return `<label>${label}${type==='textarea'?`<textarea data-field="${field}" rows="2">${esc(value)}</textarea>`:`<input data-field="${field}" value="${esc(value)}">`}</label>`;}
  function render(){
    dirty=false;$('ci-ack').checked=false;
    if(bundle){$('ci-query').value=bundle.run.query;$('ci-urls').value=bundle.run.context.source_urls.join('\n');$('ci-profile').value=bundle.run.context.profile.id;}
    $('ci-progress').textContent=bundle?(activeOperation(bundle)?'Đang xử lý yêu cầu bạn đã gửi…':bundle.run.error?`Đã dừng: ${messages[bundle.run.error.code]??'Kiểm tra kết nối hoặc nguồn trước khi tạo yêu cầu mới'}. Không tự gọi lại.`:'Nghiên cứu được lưu trên PC của bạn.'):'Lưu chủ đề rồi bắt đầu nghiên cứu.';
    $('ci-findings-card').hidden=!bundle?.findings.length;
    $('ci-sources').innerHTML=(bundle?.sources??[]).map(s=>`<article><h3><a href="${esc(safeLink(s.reference))}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a></h3><p class="hint">Công bố: ${s.timestamp?esc(new Date(s.timestamp).toLocaleString('vi-VN')):'chưa rõ'} · Lấy: ${esc(new Date(s.retrieved_at).toLocaleString('vi-VN'))}</p><details><summary>Nội dung nguồn đã lưu</summary><pre style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(s.text)}</pre></details></article>`).join('');
    $('ci-findings').innerHTML=(bundle?.findings??[]).map(f=>`<article><strong>${{SOURCED_FACT:'Nguồn đã nêu · chưa xác minh độc lập',MODEL_INFERENCE:'Suy luận · không phải dữ kiện đã xác minh',UNCERTAIN:'Chưa rõ / cần kiểm tra'}[f.kind]}</strong><p>${esc(f.claim)}</p><p class="hint">${esc(f.timestamp_relevance)}</p>${f.source_references.map(c=>`<small>Nguồn: ${esc(bundle.sources.find(s=>s.id===c.source_id)?.title??'Thiếu nguồn')}</small>`).join('')}</article>`).join('');
    $('ci-generate').textContent=bundle?.run.generation?'Tạo lại 5 ý tưởng ↗':'Tạo 5 ý tưởng ↗';
    $('ci-ideas-card').hidden=!currentIdeas(bundle).length;
    $('ci-ideas').innerHTML=currentIdeas(bundle).map((idea,index)=>`<article data-idea="${idea.id}"><p class="eyebrow">${index+1} · <span class="tag">${esc(ideaStatusName(idea.status))}</span> · ${idea.score?Number(idea.score.final_score).toFixed(1)+'/100':'chưa có điểm cho phiên bản này'}</p><h3>${esc(idea.title)}</h3><p><strong>${esc(idea.hook)}</strong></p><p>${esc(idea.angle)}</p><p class="hint">${esc(idea.target_audience)} · ${esc(idea.format)} · ${idea.estimated_duration} giây</p><ul>${idea.key_points.map(p=>`<li>${esc(p)}</li>`).join('')}</ul><p>CTA: ${esc(idea.cta)}</p><p class="hint">Gợi ý biên tập của model, chưa phải dữ kiện: ${esc(idea.rationale)}</p><details><summary>Điểm thành phần và lý do</summary>${idea.score?Object.entries(idea.score.components).map(([k,v])=>`<p><strong>${esc(dimensions[k])}: ${v}</strong> · trọng số ${idea.score.weights[k]}<br><small>${esc(idea.score.rationale[k])}</small></p>`).join(''):''}</details><button data-select class="primary" ${idea.status==='REJECTED'?'disabled':''}>Chọn ý tưởng này</button><details><summary>Sửa hoặc bỏ ý tưởng</summary>${input('Tiêu đề','title',idea.title,'input')}${input('Hook','hook',idea.hook)}${input('Góc nhìn','angle',idea.angle)}${input('Người xem','target_audience',idea.target_audience,'input')}${input('Định dạng','format',idea.format,'input')}${input('Thời lượng giây','estimated_duration',idea.estimated_duration,'input')}${input('Các ý chính · mỗi dòng một ý','key_points',idea.key_points.join('\n'))}${input('CTA','cta',idea.cta)}${input('Lý do biên tập','rationale',idea.rationale)}<button data-save-idea class="secondary">Lưu ý tưởng · cần chọn lại</button><label>Lý do bỏ<textarea data-rejection rows="2" maxlength="2000"></textarea></label><button data-reject class="secondary">Bỏ ý tưởng này</button></details></article>`).join('');
    $('ci-weights').innerHTML=Object.entries(bundle?.run.context.scoring.weights??catalog.scoring.weights).map(([k,v])=>`<p>${esc(dimensions[k])}: ${v}</p>`).join('');
    const brief=bundle?.brief;$('ci-brief-card').hidden=!brief;
    if(brief){for(const [field,id] of [['objective','objective'],['audience','audience'],['angle','angle'],['hook','hook'],['cta','cta']])$(`ci-${id}`).value=brief[field];$('ci-talking-points').value=brief.talking_points.join('\n');$('ci-constraints').value=brief.constraints.join('\n');$('ci-key-facts').innerHTML=brief.key_facts.map(f=>`<p>${esc(f)}</p>`).join('')+'<p class="hint">'+brief.source_references.map(i=>esc(bundle.sources.find(s=>s.id===i)?.title)).join(' · ')+'</p>';$('ci-brief-state').textContent=brief.status==='APPROVED'?`Đã duyệt bởi ${brief.approval.reviewer}.`:'Bản nháp · chỉnh sửa và kiểm tra trước khi duyệt.';}
    const project=bundle?.opportunity.production_project_id;$('ci-project-link').hidden=!project;if(project)$('ci-project-link').href=`/?project=${project}`;
    renderPreflight();controls();
  }
  function schedule(){clearTimeout(timer);if(activeOperation(bundle))timer=setTimeout(()=>guarded(async()=>{if(!dirty)await load(bundle.run.id);})(),1500);}
  async function load(id){bundle=await api(`/api/intelligence/runs/${id}`);await readPreflight();localStorage.setItem('vf-intelligence-run',id);history.replaceState(null,'',`/intelligence?run=${id}`);render();await runs();await queue();schedule();}
  function guarded(fn){return async event=>{if(busy)return;busy=true;controls();try{await fn(event);}catch(error){message(error.message,true);}finally{busy=false;controls();}};}
  $('ci-create').onclick=guarded(async()=>{bundle=await api('/api/intelligence/runs',{query:$('ci-query').value,profile_id:$('ci-profile').value,source_urls:$('ci-urls').value.split('\n').map(v=>v.trim()).filter(Boolean)});await load(bundle.run.id);message('Đã lưu chủ đề. Bắt đầu nghiên cứu khi bạn sẵn sàng.');});
  for(const [id,action] of [['ci-research','research'],['ci-generate','ideas']])$(id).onclick=guarded(async()=>{if(dirty)throw new Error('Lưu chỉnh sửa trước khi tạo lại ý tưởng.');bundle=await api(`/api/intelligence/runs/${bundle.run.id}/${action}`,{version:bundle.run.version,request_key:crypto.randomUUID()});render();schedule();});
  $('ci-ideas').onclick=guarded(async event=>{const row=event.target.closest('[data-idea]');if(!row)return;const idea=bundle.ideas.find(i=>i.id===row.dataset.idea),reviewer=$('ci-reviewer').value;let action,body={version:idea.version,reviewer};if(event.target.matches('[data-select]')){if(dirty)throw new Error('Lưu chỉnh sửa trước khi chọn ý tưởng.');action='select';body.opportunity_version=bundle.opportunity.version;}else if(event.target.matches('[data-reject]')){action='reject';body.changes={note:row.querySelector('[data-rejection]').value};}else if(event.target.matches('[data-save-idea]')){action='edit';body.changes=Object.fromEntries([...row.querySelectorAll('[data-field]')].map(el=>[el.dataset.field,el.dataset.field==='key_points'?el.value.split('\n').filter(Boolean):el.dataset.field==='estimated_duration'?Number(el.value):el.value]));}else return;bundle=await api(`/api/intelligence/ideas/${idea.id}/${action}`,body);await readPreflight();render();await queue();message(action==='select'?'Đã chọn ý tưởng và tạo brief chưa duyệt.':'Đã lưu quyết định; brief liên quan cần duyệt lại.');});
  $('ci-save-brief').onclick=guarded(async()=>{const changes={objective:$('ci-objective').value,audience:$('ci-audience').value,angle:$('ci-angle').value,hook:$('ci-hook').value,talking_points:$('ci-talking-points').value.split('\n').filter(Boolean),cta:$('ci-cta').value,constraints:$('ci-constraints').value.split('\n').filter(Boolean)};bundle=await api(`/api/intelligence/briefs/${bundle.brief.id}/edit`,{version:bundle.brief.version,reviewer:$('ci-reviewer').value,changes});await readPreflight();render();await queue();message('Đã lưu brief. Kiểm tra và duyệt phiên bản mới.');});
  $('ci-approve-brief').onclick=guarded(async()=>{if(phase10&&!canApprovePreflight(preflight,bundle?.brief,$('ci-override-ack').checked,$('ci-override-note').value))throw new Error('Kiểm tra điểm gần giống, nhập lý do tiếp tục và xác nhận trước khi duyệt.');if(phase10&&preflight.human_override_required){await api(`/api/production/planning/${preflight.item_id}`,{version:preflight.planning_version,reviewer:$('ci-reviewer').value,changes:{similarity_override:{warning_sha256:preflight.similarity.warning_sha256,note:$('ci-override-note').value}}});await readPreflight();}const request=briefApprovalRequest(bundle.brief,phase10,preflight,$('ci-reviewer').value,$('ci-ack').checked);bundle=await api(request.path,request.body);await readPreflight();render();await queue();message(phase10?'Đã ghi nhận duyệt brief và kiểm tra nội dung gần giống. Bạn có thể chuyển sang Studio.':'Đã ghi nhận duyệt brief. Bạn có thể chuyển sang Studio.');});
  $('ci-send').onclick=guarded(async()=>{const value=await api(`/api/intelligence/briefs/${bundle.brief.id}/send`,briefSendRequest(bundle.brief,creationSession));await load(bundle.run.id);message('Đã tạo dự án chờ tạo và duyệt kịch bản. Mở dự án sản xuất để tiếp tục.');});
  $('ci-reject-opportunity').onclick=guarded(async()=>{await api(`/api/intelligence/opportunities/${bundle.opportunity.id}/reject`,{version:bundle.opportunity.version,reviewer:$('ci-reviewer').value,note:$('ci-reject-note').value});await load(bundle.run.id);message('Đã bỏ cơ hội, giữ lại nghiên cứu và lịch sử.');});
  $('ci-reviewer').oninput=controls;$('ci-ack').onchange=controls;$('ci-override-ack').onchange=controls;$('ci-override-note').oninput=controls;
  document.querySelectorAll('#ci-brief-card input:not([type=checkbox]),#ci-brief-card textarea:not(#ci-override-note)').forEach(el=>el.oninput=()=>{dirty=true;$('ci-ack').checked=false;controls();});
  $('ci-ideas').oninput=()=>{dirty=true;controls();};
  $('ci-queue').onclick=guarded(async event=>{const button=event.target.closest('[data-open-run]');if(button){if(dirty)throw new Error('Lưu chỉnh sửa trước khi đổi nghiên cứu.');await load(button.dataset.openRun);}});
  $('ci-runs').onchange=guarded(async()=>{if($('ci-runs').value)await load($('ci-runs').value);});
  $('ci-refresh').onclick=guarded(async()=>{if(dirty)throw new Error('Lưu chỉnh sửa trước khi làm mới.');const session=await api('/api/session');csrf=session.csrf;creationSession=session;if(bundle)await load(bundle.run.id);else await queue();message('Đã làm mới dữ liệu.');});
  $('ci-filter').onchange=guarded(queue);
  function profile(){const value=catalog.profiles.find(p=>p.id===$('ci-profile').value);$('ci-urls').value=value.project_references.join('\n');}
  $('ci-profile').onchange=profile;
  $('ci-new').onclick=guarded(async()=>{bundle=null;preflight=null;dirty=false;localStorage.removeItem('vf-intelligence-run');history.replaceState(null,'','/intelligence');$('ci-query').value='';profile();render();await runs();});
  window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
  (async()=>{busy=true;controls();try{const session=await api('/api/session');csrf=session.csrf;creationSession=session;await installIntelligenceShell(session);phase10=supportsProductionIntelligence(session);document.querySelectorAll('[data-phase10-only]').forEach(el=>el.hidden=!phase10);catalog=await api('/api/intelligence/config');$('ci-profile').innerHTML=catalog.profiles.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');const requestedProfile=new URLSearchParams(location.search).get('profile');if(catalog.profiles.some(p=>p.id===requestedProfile))$('ci-profile').value=requestedProfile;profile();await runs();const saved=initialResearchRun(new URLSearchParams(location.search),localStorage.getItem('vf-intelligence-run'));if(saved&&[...$('ci-runs').options].some(o=>o.value===saved))await load(saved);else{await readPreflight();render();await queue();}}catch(error){message(error.message,true);}finally{busy=false;controls();}})();
}
