export const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
export const stageNames={IDEA:'Ý tưởng',BRIEF_READY:'Brief đã duyệt',SCRIPT_DRAFT:'Tạo kịch bản',SCRIPT_REVIEW:'Chờ duyệt kịch bản',STORYBOARD:'Storyboard',READY_TO_PRODUCE:'Sẵn sàng sản xuất',PRODUCING:'Đang sản xuất',VIDEO_REVIEW:'Chờ duyệt video',PRODUCED:'Video đã duyệt',REJECTED:'Đã bỏ',FAILED:'Cần xử lý lỗi'};
export const freshnessNames={FRESH:'Còn trong khoảng theo dõi',DATE_UNKNOWN:'Chưa rõ ngày công bố',FUTURE_DATE:'Cần kiểm tra ngày công bố',STALE:'Nguồn lịch sử',NO_SOURCES:'Chưa có nguồn'};
export const batchEntry=row=>({id:row.id,planning_version:row.planning.version,binding_sha256:row.binding_sha256});
export const productionViews=['dashboard','projects','queue','calendar','library','profiles'];
export const productionView=requested=>productionViews.includes(requested)?requested:'queue';
export function matchesStage(stage,filter){
  if(!filter)return true;
  if(filter==='@in_progress')return ['SCRIPT_DRAFT','STORYBOARD','READY_TO_PRODUCE','PRODUCING'].includes(stage);
  if(filter==='@review')return ['SCRIPT_REVIEW','VIDEO_REVIEW'].includes(stage);
  if(filter==='@errors')return ['FAILED','REJECTED'].includes(stage);
  return stage===filter;
}
export const visibleItems=(items,{search='',profile='',stage='',archived=false}={})=>items.filter(r=>(archived||!r.archived)&&(!profile||r.profile_id===profile)&&matchesStage(r.stage,stage)&&[r.title,r.profile_name,r.related_project,r.planning?.campaign].join(' ').toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi')));
export const projectStage=(project,row)=>project.archived?'ARCHIVED':row?.stage??(!project.document?.proposal?'DRAFT':project.approval?.revision===project.revision?'READY_TO_PRODUCE':project.document.proposal.storyboard?.length?'STORYBOARD':'SCRIPT_REVIEW');
export const visibleProjects=(projects,rows,{search='',stage='',archived=false}={})=>projects.filter(p=>(archived||!p.archived)&&[p.document?.name,p.document?.proposal?.title,rows.find(r=>r.project_id===p.id)?.profile_name].join(' ').toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi'))&&matchesStage(projectStage(p,rows.find(r=>r.project_id===p.id)),stage));
export const localVideoUrl=value=>typeof value==='string'&&/^\/api\/production\/videos\/[a-zA-Z0-9_-]+$/.test(value)?value:null;
export function libraryFacts(row){
  const duration=Number(row.duration_seconds),width=Number(row.width),height=Number(row.height);
  return [Number.isFinite(duration)&&duration>0?duration.toFixed(1)+' giây':'Chưa rõ thời lượng',row.aspect_ratio||row.format||'Chưa rõ định dạng',Number.isInteger(width)&&width>0&&Number.isInteger(height)&&height>0?width+'×'+height:null].filter(Boolean).join(' · ');
}
export const visibleVideos=(items,{search='',approvedOnly=true}={})=>items.filter(r=>(!approvedOnly||r.approved)&&[r.title,r.profile_name,r.related_project,r.campaign].join(' ').toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi')));
export const calendarGroups=(items,group,month)=>{const filtered=items.filter(r=>!r.archived&&(!month||!r.planning.planned_date||r.planning.planned_date.startsWith(month)));const values=new Map();for(const row of filtered){const key=group==='campaign'?(row.planning.campaign||'Chưa có chiến dịch'):group==='profile'?row.profile_name:group==='project'?(row.related_project||'Nội dung chung'):group==='brand'?(row.brand_name||row.brand_id||'Chưa chọn thương hiệu'):group==='priority'?(row.priority.score>=70?'Ưu tiên cao':row.priority.score>=40?'Ưu tiên thường':'Cần xem xét'):group==='format'?row.planning.format:(row.planning.planned_date||'Chưa xếp ngày');if(!values.has(key))values.set(key,[]);values.get(key).push(row);}return [...values.entries()].sort(([a],[b])=>a.localeCompare(b,'vi'));};


export async function installProductionShell(session, options = {}, importer = () => import('./studio-shell.mjs')) {
  if(session?.capabilities?.native_studio_ux !== true)return false;
  try { const shell=await importer();shell.loadStudioShellStyles();shell.mountStudioShell({page:options.page || 'queue',context:options.context || 'Kế hoạch và tiến độ sản xuất'});return true; } catch { return false; }
}

if(typeof document!=='undefined'){
  const $=id=>document.getElementById(id),esc=escapeHtml;
  const requested=new URLSearchParams(location.search).get('view');const view=productionView(requested);
  let queue={items:[]},catalog=null,library={items:[]},projects=[],csrf=null,busy=false,selected=new Set(),activeRow=null,planDirty=false,pendingBatch=null;
  const labels={dashboard:['Sản xuất','Theo dõi tiến độ, kiểm tra nội dung và chọn việc tiếp theo.'],projects:['Dự án','Tìm và mở dự án để tiếp tục chỉnh sửa hoặc xem video.'],queue:['Hàng đợi nội dung','Sắp xếp cơ hội, lên kế hoạch và chọn bước tiếp theo.'],calendar:['Lịch kế hoạch','Nhìn kế hoạch theo ngày, chiến dịch, hồ sơ và định dạng.'],library:['Thư viện video','Xem lại video, quyết định duyệt và nguồn gốc nội dung.'],profiles:['Hồ sơ nội dung','Cấu hình khởi đầu cho dự án, thương hiệu và tin thị trường.']};
  const assignmentNames={UNASSIGNED:'Chưa phân công',ASSIGNED:'Đã phân công',IN_PROGRESS:'Đang làm',DONE:'Xong phần việc'};
  const sourceTypeNames={web:'Trang web',provided_document:'Tài liệu cung cấp',test_fixture:'Nguồn thử nghiệm'};
  const componentNames={relevance:'Liên quan',freshness:'Độ mới của nguồn',campaign_priority:'Ưu tiên chiến dịch',project_priority:'Ưu tiên dự án',readiness:'Mức sẵn sàng'};
  const messages={DUPLICATE_REVIEW_REQUIRED:'Cần xem nội dung gần giống và lưu lý do tiếp tục.',BATCH_STALE_ITEM_RELOAD:'Nội dung đã thay đổi. Làm mới rồi chọn lại.',PLANNING_STALE_VERSION_RELOAD:'Kế hoạch đã thay đổi ở nơi khác. Đóng và mở lại nội dung.',SIMILARITY_WARNING_CHANGED_RELOAD:'Điểm gần giống đã thay đổi. Đóng và mở lại nội dung để kiểm tra.',CURRENT_HUMAN_SCRIPT_REVIEW_REQUIRED:'Mở dự án để duyệt kịch bản trước khi lập storyboard.',APPROVED_BRIEF_WITHOUT_SCRIPT_REQUIRED:'Cần brief đã duyệt và chưa có kịch bản.',PROJECT_ARCHIVED_RESTORE_FIRST:'Khôi phục dự án trước khi tiếp tục.',HUMAN_BATCH_ACTION_FIELDS_REQUIRED:'Nhập người thực hiện, chọn nội dung và xác nhận thao tác.',PLANNING_REVIEWER_REQUIRED:'Nhập người lưu kế hoạch.',BATCH_ITEM_OUTCOME_UNKNOWN:'Kết quả thao tác chưa rõ. Kiểm tra dự án; hệ thống không tự gửi lại.',BATCH_IDEMPOTENCY_KEY_CONFLICT:'Yêu cầu trước đó có nội dung khác. Làm mới để kiểm tra.'};
  function message(value,error=false){$('message').hidden=false;$('message').textContent=value;$('message').classList.toggle('error',error);}
  async function api(path,body){let response,value;try{response=await fetch(path,{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'Content-Type':'application/json','X-VF-CSRF':csrf}:{},body:body?JSON.stringify(body):undefined});value=await response.json();}catch{throw new Error('Không kết nối được Studio. Bấm Làm mới để kiểm tra và thử lại.');}if(!response.ok)throw new Error(messages[value.code]??'Không đọc được dữ liệu. Bấm Làm mới để thử lại.');return value;}
  function controls(){$('studio-main').setAttribute('aria-busy',String(busy));document.querySelectorAll('[data-select]').forEach(el=>el.disabled=busy);document.querySelectorAll('button').forEach(b=>b.disabled=busy);document.querySelectorAll('#planning-form input,#planning-form select,#planning-form textarea').forEach(el=>el.disabled=busy);const allowed=!busy&&!pendingBatch&&selected.size>0&&$('reviewer').value.trim()&&$('batch-ack').checked;$('batch-scripts').disabled=!allowed;$('batch-storyboards').disabled=!allowed;$('batch-pending').hidden=!pendingBatch;if(pendingBatch)$('batch-results').hidden=false;$('selection-count').textContent=selected.size?`${selected.size} nội dung đã chọn`:'Chưa chọn nội dung';}
  function filtered(){return visibleItems(queue.items,{search:$('search').value,profile:$('profile-filter').value,stage:$('stage-filter').value,archived:$('show-archived').checked});}
  function pill(stage){return `<span class="tag ${stage==='PRODUCED'?'success':stage==='FAILED'?'danger':['SCRIPT_REVIEW','VIDEO_REVIEW'].includes(stage)?'warning':''}">${esc(({DRAFT:'Bản nháp',ARCHIVED:'Đã lưu trữ'})[stage]??stageNames[stage]??'Chưa rõ trạng thái')}</span>`;}
  function openHref(row){return row.project_id?`/?project=${encodeURIComponent(row.project_id)}`:row.run_id?`/intelligence?run=${encodeURIComponent(row.run_id)}`:'/intelligence';}
  function card(row,selectable=true){return `<article class="queue-card">${selectable?`<input class="select" type="checkbox" data-select="${row.id}" ${selected.has(row.id)?'checked':''} aria-label="Chọn ${esc(row.title)}">`:'<span></span>'}<div><h3><a class="content-title" href="${openHref(row)}">${esc(row.title)}</a></h3><p>${esc(row.profile_name)}${row.related_project?' · '+esc(row.related_project):''}</p><div>${pill(row.stage)}${row.archived?'<span class="tag">Đã lưu trữ</span>':''}</div><p>${row.planning.campaign?esc(row.planning.campaign)+' · ':''}${row.planning.planned_date?esc(row.planning.planned_date):'Chưa xếp ngày'} · ${esc(row.planning.format)} · ${row.planning.duration_seconds}s</p><p>${row.source_titles?.length?'Nguồn: '+esc(row.source_titles[0]):'Nội dung trực tiếp / chưa có nguồn nghiên cứu'}</p><p>${row.planning.assigned_to?'Phân công: '+esc(row.planning.assigned_to)+' · ':''}${esc(assignmentNames[row.planning.assigned_status]??'Chưa rõ tiến độ')}</p><p>Cập nhật: ${row.updated_at?`<time datetime="${esc(row.updated_at)}">${esc(new Date(row.updated_at).toLocaleString('vi-VN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}))}</time>`:'chưa rõ'}</p></div><div class="metrics"><div class="metric"><div><span>Ưu tiên</span><strong>${Number(row.priority.score).toFixed(0)}</strong></div><div><span>Ý tưởng</span><strong>${row.score===null?'—':Number(row.score).toFixed(0)}</strong></div></div><p>${esc(freshnessNames[row.freshness.status]??row.freshness.status)}</p>${row.freshness.needs_revalidation?'<span class="tag warning">Cần đối chiếu nguồn</span>':''}${row.similarity.warnings.length?`<p>${row.similarity.warnings.length} điểm gần giống ${row.similarity.override_current?'· đã kiểm tra':'· cần xem'}</p>`:''}</div><div class="row-actions"><button data-plan="${row.id}" class="secondary">Xem / lên kế hoạch</button><a class="button secondary" href="${openHref(row)}">${row.project_id?'Mở dự án':'Xem nghiên cứu'}</a></div></article>`;}
  function renderQueue(){const items=filtered();document.querySelectorAll('[data-quick-stage]').forEach(button=>{const active=button.dataset.quickStage===$('stage-filter').value;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});$('queue-list').innerHTML=items.map(r=>card(r)).join('')||'<div class="empty-state"><strong>Chưa có nội dung phù hợp</strong><p>Đổi bộ lọc hoặc bắt đầu nghiên cứu để đưa nội dung vào hàng đợi.</p><a class="button secondary" href="/intelligence">Nghiên cứu nội dung mới</a></div>';const groups=[['Nội dung',queue.items.filter(r=>!r.archived).length,'Trong hàng đợi hiện tại'],['Chờ kiểm tra',queue.items.filter(r=>['SCRIPT_REVIEW','VIDEO_REVIEW'].includes(r.stage)&&!r.archived).length,'Kịch bản hoặc video'],['Sẵn sàng',queue.items.filter(r=>r.stage==='READY_TO_PRODUCE'&&!r.archived).length,'Đã duyệt nội dung và media'],['Video đã duyệt',queue.items.filter(r=>r.stage==='PRODUCED').length,'Đúng phiên bản dự án hiện tại']];$('queue-stats').innerHTML=groups.map(([title,count,note])=>`<div class="stat"><span>${title}</span><strong>${count}</strong><small>${note}</small></div>`).join('');controls();}
  function renderCalendar(){$('calendar-list').innerHTML=calendarGroups(queue.items,$('calendar-group').value,$('calendar-month').value).map(([name,items])=>`<section class="calendar-group"><h2>${esc(name)} <span class="muted">· ${items.length} nội dung</span></h2>${items.map(r=>card(r,false)).join('')}</section>`).join('')||'<div class="empty-state"><strong>Chưa có nội dung ở tháng này</strong><p>Mở hàng đợi để chọn nội dung và lưu ngày dự kiến.</p><a class="button secondary" href="/production?view=queue">Mở hàng đợi</a></div>';}
  function versionDetails(row){const version=row.versions;const hash=(label,value)=>`<p>${label}: ${value?`<code title="${esc(value)}" aria-label="${esc(value)}">${esc(value.slice(0,12))}…</code>`:'chưa có bản lưu'}</p>`;return hash('Kịch bản',version.script_version)+hash('Storyboard',version.storyboard_version)+`<p>Timeline${version.timeline_version?' · phiên bản '+version.timeline_version:''}${version.timeline_schema_version?' · định dạng '+esc(version.timeline_schema_version):''}</p>`+hash('Timeline dựng thực tế',version.render_timeline_sha256)+ (version.timeline_sha256?hash('Timeline biên tập',version.timeline_sha256):'')+hash('Yêu cầu dựng',version.render_job_id)+hash('Tệp video',row.sha256);}
  function renderLibrary(){
    const items=visibleVideos(library.items,{search:$('library-search').value,approvedOnly:$('approved-only').checked});
    $('library-list').innerHTML=items.map(row=>{
      const videoUrl=row.approved?localVideoUrl(row.video_url):null;
      const profile=row.profile_name||catalog.profiles.find(p=>p.id===row.profile_id)?.name||'Nội dung trực tiếp';
      return '<article class="video-card">'+(row.approved&&row.thumbnail_url?'<img src="'+esc(row.thumbnail_url)+'" alt="Khung hình xem trước '+esc(row.title)+'" loading="lazy">':'<div class="empty">'+esc(row.integrity==='FAILED'?'Tệp cần kiểm tra':'Chưa duyệt video')+'</div>')+
        '<div class="content"><h3><a class="content-title" href="/?project='+encodeURIComponent(row.project_id)+'">'+esc(row.title)+'</a></h3><div><span class="tag '+(row.approved?'success':'warning')+'">'+(row.approved?'Đã xem / nghe và duyệt':'Chưa có duyệt hiện hành')+'</span>'+(!row.is_current_project_revision?'<span class="tag">Bản lưu lịch sử</span>':'')+'</div><p>'+esc(profile)+(row.related_project?' · '+esc(row.related_project):'')+(row.campaign?'<br>Chiến dịch: '+esc(row.campaign):'')+'<br>'+esc(new Date(row.created_at).toLocaleDateString('vi-VN'))+' · '+esc(libraryFacts(row))+'</p><div class="video-actions">'+(videoUrl?'<button class="secondary" data-play="'+esc(row.id)+'">Xem video</button><a class="button secondary" href="'+esc(videoUrl)+'" target="_blank" rel="noopener">Mở tệp</a>':'')+'<a class="button secondary" href="/?project='+encodeURIComponent(row.project_id)+'">Mở dự án</a></div><div data-player="'+esc(row.id)+'" hidden></div><details><summary>Nguồn gốc và phiên bản</summary><p>Brief: '+(row.versions.brief_version??'—')+' · Ý tưởng: '+(row.versions.idea_version??'—')+' · Bản dựng: '+row.render_revision+'</p>'+versionDetails(row)+(row.approval?'<p>Quyết định: '+esc(row.approval.decision==='approve'?'Duyệt':'Yêu cầu sửa')+' · '+esc(row.approval.reviewer)+' · '+esc(new Date(row.approval.created_at).toLocaleString('vi-VN'))+'</p>':'')+(row.lineage?'<p>Nghiên cứu: '+esc(row.lineage.research_run_id)+'<br>Ý tưởng: '+esc(row.lineage.content_idea_id)+'<br>Brief: '+esc(row.lineage.content_brief_id)+'</p>':'<p>Nội dung được tạo trực tiếp trong dự án.</p>')+'<p>Tình trạng tệp: '+esc(row.integrity==='PASS'?'Đã kiểm tra':row.integrity==='FAILED'?'Cần kiểm tra tệp':'Chưa kiểm tra')+'</p></details></div></article>';
    }).join('')||'<div class="empty-state"><strong>Chưa có video ở lựa chọn này</strong><p>Video đã duyệt sẽ xuất hiện tại đây. Mở dự án để xem hoặc duyệt bản dựng.</p><a class="button secondary" href="/production?view=projects">Mở dự án</a></div>';
  }
  function projectCard(project){
    const row=queue.items.find(r=>r.project_id===project.id),stage=projectStage(project,row),doc=project.document||{};
    const title=doc.name||doc.proposal?.title||'Dự án chưa đặt tên';
    const template=doc.brand_template?.template,format=template?.aspect_ratio||row?.planning?.format;
    return '<article class="project-card"><div><h3><a class="content-title" href="/?project='+encodeURIComponent(project.id)+'">'+esc(title)+'</a></h3><div>'+pill(stage)+'</div><p>'+esc(row?.profile_name||'Nội dung trực tiếp')+(row?.related_project?' · '+esc(row.related_project):'')+'</p><p>'+[format,(doc.duration_seconds||doc.duration)?(doc.duration_seconds||doc.duration)+' giây mục tiêu':null].filter(Boolean).map(esc).join(' · ')+'</p><p>Cập nhật: '+(project.updated_at?esc(new Date(project.updated_at).toLocaleString('vi-VN')):'chưa rõ')+'</p></div><a class="button secondary" href="/?project='+encodeURIComponent(project.id)+'">Mở dự án</a></article>';
  }
  function renderProjects(){
    const items=visibleProjects(projects,queue.items,{search:$('projects-search').value,stage:$('projects-stage').value,archived:$('projects-archived').checked});
    $('projects-count').textContent=items.length+' dự án';
    $('projects-list').innerHTML=items.map(projectCard).join('')||'<div class="empty-state"><strong>Chưa tìm thấy dự án</strong><p>Đổi bộ lọc hoặc tạo dự án mới để bắt đầu.</p><a class="button primary" href="/?new=1">Video mới</a></div>';
  }
  function renderDashboard(){
    const rows=queue.items.filter(r=>!r.archived),review=rows.filter(r=>['SCRIPT_REVIEW','VIDEO_REVIEW'].includes(r.stage)),active=rows.filter(r=>matchesStage(r.stage,'@in_progress'));
    const stats=[['Dự án',projects.filter(p=>!p.archived).length,'Đang lưu trên PC'],['Đang thực hiện',active.length,'Kịch bản, storyboard và sản xuất'],['Cần kiểm tra',review.length,'Duyệt riêng trong mỗi dự án'],['Video đã duyệt',rows.filter(r=>r.stage==='PRODUCED').length,'Theo nội dung hiện tại']];
    $('dashboard-stats').innerHTML=stats.map(([name,count,note])=>'<div class="stat"><span>'+name+'</span><strong>'+count+'</strong><small>'+note+'</small></div>').join('');
    $('dashboard-review').innerHTML=review.slice(0,5).map(row=>card(row,false)).join('')||'<div class="empty-state"><strong>Chưa có nội dung chờ duyệt</strong><p>Các nội dung đến bước duyệt sẽ xuất hiện tại đây.</p><a class="button secondary" href="/production?view=queue">Mở hàng đợi</a></div>';
    $('dashboard-projects').innerHTML=projects.filter(p=>!p.archived).slice(0,4).map(projectCard).join('')||'<div class="empty-state"><strong>Bắt đầu video đầu tiên</strong><p>Tạo dự án mới, thêm tư liệu và kiểm tra kịch bản trước khi sản xuất.</p><a class="button primary" href="/?new=1">Video mới</a></div>';
  }
  function renderProfiles(){$('profiles-list').innerHTML=catalog.profiles.map(profile=>`<article class="profile-card"><p class="eyebrow">HỒ SƠ NỘI DUNG</p><h2>${esc(profile.name)}</h2><p>${esc(profile.target_audience)}</p><dl><dt>Giọng điệu</dt><dd>${esc(profile.tone)}</dd><dt>Kiểu nội dung</dt><dd>${esc(profile.content_style)}</dd><dt>Định dạng</dt><dd>${profile.preferred_formats.map(esc).join(' · ')}</dd><dt>CTA</dt><dd>${profile.cta_types.map(esc).join(' · ')}</dd><dt>Mục tiêu</dt><dd>${profile.duration_seconds.join(' / ')} giây · ${profile.supported_aspect_ratios.map(esc).join(' / ')}</dd><dt>Bộ nhận diện</dt><dd>${esc(catalog.brand_templates.brands.find(b=>b.id===profile.brand_id)?.name??profile.brand_id)}</dd><dt>Giọng đọc</dt><dd>${esc(profile.voice.name)}</dd><dt>Nguồn</dt><dd>Có tham chiếu, giữ thời điểm công bố; tin chưa rõ ngày cần đối chiếu.</dd></dl><a class="button secondary" href="/intelligence?profile=${esc(profile.id)}">Nghiên cứu nội dung mới</a></article>`).join('');$('priority-config').innerHTML=Object.entries(catalog.priority_configuration.weights).map(([key,value])=>`<span>${esc(componentNames[key])} · trọng số ${value}</span>`).join('')+`<span>Gần giống · trừ ${catalog.priority_configuration.duplicate_penalty} điểm</span>`;}
  function sources(row){return row.freshness.sources.map(s=>`<article><strong>${esc(s.title??'Nguồn đã lưu')}</strong><p>Loại nguồn: ${esc(sourceTypeNames[s.source_type]??'Chưa rõ')}<br>Công bố: ${s.published_at?esc(new Date(s.published_at).toLocaleString('vi-VN')):'chưa rõ'}<br>Lấy nguồn: ${s.fetched_at?esc(new Date(s.fetched_at).toLocaleString('vi-VN')):'chưa rõ'}<br>${esc(freshnessNames[s.status]??s.status)}${s.needs_revalidation?' · cần đối chiếu':''}</p></article>`).join('')||'<p>Chưa có nguồn nghiên cứu đính kèm.</p>';}
  function plan(id){activeRow=queue.items.find(r=>r.id===id);if(!activeRow)return;const row=activeRow,p=row.planning;$('planning-title').textContent=row.title;$('planning-context').innerHTML=pill(row.stage)+`<p>${esc(row.profile_name)} · ${esc(freshnessNames[row.freshness.status])}</p>`;for(const [id,key] of [['plan-campaign','campaign'],['plan-date','planned_date'],['plan-format','format'],['plan-duration','duration_seconds'],['plan-project-priority','project_priority'],['plan-campaign-priority','campaign_priority'],['plan-assignee','assigned_to'],['plan-assignment','assigned_status']])$(id).value=p[key]??'';$('plan-reviewer').value=$('reviewer').value;$('plan-open').href=openHref(row);$('plan-sources').innerHTML=sources(row);$('plan-priority').innerHTML=Object.entries(row.priority.components).map(([key,value])=>`<p>${esc(componentNames[key])}: ${Number(value).toFixed(1)} · trọng số ${row.priority.weights[key]}</p>`).join('')+`<p>Phạt gần giống: ${row.priority.duplicate_penalty} · Tổng: ${row.priority.score}/100</p><p>Điểm gợi ý từ cấu hình; chưa là dự báo hiệu quả.</p>`;$('plan-similarity').hidden=!row.similarity.warnings.length;$('plan-similarity-list').innerHTML=row.similarity.warnings.map(w=>`<p><strong>${esc(w.title)}</strong><br>${w.fields.map(f=>`${({title:'Tiêu đề',hook:'Hook',script:'Lời đọc',topic:'Chủ đề'})[f.field]}: ${(f.similarity*100).toFixed(0)}% từ giống`).join(' · ')}</p>`).join('');$('plan-override').checked=row.similarity.override_current;$('plan-override-note').value=p.similarity_override?.note??'';planDirty=false;$('planning-dialog').showModal();}
  async function reload(){document.querySelectorAll('[data-loading-view]').forEach(node=>{node.hidden=node.dataset.loadingView!==view;});try{queue=await api('/api/production/queue');selected=new Set([...selected].filter(id=>queue.items.some(r=>r.id===id)));if(view==='library')library=await api('/api/production/library');if(['dashboard','projects'].includes(view))projects=await api('/api/projects?archived=include');renderQueue();renderCalendar();if(view==='library')renderLibrary();if(view==='dashboard')renderDashboard();if(view==='projects')renderProjects();}finally{document.querySelectorAll('[data-loading-view]').forEach(node=>node.hidden=true);}}
  function guarded(fn){return async event=>{event?.preventDefault();if(busy)return;busy=true;controls();try{await fn(event);}catch(error){message(error.message,true);}finally{busy=false;controls();}};}
  $('refresh').onclick=guarded(async()=>{if(planDirty)throw new Error('Lưu kế hoạch đang sửa trước khi làm mới.');await reload();message('Đã làm mới dữ liệu.');});
  for(const id of ['search','profile-filter','stage-filter','show-archived'])$(id).addEventListener(id==='search'?'input':'change',renderQueue);
  $('queue-list').onclick=event=>{const select=event.target.closest('[data-select]');if(select){select.checked?selected.add(select.dataset.select):selected.delete(select.dataset.select);$('batch-ack').checked=false;controls();}const button=event.target.closest('[data-plan]');if(button&&!busy)plan(button.dataset.plan);};
  $('calendar-list').onclick=event=>{const button=event.target.closest('[data-plan]');if(button&&!busy)plan(button.dataset.plan);};
  $('dashboard-review').onclick=event=>{const button=event.target.closest('[data-plan]');if(button&&!busy)plan(button.dataset.plan);};
  $('queue-quick-filters').onclick=event=>{const button=event.target.closest('[data-quick-stage]');if(!button||busy)return;$('stage-filter').value=button.dataset.quickStage;renderQueue();};
  for(const id of ['projects-search','projects-stage','projects-archived'])$(id).addEventListener(id==='projects-search'?'input':'change',renderProjects);
  $('select-visible').onclick=()=>{filtered().forEach(row=>selected.add(row.id));$('batch-ack').checked=false;renderQueue();};
  $('select-five').onclick=()=>{selected=new Set(filtered().filter(r=>!['PRODUCED','REJECTED','FAILED','PRODUCING'].includes(r.stage)).slice(0,5).map(r=>r.id));$('batch-ack').checked=false;renderQueue();};
  $('clear-selection').onclick=()=>{selected.clear();$('batch-ack').checked=false;renderQueue();};
  $('reviewer').oninput=controls;$('batch-ack').onchange=controls;
  function renderReceipt(receipt,rows=queue.items){$('batch-results').hidden=false;$('batch-result-items').innerHTML=receipt.items.map(result=>`<p><strong>${esc(rows.find(r=>r.id===result.id)?.title??'Nội dung')}</strong><br>${result.status==='QUEUED'?'Đã gửi tạo kịch bản':result.status==='UPDATED'?'Đã lập storyboard':esc(messages[result.code]??result.code??result.status)}${result.project_id?` · <a href="/?project=${result.project_id}">Mở dự án</a>`:''}</p>`).join('');}
  function rememberBatch(value){pendingBatch=value;try{if(value)sessionStorage.setItem('vf-production-pending-batch',JSON.stringify(value));else sessionStorage.removeItem('vf-production-pending-batch');}catch{}controls();}
  async function sendBatch(action){if(pendingBatch)throw new Error('Kiểm tra yêu cầu đã gửi trước khi thực hiện thao tác mới.');const rows=queue.items.filter(r=>selected.has(r.id));const request={action,items:rows.map(batchEntry),request_key:crypto.randomUUID(),reviewer:$('reviewer').value,acknowledged:$('batch-ack').checked};rememberBatch(request);try{const receipt=await api('/api/production/batch',request);renderReceipt(receipt,rows);if(receipt.status==='COMPLETED')rememberBatch(null);$('batch-ack').checked=false;await reload();message(receipt.status==='OUTCOME_UNKNOWN_NO_REPLAY'?'Yêu cầu trước đó chưa rõ kết quả. Kiểm tra từng dự án trước khi thao tác tiếp.':'Đã ghi nhận kết quả cho từng nội dung. Các bước duyệt vẫn được thực hiện trong dự án.',receipt.status==='OUTCOME_UNKNOWN_NO_REPLAY');}catch(error){message('Chưa nhận đủ kết quả. Bấm kiểm tra kết quả đã lưu; không gửi lại thao tác với mã mới.',true);throw error;}}
  $('batch-recover').onclick=guarded(async()=>{if(!pendingBatch)return;const receipt=await api(`/api/production/batches/${encodeURIComponent(pendingBatch.request_key)}`);renderReceipt(receipt);if(receipt.status==='COMPLETED'){rememberBatch(null);message('Đã đọc lại kết quả đã lưu.');}else message('Yêu cầu chưa có kết quả hoàn tất. Kiểm tra từng dự án; hệ thống không tự gửi lại.',true);await reload();});
  $('batch-dismiss').onclick=()=>{if(pendingBatch&&confirm('Bạn đã kiểm tra trạng thái từng dự án và quyết định đóng yêu cầu chưa rõ? Thao tác này chỉ đóng thông báo trên trình duyệt.')){rememberBatch(null);$('batch-ack').checked=false;message('Đã đóng thông báo. Kết quả và yêu cầu gốc vẫn được lưu.');}};
  $('batch-scripts').onclick=guarded(()=>sendBatch('scripts'));$('batch-storyboards').onclick=guarded(()=>sendBatch('storyboards'));
  $('calendar-month').onchange=renderCalendar;$('calendar-group').onchange=renderCalendar;$('library-search').oninput=renderLibrary;$('approved-only').onchange=renderLibrary;
  $('library-list').onclick=event=>{const button=event.target.closest('[data-play]');if(!button)return;const row=library.items.find(r=>r.id===button.dataset.play);if(!row?.approved||!localVideoUrl(row.video_url))return;const player=document.querySelector(`[data-player="${row.id}"]`);if(!player)return;player.hidden=!player.hidden;if(!player.hidden){player.innerHTML=`<video src="${esc(localVideoUrl(row.video_url))}" controls preload="metadata" aria-label="${esc(row.title)}"></video>`;}else player.innerHTML='';};
  $('planning-close').onclick=()=>{if(planDirty&&!confirm('Đóng và bỏ các thay đổi kế hoạch chưa lưu?'))return;$('planning-dialog').close();planDirty=false;};
  $('planning-dialog').addEventListener('cancel',event=>{if(busy){event.preventDefault();return;}if(planDirty&&!confirm('Đóng và bỏ các thay đổi kế hoạch chưa lưu?'))event.preventDefault();else planDirty=false;});
  $('planning-form').oninput=()=>{planDirty=true;};
  $('planning-form').onsubmit=guarded(async event=>{event.preventDefault();const changes={campaign:$('plan-campaign').value,planned_date:$('plan-date').value||null,format:$('plan-format').value,duration_seconds:Number($('plan-duration').value),project_priority:Number($('plan-project-priority').value),campaign_priority:Number($('plan-campaign-priority').value),assigned_to:$('plan-assignee').value,assigned_status:$('plan-assignment').value};if(activeRow.similarity.warnings.length){if($('plan-override').checked){if(!$('plan-override-note').value.trim())throw new Error('Nhập lý do tiếp tục với nội dung gần giống.');changes.similarity_override={warning_sha256:activeRow.similarity.warning_sha256,note:$('plan-override-note').value};}else changes.similarity_override=null;}await api(`/api/production/planning/${activeRow.id}`,{version:activeRow.planning.version,reviewer:$('plan-reviewer').value,changes});planDirty=false;$('planning-dialog').close();await reload();message('Đã lưu kế hoạch và quyết định đối chiếu nội dung.');});
  window.addEventListener('beforeunload',event=>{if(planDirty){event.preventDefault();event.returnValue='';}});
  (async()=>{busy=true;controls();try{try{pendingBatch=JSON.parse(sessionStorage.getItem('vf-production-pending-batch')??'null');}catch{pendingBatch=null;}[$('page-title').textContent,$('page-subtitle').textContent]=labels[view];const newVideo=['dashboard','projects','library'].includes(view);$('production-new').href=newVideo?'/?new=1':'/intelligence?new=1';$('production-new').textContent=newVideo?'Video mới':'Nghiên cứu mới';$(`${view}-view`).hidden=false;document.querySelector(`[data-view="${view}"]`)?.classList.add('active');$('calendar-month').value=new Date().toLocaleDateString('sv-SE').slice(0,7);const session=await api('/api/session');csrf=session.csrf;await installProductionShell(session,{page:view});catalog=await api('/api/production/profiles');$('profile-filter').innerHTML='<option value="">Mọi hồ sơ</option>'+catalog.profiles.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('stage-filter').innerHTML='<option value="">Mọi bước</option><option value="@in_progress">Đang thực hiện</option><option value="@review">Chờ duyệt</option><option value="@errors">Cần xử lý</option>'+Object.entries(stageNames).map(([value,name])=>`<option value="${value}">${esc(name)}</option>`).join('');$('projects-stage').innerHTML='<option value="">Mọi trạng thái</option><option value="DRAFT">Bản nháp</option><option value="@in_progress">Đang thực hiện</option><option value="@review">Chờ duyệt</option><option value="PRODUCED">Video đã duyệt</option><option value="@errors">Cần xử lý</option>'+Object.entries(stageNames).filter(([stage])=>!['PRODUCED','FAILED','REJECTED'].includes(stage)).map(([stage,name])=>'<option value="'+stage+'">'+esc(name)+'</option>').join('');renderProfiles();await reload();}catch(error){message(error.message,true);}finally{busy=false;controls();}})();
}


