"""create durable project platform

Revision ID: 0001_v2_02
Revises: 
Create Date: 2026-08-26 20:01:35.405060
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_v2_02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner_ref', sa.String(length=160), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('workspace_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('provider_registry',
    sa.Column('provider_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=True),
    sa.Column('provider_key', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('capability', sa.String(length=120), nullable=False),
    sa.Column('adapter', sa.String(length=240), nullable=False),
    sa.Column('routing_mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('supports_dry_run', sa.Boolean(), nullable=False),
    sa.Column('config_ref', sa.String(length=240), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provider_id'),
    sa.UniqueConstraint('workspace_id', 'provider_key', 'capability', name='uq_provider_scope_capability')
    )
    op.create_index('ix_provider_capability_status', 'provider_registry', ['capability', 'status'], unique=False)
    op.create_table('video_projects',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=82), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('niche', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('current_version_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('workspace_id', 'slug', name='uq_video_project_workspace_slug')
    )
    op.create_index(op.f('ix_video_projects_workspace_id'), 'video_projects', ['workspace_id'], unique=False)
    op.create_table('project_versions',
    sa.Column('project_version_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('source_job_id', sa.String(length=80), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['video_projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_version_id'),
    sa.UniqueConstraint('project_id', 'ordinal', name='uq_project_version_ordinal')
    )
    op.create_index(op.f('ix_project_versions_project_id'), 'project_versions', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_versions_workspace_id'), 'project_versions', ['workspace_id'], unique=False)
    op.create_table('jobs',
    sa.Column('job_id', sa.String(length=80), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('project_version_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('request_json', sa.JSON(), nullable=False),
    sa.Column('artifacts_json', sa.JSON(), nullable=False),
    sa.Column('error_json', sa.JSON(), nullable=True),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='ck_jobs_progress'),
    sa.ForeignKeyConstraint(['project_id'], ['video_projects.project_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.project_version_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('ix_jobs_project_updated', 'jobs', ['project_id', 'updated_at'], unique=False)
    op.create_index('ix_jobs_workspace_updated', 'jobs', ['workspace_id', 'updated_at'], unique=False)
    op.create_table('assets',
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('project_version_id', sa.String(length=64), nullable=True),
    sa.Column('job_id', sa.String(length=80), nullable=True),
    sa.Column('asset_class', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('object_key', sa.String(length=768), nullable=False),
    sa.Column('content_type', sa.String(length=160), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_provider', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name='ck_assets_size'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['video_projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.project_version_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index('ix_assets_project_created', 'assets', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_assets_workspace_id'), 'assets', ['workspace_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=80), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key_hash')
    )
    op.create_index(op.f('ix_idempotency_keys_job_id'), 'idempotency_keys', ['job_id'], unique=False)
    op.create_table('job_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=80), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('from_status', sa.String(length=40), nullable=True),
    sa.Column('to_status', sa.String(length=40), nullable=True),
    sa.Column('from_stage', sa.String(length=80), nullable=True),
    sa.Column('to_stage', sa.String(length=80), nullable=True),
    sa.Column('from_progress', sa.Integer(), nullable=True),
    sa.Column('to_progress', sa.Integer(), nullable=True),
    sa.Column('actor_ref', sa.String(length=160), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_job_events_job_created', 'job_events', ['job_id', 'created_at'], unique=False)
    op.create_table('provider_usage',
    sa.Column('usage_id', sa.String(length=64), nullable=False),
    sa.Column('operation_key', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('job_id', sa.String(length=80), nullable=True),
    sa.Column('provider_id', sa.String(length=64), nullable=False),
    sa.Column('provider_key', sa.String(length=120), nullable=False),
    sa.Column('capability', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('operation', sa.String(length=160), nullable=False),
    sa.Column('units', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('unit_name', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['video_projects.project_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_registry.provider_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('usage_id'),
    sa.UniqueConstraint('operation_key')
    )
    op.create_index('ix_provider_usage_project_created', 'provider_usage', ['project_id', 'created_at'], unique=False)
    op.create_table('cost_records',
    sa.Column('cost_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('job_id', sa.String(length=80), nullable=True),
    sa.Column('provider_usage_id', sa.String(length=64), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('needs_approval', sa.Boolean(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("currency = 'VND'", name='ck_cost_records_vnd_only'),
    sa.CheckConstraint('actual_cost IS NULL OR actual_cost >= 0', name='ck_actual_cost_nonnegative'),
    sa.CheckConstraint('estimated_cost IS NULL OR estimated_cost >= 0', name='ck_estimated_cost_nonnegative'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['video_projects.project_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_usage_id'], ['provider_usage.usage_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('cost_id'),
    sa.UniqueConstraint('provider_usage_id')
    )
    op.create_index('ix_cost_records_project_created', 'cost_records', ['project_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cost_records_project_created', table_name='cost_records')
    op.drop_table('cost_records')
    op.drop_index('ix_provider_usage_project_created', table_name='provider_usage')
    op.drop_table('provider_usage')
    op.drop_index('ix_job_events_job_created', table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_idempotency_keys_job_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_assets_workspace_id'), table_name='assets')
    op.drop_index('ix_assets_project_created', table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_jobs_workspace_updated', table_name='jobs')
    op.drop_index('ix_jobs_project_updated', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_project_versions_workspace_id'), table_name='project_versions')
    op.drop_index(op.f('ix_project_versions_project_id'), table_name='project_versions')
    op.drop_table('project_versions')
    op.drop_index(op.f('ix_video_projects_workspace_id'), table_name='video_projects')
    op.drop_table('video_projects')
    op.drop_index('ix_provider_capability_status', table_name='provider_registry')
    op.drop_table('provider_registry')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
