// Shipped controllers over signed local HTTP; synthetic review, never Owner UAT.
import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {initializeNativeRenderThumbnail,renderThumbnailImageUrl} from '../apps/studio-web/native-render-thumbnail.mjs';
import {initializeNativeRenderThumbnailRights} from '../apps/studio-web/native-render-thumbnail-rights.mjs';
import {initializeNativePublications} from '../apps/studio-web/native-publications.mjs';
let stdin='';for await(const chunk of process.stdin)stdin+=chunk;const config=JSON.parse(stdin);
assert.match(config.origin,/^http:\/\/127\.0\.0\.1:[1-9][0-9]{0,4}$/);
const calls=[],messages=[],received=new Map();const auth=await fetch(config.origin+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:config.token}),signal:AbortSignal.timeout(10000)});
assert.equal(auth.status,200);const login=await auth.json(),cookie=auth.headers.getSetCookie()[0].split(';')[0];
async function api(path,body,expected=200){const response=await fetch(config.origin+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',Cookie:cookie,'X-VF-CSRF':login.csrf},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(30000)});
  const value=await response.json();calls.push({method:body?'POST':'GET',path,status:response.status});assert.equal(response.status,expected,JSON.stringify(value));received.set(path,structuredClone(value));return value;}
const session=await api('/api/session');assert.equal(session.capabilities.native_live_publishing,false);assert.equal(session.capabilities.native_official_vision,false);
for(const path of['/native-publications.mjs','/native-render-thumbnail.mjs','/native-render-thumbnail-rights.mjs','/native.mjs','/native.html']){const response=await fetch(config.origin+path,{headers:{Cookie:cookie},signal:AbortSignal.timeout(10000)});assert.equal(response.status,200);await response.text();calls.push({method:'GET',path,status:200});}
const original=await api('/api/projects/'+config.project),job=original.jobs.find(j=>j.kind==='render'&&j.status==='succeeded'&&j.revision===original.revision);assert.ok(job);assert.equal(job.final_review,null);
// This decision belongs only to the restored synthetic CPU fixture, not an accepted artifact.
const reviewed=await api('/api/jobs/'+job.id+'/review',{revision:job.revision,reviewer:'EXPLICIT SYNTHETIC THUMBNAIL PUBLICATION REHEARSAL — NOT OWNER UAT',acknowledged:true,decision:'approve',note:'Isolated copied fixture; no real Owner viewing or publication permission.'});
assert.deepEqual(reviewed.document,original.document);assert.equal(reviewed.revision,original.revision);
const nodes=new Map();class Node{constructor(tag='details'){this.tagName=tag.toUpperCase();this.children=[];this.value='';this.checked=false;this.dataset={};this.listeners={};this.textContent='';this.style={};}set id(v){this._id=v;nodes.set(v,this);}get id(){return this._id;}append(...v){this.children.push(...v);}replaceChildren(...v){this.children=[...v];}addEventListener(k,v){this.listeners[k]=v;}}
const dom={createElement:tag=>new Node(tag),getElementById:id=>{if(!nodes.has(id))nodes.set(id,new Node());return nodes.get(id);}},get=k=>dom.getElementById('native-render-thumbnail-rights-'+k),pub=k=>dom.getElementById('native-publish-'+k);
const state={project:reviewed,workspace_id:session.access.workspace_id,canEdit:true,canManage:true,dirty:false,busy:false,active:false};let rights=null,publication=null;
const thumbnail=initializeNativeRenderThumbnail({root:dom,api,getState:()=>({...state,locked:rights?.isWorking()??false}),onMessage:(...v)=>messages.push(v)});
await thumbnail.readHistory();const choices=received.get('/api/projects/'+config.project+'/render-thumbnails?limit=25').items,choice=choices.findIndex(t=>t.thumbnail_asset_id===config.thumbnail);assert.ok(choice>=0);dom.getElementById('native-render-thumbnail-list').children[choice].listeners.click();const selected=structuredClone(thumbnail.currentSelection());
const image=await fetch(config.origin+renderThumbnailImageUrl(config.project,config.thumbnail),{headers:{Cookie:cookie},signal:AbortSignal.timeout(30000)});assert.equal(image.status,200);assert.equal(image.headers.get('content-type'),'image/png');const png=Buffer.from(await image.arrayBuffer());assert.equal(createHash('sha256').update(png).digest('hex'),selected.snapshot.image.sha256);calls.push({method:'GET',path:renderThumbnailImageUrl(config.project,config.thumbnail),status:200});
rights=initializeNativeRenderThumbnailRights({root:dom,api,getState:()=>({...state}),getSelection:()=>thumbnail.currentSelection(),onMessage:(...v)=>messages.push(v),onWorking:()=>{thumbnail.controls();publication?.controls();}});
await rights.readConfig();await rights.readInput();await rights.readHistory();assert.equal(get('list').children.length,config.original_rights_count);
pub('platform').value='youtube';pub('privacy').value='private';publication=initializeNativePublications({root:dom,api,getState:()=>({...state,busy:rights.isWorking()}),getThumbnailSelection:()=>thumbnail.currentSelection(),getThumbnailRightsSelection:()=>rights.currentRecord(),onMessage:(...v)=>messages.push(v)});
const base='/api/projects/'+config.project+'/publications',newPublications=[];pub('title').value='Explicit synthetic thumbnail distribution rehearsal';
async function create(use){pub('thumbnail').checked=use;pub('thumbnail').listeners.change();await publication.execute('create');const row=structuredClone(received.get(base));assert.equal(row.status,'blocked');assert.equal(row.snapshot.validation.rights.status,'failed');assert.equal(row.mock,true);assert.equal(row.external_action,false);assert.equal(row.publish_enabled,false);assert.equal(row.receipt,null);delete row.idempotent_replay;newPublications.push(row);return row;}
const legacy=await create(false);assert.equal(legacy.snapshot.request.metadata.thumbnail_asset_id,null);assert.equal('thumbnail'in legacy.snapshot.validation,false);
const before=await create(true);assert.equal(before.snapshot.request.metadata.thumbnail_asset_id,config.thumbnail);assert.ok(before.snapshot.validation.attention.includes('NATIVE_PUBLICATION_THUMBNAIL_CURRENT_OWNER_EXCEPTION_REQUIRED'));
get('reason').value='EXPLICIT SYNTHETIC PUBLICATION THUMBNAIL EXCEPTION — NOT INDEPENDENT LICENSE OR OWNER UAT';get('reference').value='document:explicit-synthetic-thumbnail-publication-rehearsal';get('days').value='7';get('publish').checked=get('ack').checked=get('independent').checked=true;await rights.record('grant');const grant=structuredClone(rights.currentRecord());delete grant.idempotent_replay;
assert.equal(pub('thumbnail').checked,false);assert.equal(pub('ack').checked,false);assert.equal(thumbnail.currentSelection().thumbnail_asset_id,config.thumbnail);
const bound=await create(true),binding=bound.snapshot.validation.thumbnail;assert.equal(binding.status,'passed');assert.equal(binding.owner_exception.override_id,grant.override_id);assert.equal(binding.image.sha256,selected.snapshot.image.sha256);assert.equal(binding.image.rights_status,'unknown');assert.equal(binding.image.license,null);assert.equal(binding.official_thumbnail_transport_configured,false);assert.equal(binding.source_asset_rights_granted,false);assert.equal(binding.publishing_authorized,false);assert.equal(binding.owner_uat_accepted,false);
assert.notEqual(bound.publication_id,before.publication_id);assert.deepEqual(before.snapshot,(await api(base+'/'+before.publication_id)).snapshot);
await api(base+'/'+bound.publication_id+'/approve',{expected_fingerprint:bound.request_fingerprint,expected_artifact_sha256:bound.snapshot.final_sha256,acknowledged:true},409);
const blockedRun=await api(base+'/'+bound.publication_id+'/dry-run',{expected_fingerprint:bound.request_fingerprint});assert.equal(blockedRun.status,'blocked');assert.equal(blockedRun.approval,null);assert.equal(blockedRun.receipt,null);
get('reason').value='EXPLICIT SYNTHETIC THUMBNAIL EXCEPTION REVOCATION';get('reference').value='document:explicit-synthetic-thumbnail-publication-revoke';get('days').value='7';get('ack').checked=get('independent').checked=true;await rights.record('revoke');const revoked=structuredClone(rights.currentRecord());delete revoked.idempotent_replay;assert.equal(revoked.snapshot.request.override_id,grant.override_id);
const after=await create(true);assert.equal('thumbnail'in after.snapshot.validation,false);assert.ok(after.snapshot.validation.attention.includes('NATIVE_PUBLICATION_THUMBNAIL_CURRENT_OWNER_EXCEPTION_REQUIRED'));
await publication.read();assert.equal(pub('history').children.length,4);assert.equal(pub('ack').checked,false);assert.equal(pub('approve').disabled,true);assert.equal(pub('run').disabled,true);
assert.deepEqual((await api('/api/projects/'+config.project)).document,original.document);assert.equal(calls.filter(c=>c.path.endsWith('/review')&&c.method==='POST').length,1);
assert.ok(!calls.some(c=>c.path.includes('official-publications')||c.path.endsWith('/process')||c.path.endsWith('/jobs')));
process.stdout.write(JSON.stringify({status:'PASS',original_project:original,synthetic_final_reviewed_project:reviewed,original_thumbnail:selected,new_rights:[grant,revoked],new_publications:newPublications,calls,signed_http:true,dom_controller_tested:true,actual_parent_browser_executed:false,thumbnail_metadata_bound:true,source_rights_still_blocked:true,all_publications_blocked:true,official_thumbnail_transport_configured:false,external_dispatches:0,paid_operations:0,real_owner_legal_override:false,real_provider_tested:false,owner_uat_accepted:false})+'\n');
