// Shipped controllers, signed local HTTP, explicitly synthetic Owner exceptions.
import assert from'node:assert/strict';import{createHash}from'node:crypto';
import{initializeNativeRenderThumbnail,renderThumbnailImageUrl}from'../apps/studio-web/native-render-thumbnail.mjs';
import{initializeNativeRenderThumbnailRights}from'../apps/studio-web/native-render-thumbnail-rights.mjs';
let stdin='';for await(const chunk of process.stdin)stdin+=chunk;const config=JSON.parse(stdin);assert.match(config.origin,/^http:\/\/127\.0\.0\.1:[1-9][0-9]{0,4}$/);
const calls=[],messages=[],received=new Map();const auth=await fetch(config.origin+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:config.token}),signal:AbortSignal.timeout(10000)});assert.equal(auth.status,200);const login=await auth.json(),cookie=auth.headers.getSetCookie()[0].split(';')[0];
async function api(path,body){const response=await fetch(config.origin+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',Cookie:cookie,'X-VF-CSRF':login.csrf},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(30000)});const value=await response.json();calls.push({method:body?'POST':'GET',path,status:response.status});assert.equal(response.status,200,JSON.stringify(value));received.set(path,structuredClone(value));return value;}
const session=await api('/api/session');assert.equal(session.capabilities.native_render_thumbnail_rights_review,true);assert.equal(session.capabilities.native_live_publishing,false);assert.equal(session.capabilities.native_official_vision,false);
for(const path of['/native-render-thumbnail-rights.mjs','/native-render-thumbnail.mjs','/native.mjs','/native.html','/native.css','/shot-studio.mjs']){const response=await fetch(config.origin+path,{headers:{Cookie:cookie},signal:AbortSignal.timeout(10000)});assert.equal(response.status,200);await response.text();calls.push({method:'GET',path,status:200});}
const nodes=new Map();class Node{constructor(tag='details'){this.tagName=tag.toUpperCase();this.children=[];this.value='';this.checked=false;this.dataset={};this.listeners={};this.textContent='';this.style={};}set id(v){this._id=v;nodes.set(v,this);}get id(){return this._id;}append(...v){this.children.push(...v);}replaceChildren(...v){this.children=[...v];}addEventListener(k,v){this.listeners[k]=v;}}
const dom={createElement:tag=>new Node(tag),getElementById:id=>{if(!nodes.has(id))nodes.set(id,new Node());return nodes.get(id);}},get=k=>dom.getElementById('native-render-thumbnail-rights-'+k);
const state={project:await api('/api/projects/'+config.project),workspace_id:session.access.workspace_id,canEdit:true,canManage:true,dirty:false,busy:true,active:false},original=structuredClone(state.project);let rights=null;
const thumbnail=initializeNativeRenderThumbnail({root:dom,api,getState:()=>({...state,locked:rights?.isWorking()??false}),onMessage:(...v)=>messages.push(v)});state.busy=false;thumbnail.controls();await thumbnail.readHistory();
const thumbPage=received.get('/api/projects/'+config.project+'/render-thumbnails?limit=25');const choice=thumbPage.items.findIndex(v=>v.thumbnail_asset_id===config.thumbnail);assert.ok(choice>=0);dom.getElementById('native-render-thumbnail-list').children[choice].listeners.click();const selected=structuredClone(thumbnail.currentSelection());assert.equal(selected.snapshot.image.rights_status,'unknown');
const image=await fetch(config.origin+renderThumbnailImageUrl(config.project,config.thumbnail),{headers:{Cookie:cookie},signal:AbortSignal.timeout(30000)});assert.equal(image.status,200);assert.equal(image.headers.get('content-type'),'image/png');assert.equal(image.headers.get('cache-control'),'no-store');const bytes=Buffer.from(await image.arrayBuffer());assert.equal(createHash('sha256').update(bytes).digest('hex'),selected.snapshot.image.sha256);assert.equal(bytes.length,selected.snapshot.image.bytes);calls.push({method:'GET',path:renderThumbnailImageUrl(config.project,config.thumbnail),status:200});
rights=initializeNativeRenderThumbnailRights({root:dom,api,getState:()=>({...state}),getSelection:()=>thumbnail.currentSelection(),onMessage:(...v)=>messages.push(v),onWorking:()=>thumbnail.controls()});const count=calls.length;rights.sync();rights.controls();assert.equal(calls.length,count);assert.equal(get('ack').checked,false);assert.equal(get('publish').checked,false);assert.equal(get('grant').disabled,true);
await rights.readConfig();await rights.readInput();await rights.readHistory();assert.equal(get('list').children.length,config.original_rights_count);
const input=received.get('/api/projects/'+config.project+'/render-thumbnail-rights/input/'+config.thumbnail);assert.equal(input.binding.thumbnail_snapshot_sha256,selected.snapshot_sha256);assert.equal(input.binding.original_source_rights_review_still_required,true);
function fill(publish){get('reason').value='EXPLICIT SYNTHETIC UI THUMBNAIL EXCEPTION — NOT LICENSE OR REAL OWNER ACCEPTANCE';get('reference').value='document:explicit-synthetic-thumbnail-rights-studio-rehearsal';get('days').value='7';get('publish').checked=publish;get('ack').checked=get('independent').checked=true;rights.controls();}
const newRights=[];
for(const publish of[false,true]){fill(publish);const before=calls.length;get('independent').checked=false;await rights.record('grant');assert.equal(calls.length,before);get('independent').checked=true;await rights.record('grant');const row=structuredClone(rights.currentRecord());assert.equal(row.action,'grant');assert.equal(row.snapshot.request.allow_publishing_review,publish);assert.equal(row.rights_status,'unknown');assert.equal(row.license,null);assert.equal(row.publishing_authorized,false);assert.equal(row.snapshot.source_asset_rights_granted,false);assert.equal(row.owner_uat_accepted,false);assert.equal(row.idempotent_replay,false);delete row.idempotent_replay;newRights.push(row);assert.equal(get('ack').checked,false);assert.equal(get('independent').checked,false);assert.equal(get('publish').checked,false);assert.equal(thumbnail.currentSelection().thumbnail_asset_id,config.thumbnail);}
fill(true);const prior=rights.currentRecord();await rights.record('revoke');const revoked=structuredClone(rights.currentRecord());assert.equal(revoked.snapshot.request.override_id,prior.override_id);assert.equal(revoked.snapshot.request.expected_override_sha256,prior.snapshot_sha256);assert.equal(revoked.snapshot.request.allow_publishing_review,false);assert.equal(revoked.snapshot.expires_at,null);assert.equal(revoked.idempotent_replay,false);delete revoked.idempotent_replay;newRights.push(revoked);
state.canManage=false;rights.sync();await rights.readInput();await rights.readHistory();assert.equal(get('list').children.length,config.original_rights_count+3);assert.equal(get('grant').disabled,true);assert.equal(get('revoke').disabled,true);assert.equal(get('config').disabled,true);assert.equal(get('history').disabled,false);
assert.deepEqual(await api('/api/projects/'+config.project),original);assert.deepEqual(await api('/api/session'),session);assert.equal(messages.length,2);assert.ok(!calls.some(v=>v.path.endsWith('/process')||v.path.endsWith('/jobs')||v.path.includes('publication')));
process.stdout.write(JSON.stringify({status:'PASS',input,original_project:original,original_selected_thumbnail:selected,new_rights:newRights,selected_png_sha256:createHash('sha256').update(bytes).digest('hex'),selected_png_bytes:bytes.length,calls,signed_http:true,dom_controller_tested:true,actual_parent_browser_executed:false,external_dispatches:0,paid_operations:0,rights_status:'unknown',real_provider_tested:false,owner_uat_accepted:false})+'\n');
