// Actual local HTTP + isolated DOM controller; no browser, user or provider acceptance.
import assert from 'node:assert/strict';import{initializeNativeGoogleOAuth}from'../apps/studio-web/native-google-oauth.mjs';
import{request as httpRequest}from'node:http';
let raw='';for await(const chunk of process.stdin)raw+=chunk;const input=JSON.parse(raw),nodes=new Map(),calls=[];
class Node{constructor(){this.children=[];this.value='';this.checked=false;this.dataset={};this.listeners={};this.textContent='';}set id(v){this._id=v;nodes.set(v,this);}get id(){return this._id;}append(...v){this.children.push(...v);}replaceChildren(...v){this.children=[...v];}addEventListener(k,v){this.listeners[k]=v;}removeAttribute(name){delete this[name];}}
const root={createElement:()=>new Node(),getElementById(v){if(!nodes.has(v))nodes.set(v,new Node());return nodes.get(v);}},get=id=>root.getElementById('native-google-oauth-'+id),messages=[];
async function api(path,body){const response=await fetch(input.origin+path,{method:body===undefined?'GET':'POST',headers:{'Cookie':'vf_native_session='+input.cookie,'X-VF-CSRF':input.csrf,'Content-Type':'application/json','Connection':'close'},body:body===undefined?undefined:JSON.stringify(body),redirect:'error'});
 const value=await response.json();calls.push({method:body===undefined?'GET':'POST',action:path.split('?')[0].split('/').at(-1),status:response.status});if(!response.ok)throw new Error('Local request refused');return value;}
const project=await api('/api/projects/'+input.project_id),session=await api('/api/session'),state={workspace_id:session.access.workspace_id,project,canManage:session.access.permissions.includes('manage'),busy:false,dirty:false,active:false};let counter=0;
const controller=initializeNativeGoogleOAuth({root,api,getState:()=>state,onMessage:()=>messages.push('Fixed controller notice'),uuid:()=> 'explicit-native-ui-http-'+(++counter),origin:()=>input.origin,now:()=>input.stamp});
assert.equal(calls.length,2);await controller.readConfig();get('slot').value=input.analytics_slot;get('ack').checked=get('mock-ack').checked=true;await controller.createAuthorization();
const auth=controller.currentBinding().authorization;assert.equal(auth.status,'awaiting_callback');await controller.getAuthorizationLink();assert.equal(get('external-link').hidden,false);
// Explicit synthetic completion of the external-browser step, never navigation.
const link=new URL(get('external-link').href),callback=await new Promise((resolve,reject)=>{const req=httpRequest(input.origin+'/oauth/google/callback?'+new URLSearchParams({state:link.searchParams.get('state'),code:input.synthetic_code}),
 {headers:{'Sec-Fetch-Site':'cross-site','Sec-Fetch-Mode':'navigate','Sec-Fetch-Dest':'document'}},response=>{let body='';response.on('data',chunk=>body+=chunk);response.on('end',()=>resolve({status:response.statusCode,body}));});req.on('error',reject);req.end();});assert.equal(callback.status,200);assert.match(callback.body,/Protocol mock completed/);
calls.push({method:'GET',action:'synthetic-external-callback',status:callback.status});await controller.readSelected();assert.equal(controller.currentBinding().authorization.status,'consumed');assert.equal(get('external-link').hidden,true);
await controller.readHistory('operation');const first=controller.currentBinding().operation;assert.equal(first.status,'succeeded');get('refresh-ack').checked=get('mock-ack').checked=true;await controller.refreshGrant();const rotated=controller.currentBinding().operation;
assert.equal(rotated.status,'succeeded');assert.notEqual(rotated.operation_id,first.operation_id);assert.notEqual(rotated.result.grant_receipt.reference,first.result.grant_receipt.reference);assert.equal(rotated.result.credential_selected,false);
controller.prepareNew();get('ack').checked=get('mock-ack').checked=true;await controller.createAuthorization();const prepared=controller.currentBinding().authorization;assert.equal(prepared.status,'awaiting_callback');await controller.cancelAuthorization();assert.equal(controller.currentBinding().authorization.status,'cancelled');
await controller.readHistory('authorization');await controller.readHistory('operation');assert.equal(messages.length,0);assert.deepEqual(await api('/api/projects/'+input.project_id),project);assert.deepEqual(await api('/api/session'),session);
assert.equal(calls.some(v=>v.action==='publish'),false);assert.equal(get('external-link').hidden,true);assert.doesNotMatch(get('detail').textContent,/"(?:access_token|refresh_token|client_secret|authorization_url)"\s*:|state=/);
process.stdout.write(JSON.stringify({fixture_kind:'actual_local_http_isolated_dom_explicit_protocol_mock_not_browser_or_owner_acceptance',http_requests:calls.length,calls,current_project_and_session_exact:true,explicit_start_private_link_synthetic_callback_read_refresh_cancel_history:true,
 no_initialization_provider_calls_no_auto_refresh_publish_or_credential_selection:true,original_operation_id:first.operation_id,rotated_operation_id:rotated.operation_id,cancelled_authorization_id:prepared.authorization_id,private_url_state_cookie_csrf_or_tokens_exported:false}));
