"""Explicit development request after a known completed response rejected on references.

Never resumes an unknown provider outcome; original request/response/error is preserved.
"""
from pathlib import Path
import sys
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
import json
import uuid
from services.windows_native.contracts import MODEL, canonical, digest
from services.windows_native.pipeline import Config
from services.windows_native.store import Store
from services.windows_native.intelligence_service import IntelligenceService

repo=Path(__file__).resolve().parents[1]; directory=repo/'evidence/post-mvp-roadmap/phase-9'; config=Config()
path=directory/'practical-cases.json';records=json.loads(path.read_bytes()); service=IntelligenceService(config,Store(config.data_root))
for record in records:
    b=service.bundle(record['run_id'])
    if b['run']['status']!='FAILED' or (b['run']['error'] or {}).get('code')!='IDEA_EVIDENCE_REFERENCE_UNKNOWN_OR_UNSOURCED': continue
    previous=b['operations'][0]
    response_path=config.data_root/'intelligence-operations'/previous['id']/'idea-response.json'
    response=json.loads(response_path.read_bytes())
    if response['status']!='completed' or response['model']!=MODEL: raise SystemExit('Unknown outcome cannot be regenerated by this helper')
    archive=directory/f"case-{record['number']:02}-invalid-references-{previous['id']}.json"
    if archive.exists(): raise SystemExit('Explicit regeneration already attempted; inspect instead of replay')
    archive.write_bytes(canonical(b))
    record['known_completed_invalid_provider_response']={'operation_id':previous['id'],'response_id':response['id'],'response_sha256':digest(response),'actual_provider_calls':1,'error_preserved':True}
    service.enqueue(b['run']['id'],b['run']['version'],'ideas',uuid.uuid4().hex)
    service.run_one();b=service.bundle(record['run_id'])
    record.update(status=b['run']['status'],operations=b['operations'],bundle_sha256=digest(b),idea_ids=[i['id'] for i in b['ideas']],actual_provider_calls=b['run']['provider_metadata'].get('last_idea_generation',{}).get('actual_provider_calls',0))
    (directory/f"case-{record['number']:02}.json").write_bytes(canonical(b));path.write_bytes(canonical(records))
    print(json.dumps({'number':record['number'],'explicit_new_generation':True,'status':record['status'],'ideas':len(b['ideas']),'error':b['run']['error']}),flush=True)
